/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  JoblogicAPIModelsCreateAreaRequest,
  JoblogicAPIModelsCreateAreaResponse,
  JoblogicAPIModelsGetAreaResponse,
  JoblogicAPIModelsSearchAreaRequest,
  JoblogicAPIModelsSearchAreaResponse,
  JoblogicAPIModelsUpdateAreaRequest,
  JoblogicAPIModelsUpdateAreaResponse,
} from '../models/index';
import {
    JoblogicAPIModelsCreateAreaRequestFromJSON,
    JoblogicAPIModelsCreateAreaRequestToJSON,
    JoblogicAPIModelsCreateAreaResponseFromJSON,
    JoblogicAPIModelsCreateAreaResponseToJSON,
    JoblogicAPIModelsGetAreaResponseFromJSON,
    JoblogicAPIModelsGetAreaResponseToJSON,
    JoblogicAPIModelsSearchAreaRequestFromJSON,
    JoblogicAPIModelsSearchAreaRequestToJSON,
    JoblogicAPIModelsSearchAreaResponseFromJSON,
    JoblogicAPIModelsSearchAreaResponseToJSON,
    JoblogicAPIModelsUpdateAreaRequestFromJSON,
    JoblogicAPIModelsUpdateAreaRequestToJSON,
    JoblogicAPIModelsUpdateAreaResponseFromJSON,
    JoblogicAPIModelsUpdateAreaResponseToJSON,
} from '../models/index';

export interface ApiV1AreaDeleteRequest {
    authorization: string;
    uniqueId?: string;
    tenantId?: string;
}

export interface ApiV1AreaGetRequest {
    authorization: string;
    uniqueId?: string;
    tenantId?: string;
}

export interface ApiV1AreaGetAllPostRequest {
    authorization: string;
    joblogicAPIModelsSearchAreaRequest?: JoblogicAPIModelsSearchAreaRequest;
}

export interface ApiV1AreaPostRequest {
    authorization: string;
    joblogicAPIModelsCreateAreaRequest?: JoblogicAPIModelsCreateAreaRequest;
}

export interface ApiV1AreaPutRequest {
    authorization: string;
    joblogicAPIModelsUpdateAreaRequest?: JoblogicAPIModelsUpdateAreaRequest;
}

/**
 * 
 */
export class AreaApi extends runtime.BaseAPI {

    /**
     * Delete Area
     */
    async apiV1AreaDeleteRaw(requestParameters: ApiV1AreaDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling apiV1AreaDelete().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['uniqueId'] != null) {
            queryParameters['uniqueId'] = requestParameters['uniqueId'];
        }

        if (requestParameters['tenantId'] != null) {
            queryParameters['tenantId'] = requestParameters['tenantId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/api/v1/Area`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete Area
     */
    async apiV1AreaDelete(requestParameters: ApiV1AreaDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1AreaDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Gets Area Details
     */
    async apiV1AreaGetRaw(requestParameters: ApiV1AreaGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JoblogicAPIModelsGetAreaResponse>> {
        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling apiV1AreaGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['uniqueId'] != null) {
            queryParameters['uniqueId'] = requestParameters['uniqueId'];
        }

        if (requestParameters['tenantId'] != null) {
            queryParameters['tenantId'] = requestParameters['tenantId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/api/v1/Area`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JoblogicAPIModelsGetAreaResponseFromJSON(jsonValue));
    }

    /**
     * Gets Area Details
     */
    async apiV1AreaGet(requestParameters: ApiV1AreaGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JoblogicAPIModelsGetAreaResponse> {
        const response = await this.apiV1AreaGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Search Area by keyword
     */
    async apiV1AreaGetAllPostRaw(requestParameters: ApiV1AreaGetAllPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JoblogicAPIModelsSearchAreaResponse>> {
        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling apiV1AreaGetAllPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/api/v1/Area/GetAll`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: JoblogicAPIModelsSearchAreaRequestToJSON(requestParameters['joblogicAPIModelsSearchAreaRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JoblogicAPIModelsSearchAreaResponseFromJSON(jsonValue));
    }

    /**
     * Search Area by keyword
     */
    async apiV1AreaGetAllPost(requestParameters: ApiV1AreaGetAllPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JoblogicAPIModelsSearchAreaResponse> {
        const response = await this.apiV1AreaGetAllPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create Area
     */
    async apiV1AreaPostRaw(requestParameters: ApiV1AreaPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JoblogicAPIModelsCreateAreaResponse>> {
        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling apiV1AreaPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/api/v1/Area`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: JoblogicAPIModelsCreateAreaRequestToJSON(requestParameters['joblogicAPIModelsCreateAreaRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JoblogicAPIModelsCreateAreaResponseFromJSON(jsonValue));
    }

    /**
     * Create Area
     */
    async apiV1AreaPost(requestParameters: ApiV1AreaPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JoblogicAPIModelsCreateAreaResponse> {
        const response = await this.apiV1AreaPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Area
     */
    async apiV1AreaPutRaw(requestParameters: ApiV1AreaPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JoblogicAPIModelsUpdateAreaResponse>> {
        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling apiV1AreaPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/api/v1/Area`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: JoblogicAPIModelsUpdateAreaRequestToJSON(requestParameters['joblogicAPIModelsUpdateAreaRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JoblogicAPIModelsUpdateAreaResponseFromJSON(jsonValue));
    }

    /**
     * Update Area
     */
    async apiV1AreaPut(requestParameters: ApiV1AreaPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JoblogicAPIModelsUpdateAreaResponse> {
        const response = await this.apiV1AreaPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
