/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  JoblogicAPIModelsCreateCGroupInvoicePaymentRequest,
  JoblogicAPIModelsCreateInvoicePaymentRequest,
  JoblogicAPIModelsCreateSiteTypeResponse,
  JoblogicAPIModelsGetAllCGroupInvoicePayments,
  JoblogicAPIModelsGetAllInvoicePaymentsByInvoiceUniqueId,
  JoblogicAPIModelsGetCGroupInvoicePaymentResponse,
  JoblogicAPIModelsGetInvoicePaymentResponse,
  JoblogicAPIModelsUpdateCGroupInvoicePaymentRequest,
  JoblogicAPIModelsUpdateInvoicePaymentRequest,
  JoblogicAPIModelsUpdateSiteTypeResponse,
} from '../models/index';
import {
    JoblogicAPIModelsCreateCGroupInvoicePaymentRequestFromJSON,
    JoblogicAPIModelsCreateCGroupInvoicePaymentRequestToJSON,
    JoblogicAPIModelsCreateInvoicePaymentRequestFromJSON,
    JoblogicAPIModelsCreateInvoicePaymentRequestToJSON,
    JoblogicAPIModelsCreateSiteTypeResponseFromJSON,
    JoblogicAPIModelsCreateSiteTypeResponseToJSON,
    JoblogicAPIModelsGetAllCGroupInvoicePaymentsFromJSON,
    JoblogicAPIModelsGetAllCGroupInvoicePaymentsToJSON,
    JoblogicAPIModelsGetAllInvoicePaymentsByInvoiceUniqueIdFromJSON,
    JoblogicAPIModelsGetAllInvoicePaymentsByInvoiceUniqueIdToJSON,
    JoblogicAPIModelsGetCGroupInvoicePaymentResponseFromJSON,
    JoblogicAPIModelsGetCGroupInvoicePaymentResponseToJSON,
    JoblogicAPIModelsGetInvoicePaymentResponseFromJSON,
    JoblogicAPIModelsGetInvoicePaymentResponseToJSON,
    JoblogicAPIModelsUpdateCGroupInvoicePaymentRequestFromJSON,
    JoblogicAPIModelsUpdateCGroupInvoicePaymentRequestToJSON,
    JoblogicAPIModelsUpdateInvoicePaymentRequestFromJSON,
    JoblogicAPIModelsUpdateInvoicePaymentRequestToJSON,
    JoblogicAPIModelsUpdateSiteTypeResponseFromJSON,
    JoblogicAPIModelsUpdateSiteTypeResponseToJSON,
} from '../models/index';

export interface ApiV1InvoicePaymentCGroupDeleteRequest {
    authorization: string;
    uniqueId?: string;
    tenantId?: string;
}

export interface ApiV1InvoicePaymentCGroupGetRequest {
    authorization: string;
    uniqueId?: string;
    tenantId?: string;
}

export interface ApiV1InvoicePaymentCGroupGetAllGetRequest {
    authorization: string;
    cGroupInvoiceUniqueId?: string;
    tenantId?: string;
}

export interface ApiV1InvoicePaymentCGroupPostRequest {
    authorization: string;
    joblogicAPIModelsCreateCGroupInvoicePaymentRequest?: JoblogicAPIModelsCreateCGroupInvoicePaymentRequest;
}

export interface ApiV1InvoicePaymentCGroupPutRequest {
    authorization: string;
    joblogicAPIModelsUpdateCGroupInvoicePaymentRequest?: JoblogicAPIModelsUpdateCGroupInvoicePaymentRequest;
}

export interface ApiV1InvoicePaymentDeleteRequest {
    authorization: string;
    uniqueId?: string;
    tenantId?: string;
}

export interface ApiV1InvoicePaymentGetRequest {
    authorization: string;
    uniqueId?: string;
    tenantId?: string;
}

export interface ApiV1InvoicePaymentGetAllGetRequest {
    authorization: string;
    invoiceUniqueId?: string;
    tenantId?: string;
}

export interface ApiV1InvoicePaymentPostRequest {
    authorization: string;
    joblogicAPIModelsCreateInvoicePaymentRequest?: JoblogicAPIModelsCreateInvoicePaymentRequest;
}

export interface ApiV1InvoicePaymentPutRequest {
    authorization: string;
    joblogicAPIModelsUpdateInvoicePaymentRequest?: JoblogicAPIModelsUpdateInvoicePaymentRequest;
}

/**
 * 
 */
export class InvoicePaymentApi extends runtime.BaseAPI {

    /**
     * Delete CGroup Invoice Payment
     */
    async apiV1InvoicePaymentCGroupDeleteRaw(requestParameters: ApiV1InvoicePaymentCGroupDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling apiV1InvoicePaymentCGroupDelete().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['uniqueId'] != null) {
            queryParameters['uniqueId'] = requestParameters['uniqueId'];
        }

        if (requestParameters['tenantId'] != null) {
            queryParameters['tenantId'] = requestParameters['tenantId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/api/v1/InvoicePayment/CGroup`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete CGroup Invoice Payment
     */
    async apiV1InvoicePaymentCGroupDelete(requestParameters: ApiV1InvoicePaymentCGroupDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1InvoicePaymentCGroupDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Gets CGroup payments details
     */
    async apiV1InvoicePaymentCGroupGetRaw(requestParameters: ApiV1InvoicePaymentCGroupGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JoblogicAPIModelsGetCGroupInvoicePaymentResponse>> {
        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling apiV1InvoicePaymentCGroupGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['uniqueId'] != null) {
            queryParameters['uniqueId'] = requestParameters['uniqueId'];
        }

        if (requestParameters['tenantId'] != null) {
            queryParameters['tenantId'] = requestParameters['tenantId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/api/v1/InvoicePayment/CGroup`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JoblogicAPIModelsGetCGroupInvoicePaymentResponseFromJSON(jsonValue));
    }

    /**
     * Gets CGroup payments details
     */
    async apiV1InvoicePaymentCGroupGet(requestParameters: ApiV1InvoicePaymentCGroupGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JoblogicAPIModelsGetCGroupInvoicePaymentResponse> {
        const response = await this.apiV1InvoicePaymentCGroupGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all payments from the CGroup Invoice
     */
    async apiV1InvoicePaymentCGroupGetAllGetRaw(requestParameters: ApiV1InvoicePaymentCGroupGetAllGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JoblogicAPIModelsGetAllCGroupInvoicePayments>> {
        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling apiV1InvoicePaymentCGroupGetAllGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['cGroupInvoiceUniqueId'] != null) {
            queryParameters['cGroupInvoiceUniqueId'] = requestParameters['cGroupInvoiceUniqueId'];
        }

        if (requestParameters['tenantId'] != null) {
            queryParameters['tenantId'] = requestParameters['tenantId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/api/v1/InvoicePayment/CGroup/GetAll`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JoblogicAPIModelsGetAllCGroupInvoicePaymentsFromJSON(jsonValue));
    }

    /**
     * Get all payments from the CGroup Invoice
     */
    async apiV1InvoicePaymentCGroupGetAllGet(requestParameters: ApiV1InvoicePaymentCGroupGetAllGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JoblogicAPIModelsGetAllCGroupInvoicePayments> {
        const response = await this.apiV1InvoicePaymentCGroupGetAllGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create CGroup invoice payment
     */
    async apiV1InvoicePaymentCGroupPostRaw(requestParameters: ApiV1InvoicePaymentCGroupPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JoblogicAPIModelsGetCGroupInvoicePaymentResponse>> {
        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling apiV1InvoicePaymentCGroupPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/api/v1/InvoicePayment/CGroup`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: JoblogicAPIModelsCreateCGroupInvoicePaymentRequestToJSON(requestParameters['joblogicAPIModelsCreateCGroupInvoicePaymentRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JoblogicAPIModelsGetCGroupInvoicePaymentResponseFromJSON(jsonValue));
    }

    /**
     * Create CGroup invoice payment
     */
    async apiV1InvoicePaymentCGroupPost(requestParameters: ApiV1InvoicePaymentCGroupPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JoblogicAPIModelsGetCGroupInvoicePaymentResponse> {
        const response = await this.apiV1InvoicePaymentCGroupPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update CGroup Invoice Payment
     */
    async apiV1InvoicePaymentCGroupPutRaw(requestParameters: ApiV1InvoicePaymentCGroupPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JoblogicAPIModelsGetCGroupInvoicePaymentResponse>> {
        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling apiV1InvoicePaymentCGroupPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/api/v1/InvoicePayment/CGroup`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: JoblogicAPIModelsUpdateCGroupInvoicePaymentRequestToJSON(requestParameters['joblogicAPIModelsUpdateCGroupInvoicePaymentRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JoblogicAPIModelsGetCGroupInvoicePaymentResponseFromJSON(jsonValue));
    }

    /**
     * Update CGroup Invoice Payment
     */
    async apiV1InvoicePaymentCGroupPut(requestParameters: ApiV1InvoicePaymentCGroupPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JoblogicAPIModelsGetCGroupInvoicePaymentResponse> {
        const response = await this.apiV1InvoicePaymentCGroupPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Invoice Payment
     */
    async apiV1InvoicePaymentDeleteRaw(requestParameters: ApiV1InvoicePaymentDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling apiV1InvoicePaymentDelete().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['uniqueId'] != null) {
            queryParameters['uniqueId'] = requestParameters['uniqueId'];
        }

        if (requestParameters['tenantId'] != null) {
            queryParameters['tenantId'] = requestParameters['tenantId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/api/v1/InvoicePayment`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete Invoice Payment
     */
    async apiV1InvoicePaymentDelete(requestParameters: ApiV1InvoicePaymentDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1InvoicePaymentDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Gets payments details
     */
    async apiV1InvoicePaymentGetRaw(requestParameters: ApiV1InvoicePaymentGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JoblogicAPIModelsGetInvoicePaymentResponse>> {
        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling apiV1InvoicePaymentGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['uniqueId'] != null) {
            queryParameters['uniqueId'] = requestParameters['uniqueId'];
        }

        if (requestParameters['tenantId'] != null) {
            queryParameters['tenantId'] = requestParameters['tenantId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/api/v1/InvoicePayment`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JoblogicAPIModelsGetInvoicePaymentResponseFromJSON(jsonValue));
    }

    /**
     * Gets payments details
     */
    async apiV1InvoicePaymentGet(requestParameters: ApiV1InvoicePaymentGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JoblogicAPIModelsGetInvoicePaymentResponse> {
        const response = await this.apiV1InvoicePaymentGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all payments from the invoice
     */
    async apiV1InvoicePaymentGetAllGetRaw(requestParameters: ApiV1InvoicePaymentGetAllGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JoblogicAPIModelsGetAllInvoicePaymentsByInvoiceUniqueId>> {
        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling apiV1InvoicePaymentGetAllGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['invoiceUniqueId'] != null) {
            queryParameters['invoiceUniqueId'] = requestParameters['invoiceUniqueId'];
        }

        if (requestParameters['tenantId'] != null) {
            queryParameters['tenantId'] = requestParameters['tenantId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/api/v1/InvoicePayment/GetAll`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JoblogicAPIModelsGetAllInvoicePaymentsByInvoiceUniqueIdFromJSON(jsonValue));
    }

    /**
     * Get all payments from the invoice
     */
    async apiV1InvoicePaymentGetAllGet(requestParameters: ApiV1InvoicePaymentGetAllGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JoblogicAPIModelsGetAllInvoicePaymentsByInvoiceUniqueId> {
        const response = await this.apiV1InvoicePaymentGetAllGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create invoice payment
     */
    async apiV1InvoicePaymentPostRaw(requestParameters: ApiV1InvoicePaymentPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JoblogicAPIModelsCreateSiteTypeResponse>> {
        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling apiV1InvoicePaymentPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/api/v1/InvoicePayment`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: JoblogicAPIModelsCreateInvoicePaymentRequestToJSON(requestParameters['joblogicAPIModelsCreateInvoicePaymentRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JoblogicAPIModelsCreateSiteTypeResponseFromJSON(jsonValue));
    }

    /**
     * Create invoice payment
     */
    async apiV1InvoicePaymentPost(requestParameters: ApiV1InvoicePaymentPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JoblogicAPIModelsCreateSiteTypeResponse> {
        const response = await this.apiV1InvoicePaymentPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Site Type
     */
    async apiV1InvoicePaymentPutRaw(requestParameters: ApiV1InvoicePaymentPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JoblogicAPIModelsUpdateSiteTypeResponse>> {
        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling apiV1InvoicePaymentPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/api/v1/InvoicePayment`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: JoblogicAPIModelsUpdateInvoicePaymentRequestToJSON(requestParameters['joblogicAPIModelsUpdateInvoicePaymentRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JoblogicAPIModelsUpdateSiteTypeResponseFromJSON(jsonValue));
    }

    /**
     * Update Site Type
     */
    async apiV1InvoicePaymentPut(requestParameters: ApiV1InvoicePaymentPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JoblogicAPIModelsUpdateSiteTypeResponse> {
        const response = await this.apiV1InvoicePaymentPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
