/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  JoblogicAPIModelsCreateTaskRequest,
  JoblogicAPIModelsSearchTaskRequest,
  JoblogicAPIModelsSearchTaskResponse,
  JoblogicAPIModelsTaskItemResponse,
} from '../models/index';
import {
    JoblogicAPIModelsCreateTaskRequestFromJSON,
    JoblogicAPIModelsCreateTaskRequestToJSON,
    JoblogicAPIModelsSearchTaskRequestFromJSON,
    JoblogicAPIModelsSearchTaskRequestToJSON,
    JoblogicAPIModelsSearchTaskResponseFromJSON,
    JoblogicAPIModelsSearchTaskResponseToJSON,
    JoblogicAPIModelsTaskItemResponseFromJSON,
    JoblogicAPIModelsTaskItemResponseToJSON,
} from '../models/index';

export interface ApiV1TaskGetAllPostRequest {
    authorization: string;
    joblogicAPIModelsSearchTaskRequest?: JoblogicAPIModelsSearchTaskRequest;
}

export interface ApiV1TaskGetByIdGetRequest {
    authorization: string;
    id?: string;
    tenantId?: string;
}

export interface ApiV1TaskLibraryPostRequest {
    authorization: string;
    joblogicAPIModelsCreateTaskRequest?: JoblogicAPIModelsCreateTaskRequest;
}

/**
 * 
 */
export class TaskApi extends runtime.BaseAPI {

    /**
     * Search Task by keyword and active status
     */
    async apiV1TaskGetAllPostRaw(requestParameters: ApiV1TaskGetAllPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JoblogicAPIModelsSearchTaskResponse>> {
        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling apiV1TaskGetAllPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/api/v1/Task/GetAll`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: JoblogicAPIModelsSearchTaskRequestToJSON(requestParameters['joblogicAPIModelsSearchTaskRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JoblogicAPIModelsSearchTaskResponseFromJSON(jsonValue));
    }

    /**
     * Search Task by keyword and active status
     */
    async apiV1TaskGetAllPost(requestParameters: ApiV1TaskGetAllPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JoblogicAPIModelsSearchTaskResponse> {
        const response = await this.apiV1TaskGetAllPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get task by Unique Id and tenant id.
     */
    async apiV1TaskGetByIdGetRaw(requestParameters: ApiV1TaskGetByIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JoblogicAPIModelsTaskItemResponse>> {
        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling apiV1TaskGetByIdGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['tenantId'] != null) {
            queryParameters['tenantId'] = requestParameters['tenantId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/api/v1/Task/GetById`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JoblogicAPIModelsTaskItemResponseFromJSON(jsonValue));
    }

    /**
     * Get task by Unique Id and tenant id.
     */
    async apiV1TaskGetByIdGet(requestParameters: ApiV1TaskGetByIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JoblogicAPIModelsTaskItemResponse> {
        const response = await this.apiV1TaskGetByIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Add new task library
     */
    async apiV1TaskLibraryPostRaw(requestParameters: ApiV1TaskLibraryPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JoblogicAPIModelsTaskItemResponse>> {
        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling apiV1TaskLibraryPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/api/v1/Task/Library`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: JoblogicAPIModelsCreateTaskRequestToJSON(requestParameters['joblogicAPIModelsCreateTaskRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JoblogicAPIModelsTaskItemResponseFromJSON(jsonValue));
    }

    /**
     * Add new task library
     */
    async apiV1TaskLibraryPost(requestParameters: ApiV1TaskLibraryPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JoblogicAPIModelsTaskItemResponse> {
        const response = await this.apiV1TaskLibraryPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
