/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  JoblogicAPIModelsCreateTradeRequest,
  JoblogicAPIModelsCreateTradeResponse,
  JoblogicAPIModelsDeleteTradeRequest,
  JoblogicAPIModelsDeleteTradeResponse,
  JoblogicAPIModelsGetTradeResponse,
  JoblogicAPIModelsSearchTradeRequest,
  JoblogicAPIModelsSearchTradeResponse,
  JoblogicAPIModelsUpdateTradeRequest,
  JoblogicAPIModelsUpdateTradeResponse,
} from '../models/index';
import {
    JoblogicAPIModelsCreateTradeRequestFromJSON,
    JoblogicAPIModelsCreateTradeRequestToJSON,
    JoblogicAPIModelsCreateTradeResponseFromJSON,
    JoblogicAPIModelsCreateTradeResponseToJSON,
    JoblogicAPIModelsDeleteTradeRequestFromJSON,
    JoblogicAPIModelsDeleteTradeRequestToJSON,
    JoblogicAPIModelsDeleteTradeResponseFromJSON,
    JoblogicAPIModelsDeleteTradeResponseToJSON,
    JoblogicAPIModelsGetTradeResponseFromJSON,
    JoblogicAPIModelsGetTradeResponseToJSON,
    JoblogicAPIModelsSearchTradeRequestFromJSON,
    JoblogicAPIModelsSearchTradeRequestToJSON,
    JoblogicAPIModelsSearchTradeResponseFromJSON,
    JoblogicAPIModelsSearchTradeResponseToJSON,
    JoblogicAPIModelsUpdateTradeRequestFromJSON,
    JoblogicAPIModelsUpdateTradeRequestToJSON,
    JoblogicAPIModelsUpdateTradeResponseFromJSON,
    JoblogicAPIModelsUpdateTradeResponseToJSON,
} from '../models/index';

export interface ApiV1TradeDeleteRequest {
    authorization: string;
    joblogicAPIModelsDeleteTradeRequest?: JoblogicAPIModelsDeleteTradeRequest;
}

export interface ApiV1TradeGetRequest {
    authorization: string;
    tenantId?: string;
    id?: string;
}

export interface ApiV1TradeGetAllPostRequest {
    authorization: string;
    joblogicAPIModelsSearchTradeRequest?: JoblogicAPIModelsSearchTradeRequest;
}

export interface ApiV1TradePostRequest {
    authorization: string;
    joblogicAPIModelsCreateTradeRequest?: JoblogicAPIModelsCreateTradeRequest;
}

export interface ApiV1TradePutRequest {
    authorization: string;
    joblogicAPIModelsUpdateTradeRequest?: JoblogicAPIModelsUpdateTradeRequest;
}

/**
 * 
 */
export class TradeApi extends runtime.BaseAPI {

    /**
     * Delete an existing Trade using core service
     */
    async apiV1TradeDeleteRaw(requestParameters: ApiV1TradeDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JoblogicAPIModelsDeleteTradeResponse>> {
        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling apiV1TradeDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/api/v1/Trade`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: JoblogicAPIModelsDeleteTradeRequestToJSON(requestParameters['joblogicAPIModelsDeleteTradeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JoblogicAPIModelsDeleteTradeResponseFromJSON(jsonValue));
    }

    /**
     * Delete an existing Trade using core service
     */
    async apiV1TradeDelete(requestParameters: ApiV1TradeDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JoblogicAPIModelsDeleteTradeResponse> {
        const response = await this.apiV1TradeDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Trade by Id
     */
    async apiV1TradeGetRaw(requestParameters: ApiV1TradeGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JoblogicAPIModelsGetTradeResponse>> {
        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling apiV1TradeGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['tenantId'] != null) {
            queryParameters['tenantId'] = requestParameters['tenantId'];
        }

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/api/v1/Trade`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JoblogicAPIModelsGetTradeResponseFromJSON(jsonValue));
    }

    /**
     * Get Trade by Id
     */
    async apiV1TradeGet(requestParameters: ApiV1TradeGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JoblogicAPIModelsGetTradeResponse> {
        const response = await this.apiV1TradeGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Search Trade by keyword
     */
    async apiV1TradeGetAllPostRaw(requestParameters: ApiV1TradeGetAllPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JoblogicAPIModelsSearchTradeResponse>> {
        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling apiV1TradeGetAllPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/api/v1/Trade/GetAll`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: JoblogicAPIModelsSearchTradeRequestToJSON(requestParameters['joblogicAPIModelsSearchTradeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JoblogicAPIModelsSearchTradeResponseFromJSON(jsonValue));
    }

    /**
     * Search Trade by keyword
     */
    async apiV1TradeGetAllPost(requestParameters: ApiV1TradeGetAllPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JoblogicAPIModelsSearchTradeResponse> {
        const response = await this.apiV1TradeGetAllPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new Trade using core service
     */
    async apiV1TradePostRaw(requestParameters: ApiV1TradePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JoblogicAPIModelsCreateTradeResponse>> {
        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling apiV1TradePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/api/v1/Trade`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: JoblogicAPIModelsCreateTradeRequestToJSON(requestParameters['joblogicAPIModelsCreateTradeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JoblogicAPIModelsCreateTradeResponseFromJSON(jsonValue));
    }

    /**
     * Create a new Trade using core service
     */
    async apiV1TradePost(requestParameters: ApiV1TradePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JoblogicAPIModelsCreateTradeResponse> {
        const response = await this.apiV1TradePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update an existing Trade using core service
     */
    async apiV1TradePutRaw(requestParameters: ApiV1TradePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JoblogicAPIModelsUpdateTradeResponse>> {
        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling apiV1TradePut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/api/v1/Trade`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: JoblogicAPIModelsUpdateTradeRequestToJSON(requestParameters['joblogicAPIModelsUpdateTradeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JoblogicAPIModelsUpdateTradeResponseFromJSON(jsonValue));
    }

    /**
     * Update an existing Trade using core service
     */
    async apiV1TradePut(requestParameters: ApiV1TradePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JoblogicAPIModelsUpdateTradeResponse> {
        const response = await this.apiV1TradePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
