/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  JoblogicAPIModelsTVSJobMessageContext,
} from '../models/index';
import {
    JoblogicAPIModelsTVSJobMessageContextFromJSON,
    JoblogicAPIModelsTVSJobMessageContextToJSON,
} from '../models/index';

export interface ApiV1TvsJobPartPostRequest {
    authorization: string;
    joblogicAPIModelsTVSJobMessageContext?: JoblogicAPIModelsTVSJobMessageContext;
}

/**
 * 
 */
export class TVSApi extends runtime.BaseAPI {

    /**
     */
    async apiV1TvsJobPartPostRaw(requestParameters: ApiV1TvsJobPartPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling apiV1TvsJobPartPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/api/v1/tvs/job/part`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: JoblogicAPIModelsTVSJobMessageContextToJSON(requestParameters['joblogicAPIModelsTVSJobMessageContext']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiV1TvsJobPartPost(requestParameters: ApiV1TvsJobPartPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1TvsJobPartPostRaw(requestParameters, initOverrides);
    }

}
