/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JoblogicAPIModelsGetContactRequest } from './JoblogicAPIModelsGetContactRequest';
import {
    JoblogicAPIModelsGetContactRequestFromJSON,
    JoblogicAPIModelsGetContactRequestFromJSONTyped,
    JoblogicAPIModelsGetContactRequestToJSON,
    JoblogicAPIModelsGetContactRequestToJSONTyped,
} from './JoblogicAPIModelsGetContactRequest';
import type { JoblogicAPIModelsSiteAdditionalDetails } from './JoblogicAPIModelsSiteAdditionalDetails';
import {
    JoblogicAPIModelsSiteAdditionalDetailsFromJSON,
    JoblogicAPIModelsSiteAdditionalDetailsFromJSONTyped,
    JoblogicAPIModelsSiteAdditionalDetailsToJSON,
    JoblogicAPIModelsSiteAdditionalDetailsToJSONTyped,
} from './JoblogicAPIModelsSiteAdditionalDetails';

/**
 * 
 * @export
 * @interface JoblogicAPIModelsGetSiteResponse
 */
export interface JoblogicAPIModelsGetSiteResponse {
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsGetSiteResponse
     */
    intId?: number;
    /**
     * Id of the Site in Joblogic
     * @type {string}
     * @memberof JoblogicAPIModelsGetSiteResponse
     */
    id?: string;
    /**
     * Id of the Site in an external system
     * @type {string}
     * @memberof JoblogicAPIModelsGetSiteResponse
     */
    externalId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsGetSiteResponse
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsGetSiteResponse
     */
    address1?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsGetSiteResponse
     */
    address2?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsGetSiteResponse
     */
    address3?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsGetSiteResponse
     */
    address4?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsGetSiteResponse
     */
    postcode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsGetSiteResponse
     */
    telephone?: string | null;
    /**
     * Will create a new Region if the requested one does not exist, not case sensitive
     * @type {string}
     * @memberof JoblogicAPIModelsGetSiteResponse
     */
    region?: string | null;
    /**
     * A custom reference number which can help to identify the Site
     * @type {string}
     * @memberof JoblogicAPIModelsGetSiteResponse
     */
    referenceNumber?: string | null;
    /**
     * The Account number associated to the Site
     * @type {string}
     * @memberof JoblogicAPIModelsGetSiteResponse
     */
    accountNumber?: string | null;
    /**
     * A list of contacts that will be associated to the Site
     * @type {Array<JoblogicAPIModelsGetContactRequest>}
     * @memberof JoblogicAPIModelsGetSiteResponse
     */
    contacts?: Array<JoblogicAPIModelsGetContactRequest> | null;
    /**
     * A list of tags, associated to the Site that can be used for searching/filtering
     * @type {Array<string>}
     * @memberof JoblogicAPIModelsGetSiteResponse
     */
    tags?: Array<string> | null;
    /**
     * 
     * @type {JoblogicAPIModelsSiteAdditionalDetails}
     * @memberof JoblogicAPIModelsGetSiteResponse
     */
    additionalDetails?: JoblogicAPIModelsSiteAdditionalDetails;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsGetSiteResponse
     */
    readonly customerUniqueId?: string | null;
}

/**
 * Check if a given object implements the JoblogicAPIModelsGetSiteResponse interface.
 */
export function instanceOfJoblogicAPIModelsGetSiteResponse(value: object): value is JoblogicAPIModelsGetSiteResponse {
    return true;
}

export function JoblogicAPIModelsGetSiteResponseFromJSON(json: any): JoblogicAPIModelsGetSiteResponse {
    return JoblogicAPIModelsGetSiteResponseFromJSONTyped(json, false);
}

export function JoblogicAPIModelsGetSiteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsGetSiteResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'intId': json['IntId'] == null ? undefined : json['IntId'],
        'id': json['Id'] == null ? undefined : json['Id'],
        'externalId': json['ExternalId'] == null ? undefined : json['ExternalId'],
        'name': json['Name'] == null ? undefined : json['Name'],
        'address1': json['Address1'] == null ? undefined : json['Address1'],
        'address2': json['Address2'] == null ? undefined : json['Address2'],
        'address3': json['Address3'] == null ? undefined : json['Address3'],
        'address4': json['Address4'] == null ? undefined : json['Address4'],
        'postcode': json['Postcode'] == null ? undefined : json['Postcode'],
        'telephone': json['Telephone'] == null ? undefined : json['Telephone'],
        'region': json['Region'] == null ? undefined : json['Region'],
        'referenceNumber': json['ReferenceNumber'] == null ? undefined : json['ReferenceNumber'],
        'accountNumber': json['AccountNumber'] == null ? undefined : json['AccountNumber'],
        'contacts': json['Contacts'] == null ? undefined : ((json['Contacts'] as Array<any>).map(JoblogicAPIModelsGetContactRequestFromJSON)),
        'tags': json['Tags'] == null ? undefined : json['Tags'],
        'additionalDetails': json['AdditionalDetails'] == null ? undefined : JoblogicAPIModelsSiteAdditionalDetailsFromJSON(json['AdditionalDetails']),
        'customerUniqueId': json['CustomerUniqueId'] == null ? undefined : json['CustomerUniqueId'],
    };
}

export function JoblogicAPIModelsGetSiteResponseToJSON(json: any): JoblogicAPIModelsGetSiteResponse {
    return JoblogicAPIModelsGetSiteResponseToJSONTyped(json, false);
}

export function JoblogicAPIModelsGetSiteResponseToJSONTyped(value?: Omit<JoblogicAPIModelsGetSiteResponse, 'CustomerUniqueId'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'IntId': value['intId'],
        'Id': value['id'],
        'ExternalId': value['externalId'],
        'Name': value['name'],
        'Address1': value['address1'],
        'Address2': value['address2'],
        'Address3': value['address3'],
        'Address4': value['address4'],
        'Postcode': value['postcode'],
        'Telephone': value['telephone'],
        'Region': value['region'],
        'ReferenceNumber': value['referenceNumber'],
        'AccountNumber': value['accountNumber'],
        'Contacts': value['contacts'] == null ? undefined : ((value['contacts'] as Array<any>).map(JoblogicAPIModelsGetContactRequestToJSON)),
        'Tags': value['tags'],
        'AdditionalDetails': JoblogicAPIModelsSiteAdditionalDetailsToJSON(value['additionalDetails']),
    };
}

