/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JoblogicAPIModelsSearchTradeItemResponse } from './JoblogicAPIModelsSearchTradeItemResponse';
import {
    JoblogicAPIModelsSearchTradeItemResponseFromJSON,
    JoblogicAPIModelsSearchTradeItemResponseFromJSONTyped,
    JoblogicAPIModelsSearchTradeItemResponseToJSON,
    JoblogicAPIModelsSearchTradeItemResponseToJSONTyped,
} from './JoblogicAPIModelsSearchTradeItemResponse';

/**
 * 
 * @export
 * @interface JoblogicAPIModelsSearchTradeResponse
 */
export interface JoblogicAPIModelsSearchTradeResponse {
    /**
     * 
     * @type {Array<JoblogicAPIModelsSearchTradeItemResponse>}
     * @memberof JoblogicAPIModelsSearchTradeResponse
     */
    items?: Array<JoblogicAPIModelsSearchTradeItemResponse> | null;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsSearchTradeResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsSearchTradeResponse
     */
    pageIndex?: number;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsSearchTradeResponse
     */
    pageSize?: number;
}

/**
 * Check if a given object implements the JoblogicAPIModelsSearchTradeResponse interface.
 */
export function instanceOfJoblogicAPIModelsSearchTradeResponse(value: object): value is JoblogicAPIModelsSearchTradeResponse {
    return true;
}

export function JoblogicAPIModelsSearchTradeResponseFromJSON(json: any): JoblogicAPIModelsSearchTradeResponse {
    return JoblogicAPIModelsSearchTradeResponseFromJSONTyped(json, false);
}

export function JoblogicAPIModelsSearchTradeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsSearchTradeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['Items'] == null ? undefined : ((json['Items'] as Array<any>).map(JoblogicAPIModelsSearchTradeItemResponseFromJSON)),
        'totalCount': json['TotalCount'] == null ? undefined : json['TotalCount'],
        'pageIndex': json['PageIndex'] == null ? undefined : json['PageIndex'],
        'pageSize': json['PageSize'] == null ? undefined : json['PageSize'],
    };
}

export function JoblogicAPIModelsSearchTradeResponseToJSON(json: any): JoblogicAPIModelsSearchTradeResponse {
    return JoblogicAPIModelsSearchTradeResponseToJSONTyped(json, false);
}

export function JoblogicAPIModelsSearchTradeResponseToJSONTyped(value?: JoblogicAPIModelsSearchTradeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(JoblogicAPIModelsSearchTradeItemResponseToJSON)),
        'TotalCount': value['totalCount'],
        'PageIndex': value['pageIndex'],
        'PageSize': value['pageSize'],
    };
}

