/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JoblogicAPIModelsCreditLineRequestModel
 */
export interface JoblogicAPIModelsCreditLineRequestModel {
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCreditLineRequestModel
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsCreditLineRequestModel
     */
    pricePerUnit?: number;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsCreditLineRequestModel
     */
    quantity?: number;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCreditLineRequestModel
     */
    taxCodeId?: string;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCreditLineRequestModel
     */
    nominalCodeId?: string | null;
}

/**
 * Check if a given object implements the JoblogicAPIModelsCreditLineRequestModel interface.
 */
export function instanceOfJoblogicAPIModelsCreditLineRequestModel(value: object): value is JoblogicAPIModelsCreditLineRequestModel {
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function JoblogicAPIModelsCreditLineRequestModelFromJSON(json: any): JoblogicAPIModelsCreditLineRequestModel {
    return JoblogicAPIModelsCreditLineRequestModelFromJSONTyped(json, false);
}

export function JoblogicAPIModelsCreditLineRequestModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsCreditLineRequestModel {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['Description'],
        'pricePerUnit': json['PricePerUnit'] == null ? undefined : json['PricePerUnit'],
        'quantity': json['Quantity'] == null ? undefined : json['Quantity'],
        'taxCodeId': json['TaxCodeId'] == null ? undefined : json['TaxCodeId'],
        'nominalCodeId': json['NominalCodeId'] == null ? undefined : json['NominalCodeId'],
    };
}

export function JoblogicAPIModelsCreditLineRequestModelToJSON(json: any): JoblogicAPIModelsCreditLineRequestModel {
    return JoblogicAPIModelsCreditLineRequestModelToJSONTyped(json, false);
}

export function JoblogicAPIModelsCreditLineRequestModelToJSONTyped(value?: JoblogicAPIModelsCreditLineRequestModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Description': value['description'],
        'PricePerUnit': value['pricePerUnit'],
        'Quantity': value['quantity'],
        'TaxCodeId': value['taxCodeId'],
        'NominalCodeId': value['nominalCodeId'],
    };
}

