/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobLogicMicroserviceCoreContractContractPurchaseOrderInvoiceType } from './JobLogicMicroserviceCoreContractContractPurchaseOrderInvoiceType';
import {
    JobLogicMicroserviceCoreContractContractPurchaseOrderInvoiceTypeFromJSON,
    JobLogicMicroserviceCoreContractContractPurchaseOrderInvoiceTypeFromJSONTyped,
    JobLogicMicroserviceCoreContractContractPurchaseOrderInvoiceTypeToJSON,
    JobLogicMicroserviceCoreContractContractPurchaseOrderInvoiceTypeToJSONTyped,
} from './JobLogicMicroserviceCoreContractContractPurchaseOrderInvoiceType';

/**
 * 
 * @export
 * @interface JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceLineModel
 */
export interface JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceLineModel {
    /**
     * 
     * @type {string}
     * @memberof JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceLineModel
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceLineModel
     */
    purchaseOrderId?: string;
    /**
     * 
     * @type {string}
     * @memberof JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceLineModel
     */
    invoiceId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceLineModel
     */
    isFinalInvoice?: boolean;
    /**
     * 
     * @type {string}
     * @memberof JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceLineModel
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceLineModel
     */
    quantity?: number;
    /**
     * 
     * @type {number}
     * @memberof JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceLineModel
     */
    pricePerUnit?: number;
    /**
     * 
     * @type {JobLogicMicroserviceCoreContractContractPurchaseOrderInvoiceType}
     * @memberof JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceLineModel
     */
    type?: JobLogicMicroserviceCoreContractContractPurchaseOrderInvoiceType;
    /**
     * 
     * @type {string}
     * @memberof JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceLineModel
     */
    taxCodeId?: string;
    /**
     * 
     * @type {number}
     * @memberof JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceLineModel
     */
    vatRate?: number;
    /**
     * 
     * @type {string}
     * @memberof JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceLineModel
     */
    taxCodeDescription?: string | null;
    /**
     * 
     * @type {number}
     * @memberof JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceLineModel
     */
    overriddenTaxAmount?: number | null;
    /**
     * 
     * @type {string}
     * @memberof JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceLineModel
     */
    nominalCodeId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceLineModel
     */
    nominalCodeValue?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceLineModel
     */
    nominalCodeDescription?: string | null;
    /**
     * 
     * @type {number}
     * @memberof JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceLineModel
     */
    totalExcludingVatAndDiscount?: number;
    /**
     * 
     * @type {number}
     * @memberof JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceLineModel
     */
    totalExcludingVat?: number;
    /**
     * 
     * @type {number}
     * @memberof JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceLineModel
     */
    totalIncludingVat?: number;
    /**
     * 
     * @type {number}
     * @memberof JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceLineModel
     */
    totalVatAmount?: number;
}



/**
 * Check if a given object implements the JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceLineModel interface.
 */
export function instanceOfJobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceLineModel(value: object): value is JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceLineModel {
    return true;
}

export function JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceLineModelFromJSON(json: any): JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceLineModel {
    return JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceLineModelFromJSONTyped(json, false);
}

export function JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceLineModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceLineModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['Id'] == null ? undefined : json['Id'],
        'purchaseOrderId': json['PurchaseOrderId'] == null ? undefined : json['PurchaseOrderId'],
        'invoiceId': json['InvoiceId'] == null ? undefined : json['InvoiceId'],
        'isFinalInvoice': json['IsFinalInvoice'] == null ? undefined : json['IsFinalInvoice'],
        'description': json['Description'] == null ? undefined : json['Description'],
        'quantity': json['Quantity'] == null ? undefined : json['Quantity'],
        'pricePerUnit': json['PricePerUnit'] == null ? undefined : json['PricePerUnit'],
        'type': json['Type'] == null ? undefined : JobLogicMicroserviceCoreContractContractPurchaseOrderInvoiceTypeFromJSON(json['Type']),
        'taxCodeId': json['TaxCodeId'] == null ? undefined : json['TaxCodeId'],
        'vatRate': json['VatRate'] == null ? undefined : json['VatRate'],
        'taxCodeDescription': json['TaxCodeDescription'] == null ? undefined : json['TaxCodeDescription'],
        'overriddenTaxAmount': json['OverriddenTaxAmount'] == null ? undefined : json['OverriddenTaxAmount'],
        'nominalCodeId': json['NominalCodeId'] == null ? undefined : json['NominalCodeId'],
        'nominalCodeValue': json['NominalCodeValue'] == null ? undefined : json['NominalCodeValue'],
        'nominalCodeDescription': json['NominalCodeDescription'] == null ? undefined : json['NominalCodeDescription'],
        'totalExcludingVatAndDiscount': json['TotalExcludingVatAndDiscount'] == null ? undefined : json['TotalExcludingVatAndDiscount'],
        'totalExcludingVat': json['TotalExcludingVat'] == null ? undefined : json['TotalExcludingVat'],
        'totalIncludingVat': json['TotalIncludingVat'] == null ? undefined : json['TotalIncludingVat'],
        'totalVatAmount': json['TotalVatAmount'] == null ? undefined : json['TotalVatAmount'],
    };
}

export function JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceLineModelToJSON(json: any): JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceLineModel {
    return JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceLineModelToJSONTyped(json, false);
}

export function JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceLineModelToJSONTyped(value?: JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceLineModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Id': value['id'],
        'PurchaseOrderId': value['purchaseOrderId'],
        'InvoiceId': value['invoiceId'],
        'IsFinalInvoice': value['isFinalInvoice'],
        'Description': value['description'],
        'Quantity': value['quantity'],
        'PricePerUnit': value['pricePerUnit'],
        'Type': JobLogicMicroserviceCoreContractContractPurchaseOrderInvoiceTypeToJSON(value['type']),
        'TaxCodeId': value['taxCodeId'],
        'VatRate': value['vatRate'],
        'TaxCodeDescription': value['taxCodeDescription'],
        'OverriddenTaxAmount': value['overriddenTaxAmount'],
        'NominalCodeId': value['nominalCodeId'],
        'NominalCodeValue': value['nominalCodeValue'],
        'NominalCodeDescription': value['nominalCodeDescription'],
        'TotalExcludingVatAndDiscount': value['totalExcludingVatAndDiscount'],
        'TotalExcludingVat': value['totalExcludingVat'],
        'TotalIncludingVat': value['totalIncludingVat'],
        'TotalVatAmount': value['totalVatAmount'],
    };
}

