/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JoblogicAPIModelsResponseSearchJobAssetItemResponse } from './JoblogicAPIModelsResponseSearchJobAssetItemResponse';
import {
    JoblogicAPIModelsResponseSearchJobAssetItemResponseFromJSON,
    JoblogicAPIModelsResponseSearchJobAssetItemResponseFromJSONTyped,
    JoblogicAPIModelsResponseSearchJobAssetItemResponseToJSON,
    JoblogicAPIModelsResponseSearchJobAssetItemResponseToJSONTyped,
} from './JoblogicAPIModelsResponseSearchJobAssetItemResponse';

/**
 * 
 * @export
 * @interface JoblogicAPIModelsResponseJobAssetResponse
 */
export interface JoblogicAPIModelsResponseJobAssetResponse {
    /**
     * 
     * @type {Array<JoblogicAPIModelsResponseSearchJobAssetItemResponse>}
     * @memberof JoblogicAPIModelsResponseJobAssetResponse
     */
    items?: Array<JoblogicAPIModelsResponseSearchJobAssetItemResponse> | null;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsResponseJobAssetResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsResponseJobAssetResponse
     */
    pageIndex?: number;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsResponseJobAssetResponse
     */
    pageSize?: number;
}

/**
 * Check if a given object implements the JoblogicAPIModelsResponseJobAssetResponse interface.
 */
export function instanceOfJoblogicAPIModelsResponseJobAssetResponse(value: object): value is JoblogicAPIModelsResponseJobAssetResponse {
    return true;
}

export function JoblogicAPIModelsResponseJobAssetResponseFromJSON(json: any): JoblogicAPIModelsResponseJobAssetResponse {
    return JoblogicAPIModelsResponseJobAssetResponseFromJSONTyped(json, false);
}

export function JoblogicAPIModelsResponseJobAssetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsResponseJobAssetResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['Items'] == null ? undefined : ((json['Items'] as Array<any>).map(JoblogicAPIModelsResponseSearchJobAssetItemResponseFromJSON)),
        'totalCount': json['TotalCount'] == null ? undefined : json['TotalCount'],
        'pageIndex': json['PageIndex'] == null ? undefined : json['PageIndex'],
        'pageSize': json['PageSize'] == null ? undefined : json['PageSize'],
    };
}

export function JoblogicAPIModelsResponseJobAssetResponseToJSON(json: any): JoblogicAPIModelsResponseJobAssetResponse {
    return JoblogicAPIModelsResponseJobAssetResponseToJSONTyped(json, false);
}

export function JoblogicAPIModelsResponseJobAssetResponseToJSONTyped(value?: JoblogicAPIModelsResponseJobAssetResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(JoblogicAPIModelsResponseSearchJobAssetItemResponseToJSON)),
        'TotalCount': value['totalCount'],
        'PageIndex': value['pageIndex'],
        'PageSize': value['pageSize'],
    };
}

