/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JoblogicAPIModelsNGBNGBWorkingHour
 */
export interface JoblogicAPIModelsNGBNGBWorkingHour {
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsNGBNGBWorkingHour
     */
    day?: number;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsNGBNGBWorkingHour
     */
    startHour?: number;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsNGBNGBWorkingHour
     */
    startMinute?: number;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsNGBNGBWorkingHour
     */
    endHour?: number;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsNGBNGBWorkingHour
     */
    endMinute?: number;
    /**
     * 
     * @type {boolean}
     * @memberof JoblogicAPIModelsNGBNGBWorkingHour
     */
    closeAllDay?: boolean;
}

/**
 * Check if a given object implements the JoblogicAPIModelsNGBNGBWorkingHour interface.
 */
export function instanceOfJoblogicAPIModelsNGBNGBWorkingHour(value: object): value is JoblogicAPIModelsNGBNGBWorkingHour {
    return true;
}

export function JoblogicAPIModelsNGBNGBWorkingHourFromJSON(json: any): JoblogicAPIModelsNGBNGBWorkingHour {
    return JoblogicAPIModelsNGBNGBWorkingHourFromJSONTyped(json, false);
}

export function JoblogicAPIModelsNGBNGBWorkingHourFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsNGBNGBWorkingHour {
    if (json == null) {
        return json;
    }
    return {
        
        'day': json['Day'] == null ? undefined : json['Day'],
        'startHour': json['StartHour'] == null ? undefined : json['StartHour'],
        'startMinute': json['StartMinute'] == null ? undefined : json['StartMinute'],
        'endHour': json['EndHour'] == null ? undefined : json['EndHour'],
        'endMinute': json['EndMinute'] == null ? undefined : json['EndMinute'],
        'closeAllDay': json['CloseAllDay'] == null ? undefined : json['CloseAllDay'],
    };
}

export function JoblogicAPIModelsNGBNGBWorkingHourToJSON(json: any): JoblogicAPIModelsNGBNGBWorkingHour {
    return JoblogicAPIModelsNGBNGBWorkingHourToJSONTyped(json, false);
}

export function JoblogicAPIModelsNGBNGBWorkingHourToJSONTyped(value?: JoblogicAPIModelsNGBNGBWorkingHour | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Day': value['day'],
        'StartHour': value['startHour'],
        'StartMinute': value['startMinute'],
        'EndHour': value['endHour'],
        'EndMinute': value['endMinute'],
        'CloseAllDay': value['closeAllDay'],
    };
}

