/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JoblogicAPIModelsApprovePurchaseOrderRequest
 */
export interface JoblogicAPIModelsApprovePurchaseOrderRequest {
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsApprovePurchaseOrderRequest
     */
    purchaseOrderId: string;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsApprovePurchaseOrderRequest
     */
    approveBy: number;
    /**
     * Contractor Id in Joblogic
     * @type {string}
     * @memberof JoblogicAPIModelsApprovePurchaseOrderRequest
     */
    tenantId: string;
}

/**
 * Check if a given object implements the JoblogicAPIModelsApprovePurchaseOrderRequest interface.
 */
export function instanceOfJoblogicAPIModelsApprovePurchaseOrderRequest(value: object): value is JoblogicAPIModelsApprovePurchaseOrderRequest {
    if (!('purchaseOrderId' in value) || value['purchaseOrderId'] === undefined) return false;
    if (!('approveBy' in value) || value['approveBy'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    return true;
}

export function JoblogicAPIModelsApprovePurchaseOrderRequestFromJSON(json: any): JoblogicAPIModelsApprovePurchaseOrderRequest {
    return JoblogicAPIModelsApprovePurchaseOrderRequestFromJSONTyped(json, false);
}

export function JoblogicAPIModelsApprovePurchaseOrderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsApprovePurchaseOrderRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'purchaseOrderId': json['PurchaseOrderId'],
        'approveBy': json['ApproveBy'],
        'tenantId': json['TenantId'],
    };
}

export function JoblogicAPIModelsApprovePurchaseOrderRequestToJSON(json: any): JoblogicAPIModelsApprovePurchaseOrderRequest {
    return JoblogicAPIModelsApprovePurchaseOrderRequestToJSONTyped(json, false);
}

export function JoblogicAPIModelsApprovePurchaseOrderRequestToJSONTyped(value?: JoblogicAPIModelsApprovePurchaseOrderRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'PurchaseOrderId': value['purchaseOrderId'],
        'ApproveBy': value['approveBy'],
        'TenantId': value['tenantId'],
    };
}

