/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JoblogicAPIModelsSupplierContactRequest } from './JoblogicAPIModelsSupplierContactRequest';
import {
    JoblogicAPIModelsSupplierContactRequestFromJSON,
    JoblogicAPIModelsSupplierContactRequestFromJSONTyped,
    JoblogicAPIModelsSupplierContactRequestToJSON,
    JoblogicAPIModelsSupplierContactRequestToJSONTyped,
} from './JoblogicAPIModelsSupplierContactRequest';

/**
 * 
 * @export
 * @interface JoblogicAPIModelsSupplierAdditionalDetailsRequest
 */
export interface JoblogicAPIModelsSupplierAdditionalDetailsRequest {
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsSupplierAdditionalDetailsRequest
     */
    partLibraryId?: number | null;
    /**
     * 
     * @type {JoblogicAPIModelsSupplierContactRequest}
     * @memberof JoblogicAPIModelsSupplierAdditionalDetailsRequest
     */
    primaryContact?: JoblogicAPIModelsSupplierContactRequest;
}

/**
 * Check if a given object implements the JoblogicAPIModelsSupplierAdditionalDetailsRequest interface.
 */
export function instanceOfJoblogicAPIModelsSupplierAdditionalDetailsRequest(value: object): value is JoblogicAPIModelsSupplierAdditionalDetailsRequest {
    return true;
}

export function JoblogicAPIModelsSupplierAdditionalDetailsRequestFromJSON(json: any): JoblogicAPIModelsSupplierAdditionalDetailsRequest {
    return JoblogicAPIModelsSupplierAdditionalDetailsRequestFromJSONTyped(json, false);
}

export function JoblogicAPIModelsSupplierAdditionalDetailsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsSupplierAdditionalDetailsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'partLibraryId': json['PartLibraryId'] == null ? undefined : json['PartLibraryId'],
        'primaryContact': json['PrimaryContact'] == null ? undefined : JoblogicAPIModelsSupplierContactRequestFromJSON(json['PrimaryContact']),
    };
}

export function JoblogicAPIModelsSupplierAdditionalDetailsRequestToJSON(json: any): JoblogicAPIModelsSupplierAdditionalDetailsRequest {
    return JoblogicAPIModelsSupplierAdditionalDetailsRequestToJSONTyped(json, false);
}

export function JoblogicAPIModelsSupplierAdditionalDetailsRequestToJSONTyped(value?: JoblogicAPIModelsSupplierAdditionalDetailsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'PartLibraryId': value['partLibraryId'],
        'PrimaryContact': JoblogicAPIModelsSupplierContactRequestToJSON(value['primaryContact']),
    };
}

