/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JoblogicAPIModelsProfitabilityQuoteResponse } from './JoblogicAPIModelsProfitabilityQuoteResponse';
import {
    JoblogicAPIModelsProfitabilityQuoteResponseFromJSON,
    JoblogicAPIModelsProfitabilityQuoteResponseFromJSONTyped,
    JoblogicAPIModelsProfitabilityQuoteResponseToJSON,
    JoblogicAPIModelsProfitabilityQuoteResponseToJSONTyped,
} from './JoblogicAPIModelsProfitabilityQuoteResponse';
import type { JoblogicAPIModelsQuoteGroupCostLinesResponse } from './JoblogicAPIModelsQuoteGroupCostLinesResponse';
import {
    JoblogicAPIModelsQuoteGroupCostLinesResponseFromJSON,
    JoblogicAPIModelsQuoteGroupCostLinesResponseFromJSONTyped,
    JoblogicAPIModelsQuoteGroupCostLinesResponseToJSON,
    JoblogicAPIModelsQuoteGroupCostLinesResponseToJSONTyped,
} from './JoblogicAPIModelsQuoteGroupCostLinesResponse';

/**
 * 
 * @export
 * @interface JoblogicAPIModelsGetQuoteLinesResponse
 */
export interface JoblogicAPIModelsGetQuoteLinesResponse {
    /**
     * 
     * @type {JoblogicAPIModelsQuoteGroupCostLinesResponse}
     * @memberof JoblogicAPIModelsGetQuoteLinesResponse
     */
    groupLinesResponse?: JoblogicAPIModelsQuoteGroupCostLinesResponse;
    /**
     * 
     * @type {JoblogicAPIModelsProfitabilityQuoteResponse}
     * @memberof JoblogicAPIModelsGetQuoteLinesResponse
     */
    profitabilityQuote?: JoblogicAPIModelsProfitabilityQuoteResponse;
}

/**
 * Check if a given object implements the JoblogicAPIModelsGetQuoteLinesResponse interface.
 */
export function instanceOfJoblogicAPIModelsGetQuoteLinesResponse(value: object): value is JoblogicAPIModelsGetQuoteLinesResponse {
    return true;
}

export function JoblogicAPIModelsGetQuoteLinesResponseFromJSON(json: any): JoblogicAPIModelsGetQuoteLinesResponse {
    return JoblogicAPIModelsGetQuoteLinesResponseFromJSONTyped(json, false);
}

export function JoblogicAPIModelsGetQuoteLinesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsGetQuoteLinesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'groupLinesResponse': json['GroupLinesResponse'] == null ? undefined : JoblogicAPIModelsQuoteGroupCostLinesResponseFromJSON(json['GroupLinesResponse']),
        'profitabilityQuote': json['ProfitabilityQuote'] == null ? undefined : JoblogicAPIModelsProfitabilityQuoteResponseFromJSON(json['ProfitabilityQuote']),
    };
}

export function JoblogicAPIModelsGetQuoteLinesResponseToJSON(json: any): JoblogicAPIModelsGetQuoteLinesResponse {
    return JoblogicAPIModelsGetQuoteLinesResponseToJSONTyped(json, false);
}

export function JoblogicAPIModelsGetQuoteLinesResponseToJSONTyped(value?: JoblogicAPIModelsGetQuoteLinesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'GroupLinesResponse': JoblogicAPIModelsQuoteGroupCostLinesResponseToJSON(value['groupLinesResponse']),
        'ProfitabilityQuote': JoblogicAPIModelsProfitabilityQuoteResponseToJSON(value['profitabilityQuote']),
    };
}

