/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobLogicMicroserviceCoreContractEnumsContractPurchaseOrderStatus } from './JobLogicMicroserviceCoreContractEnumsContractPurchaseOrderStatus';
import {
    JobLogicMicroserviceCoreContractEnumsContractPurchaseOrderStatusFromJSON,
    JobLogicMicroserviceCoreContractEnumsContractPurchaseOrderStatusFromJSONTyped,
    JobLogicMicroserviceCoreContractEnumsContractPurchaseOrderStatusToJSON,
    JobLogicMicroserviceCoreContractEnumsContractPurchaseOrderStatusToJSONTyped,
} from './JobLogicMicroserviceCoreContractEnumsContractPurchaseOrderStatus';
import type { JobLogicMicroserviceCoreContractInvoiceStatus } from './JobLogicMicroserviceCoreContractInvoiceStatus';
import {
    JobLogicMicroserviceCoreContractInvoiceStatusFromJSON,
    JobLogicMicroserviceCoreContractInvoiceStatusFromJSONTyped,
    JobLogicMicroserviceCoreContractInvoiceStatusToJSON,
    JobLogicMicroserviceCoreContractInvoiceStatusToJSONTyped,
} from './JobLogicMicroserviceCoreContractInvoiceStatus';
import type { JobLogicMicroserviceCoreContractEnumsContractPurchaseOrderCompletionStatus } from './JobLogicMicroserviceCoreContractEnumsContractPurchaseOrderCompletionStatus';
import {
    JobLogicMicroserviceCoreContractEnumsContractPurchaseOrderCompletionStatusFromJSON,
    JobLogicMicroserviceCoreContractEnumsContractPurchaseOrderCompletionStatusFromJSONTyped,
    JobLogicMicroserviceCoreContractEnumsContractPurchaseOrderCompletionStatusToJSON,
    JobLogicMicroserviceCoreContractEnumsContractPurchaseOrderCompletionStatusToJSONTyped,
} from './JobLogicMicroserviceCoreContractEnumsContractPurchaseOrderCompletionStatus';

/**
 * 
 * @export
 * @interface JoblogicAPIModelsContractPurchaseOrderItemResponse
 */
export interface JoblogicAPIModelsContractPurchaseOrderItemResponse {
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsContractPurchaseOrderItemResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsContractPurchaseOrderItemResponse
     */
    pONumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsContractPurchaseOrderItemResponse
     */
    pPMContractId?: string;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsContractPurchaseOrderItemResponse
     */
    pPMContractNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsContractPurchaseOrderItemResponse
     */
    subContractorName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsContractPurchaseOrderItemResponse
     */
    subContractorId?: string;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsContractPurchaseOrderItemResponse
     */
    accountNumber?: string | null;
    /**
     * 
     * @type {JobLogicMicroserviceCoreContractEnumsContractPurchaseOrderStatus}
     * @memberof JoblogicAPIModelsContractPurchaseOrderItemResponse
     */
    status?: JobLogicMicroserviceCoreContractEnumsContractPurchaseOrderStatus;
    /**
     * 
     * @type {JobLogicMicroserviceCoreContractEnumsContractPurchaseOrderCompletionStatus}
     * @memberof JoblogicAPIModelsContractPurchaseOrderItemResponse
     */
    completionStatus?: JobLogicMicroserviceCoreContractEnumsContractPurchaseOrderCompletionStatus;
    /**
     * 
     * @type {JobLogicMicroserviceCoreContractInvoiceStatus}
     * @memberof JoblogicAPIModelsContractPurchaseOrderItemResponse
     */
    invoiceStatus?: JobLogicMicroserviceCoreContractInvoiceStatus;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsContractPurchaseOrderItemResponse
     */
    totalExcludingVat?: number;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsContractPurchaseOrderItemResponse
     */
    totalIncludingVat?: number;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsContractPurchaseOrderItemResponse
     */
    totalInvoicedExcludingVat?: number;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsContractPurchaseOrderItemResponse
     */
    totalInvoicedIncludingVAT?: number;
    /**
     * 
     * @type {Date}
     * @memberof JoblogicAPIModelsContractPurchaseOrderItemResponse
     */
    dateRaised?: Date;
    /**
     * 
     * @type {Date}
     * @memberof JoblogicAPIModelsContractPurchaseOrderItemResponse
     */
    estimationCompletionDate?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof JoblogicAPIModelsContractPurchaseOrderItemResponse
     */
    actualCompletionDate?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof JoblogicAPIModelsContractPurchaseOrderItemResponse
     */
    endDate?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof JoblogicAPIModelsContractPurchaseOrderItemResponse
     */
    startDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsContractPurchaseOrderItemResponse
     */
    customReference?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsContractPurchaseOrderItemResponse
     */
    raisedByUserName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsContractPurchaseOrderItemResponse
     */
    ownerName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsContractPurchaseOrderItemResponse
     */
    tagsJson?: string | null;
}



/**
 * Check if a given object implements the JoblogicAPIModelsContractPurchaseOrderItemResponse interface.
 */
export function instanceOfJoblogicAPIModelsContractPurchaseOrderItemResponse(value: object): value is JoblogicAPIModelsContractPurchaseOrderItemResponse {
    return true;
}

export function JoblogicAPIModelsContractPurchaseOrderItemResponseFromJSON(json: any): JoblogicAPIModelsContractPurchaseOrderItemResponse {
    return JoblogicAPIModelsContractPurchaseOrderItemResponseFromJSONTyped(json, false);
}

export function JoblogicAPIModelsContractPurchaseOrderItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsContractPurchaseOrderItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['Id'] == null ? undefined : json['Id'],
        'pONumber': json['PONumber'] == null ? undefined : json['PONumber'],
        'pPMContractId': json['PPMContractId'] == null ? undefined : json['PPMContractId'],
        'pPMContractNumber': json['PPMContractNumber'] == null ? undefined : json['PPMContractNumber'],
        'subContractorName': json['SubContractorName'] == null ? undefined : json['SubContractorName'],
        'subContractorId': json['SubContractorId'] == null ? undefined : json['SubContractorId'],
        'accountNumber': json['AccountNumber'] == null ? undefined : json['AccountNumber'],
        'status': json['Status'] == null ? undefined : JobLogicMicroserviceCoreContractEnumsContractPurchaseOrderStatusFromJSON(json['Status']),
        'completionStatus': json['CompletionStatus'] == null ? undefined : JobLogicMicroserviceCoreContractEnumsContractPurchaseOrderCompletionStatusFromJSON(json['CompletionStatus']),
        'invoiceStatus': json['InvoiceStatus'] == null ? undefined : JobLogicMicroserviceCoreContractInvoiceStatusFromJSON(json['InvoiceStatus']),
        'totalExcludingVat': json['TotalExcludingVat'] == null ? undefined : json['TotalExcludingVat'],
        'totalIncludingVat': json['TotalIncludingVat'] == null ? undefined : json['TotalIncludingVat'],
        'totalInvoicedExcludingVat': json['TotalInvoicedExcludingVat'] == null ? undefined : json['TotalInvoicedExcludingVat'],
        'totalInvoicedIncludingVAT': json['TotalInvoicedIncludingVAT'] == null ? undefined : json['TotalInvoicedIncludingVAT'],
        'dateRaised': json['DateRaised'] == null ? undefined : (new Date(json['DateRaised'])),
        'estimationCompletionDate': json['EstimationCompletionDate'] == null ? undefined : (new Date(json['EstimationCompletionDate'])),
        'actualCompletionDate': json['ActualCompletionDate'] == null ? undefined : (new Date(json['ActualCompletionDate'])),
        'endDate': json['EndDate'] == null ? undefined : (new Date(json['EndDate'])),
        'startDate': json['StartDate'] == null ? undefined : (new Date(json['StartDate'])),
        'customReference': json['CustomReference'] == null ? undefined : json['CustomReference'],
        'raisedByUserName': json['RaisedByUserName'] == null ? undefined : json['RaisedByUserName'],
        'ownerName': json['OwnerName'] == null ? undefined : json['OwnerName'],
        'tagsJson': json['TagsJson'] == null ? undefined : json['TagsJson'],
    };
}

export function JoblogicAPIModelsContractPurchaseOrderItemResponseToJSON(json: any): JoblogicAPIModelsContractPurchaseOrderItemResponse {
    return JoblogicAPIModelsContractPurchaseOrderItemResponseToJSONTyped(json, false);
}

export function JoblogicAPIModelsContractPurchaseOrderItemResponseToJSONTyped(value?: JoblogicAPIModelsContractPurchaseOrderItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Id': value['id'],
        'PONumber': value['pONumber'],
        'PPMContractId': value['pPMContractId'],
        'PPMContractNumber': value['pPMContractNumber'],
        'SubContractorName': value['subContractorName'],
        'SubContractorId': value['subContractorId'],
        'AccountNumber': value['accountNumber'],
        'Status': JobLogicMicroserviceCoreContractEnumsContractPurchaseOrderStatusToJSON(value['status']),
        'CompletionStatus': JobLogicMicroserviceCoreContractEnumsContractPurchaseOrderCompletionStatusToJSON(value['completionStatus']),
        'InvoiceStatus': JobLogicMicroserviceCoreContractInvoiceStatusToJSON(value['invoiceStatus']),
        'TotalExcludingVat': value['totalExcludingVat'],
        'TotalIncludingVat': value['totalIncludingVat'],
        'TotalInvoicedExcludingVat': value['totalInvoicedExcludingVat'],
        'TotalInvoicedIncludingVAT': value['totalInvoicedIncludingVAT'],
        'DateRaised': value['dateRaised'] == null ? value['dateRaised'] : value['dateRaised'].toISOString(),
        'EstimationCompletionDate': value['estimationCompletionDate'] == null ? value['estimationCompletionDate'] : value['estimationCompletionDate'].toISOString(),
        'ActualCompletionDate': value['actualCompletionDate'] == null ? value['actualCompletionDate'] : value['actualCompletionDate'].toISOString(),
        'EndDate': value['endDate'] == null ? value['endDate'] : value['endDate'].toISOString(),
        'StartDate': value['startDate'] == null ? value['startDate'] : value['startDate'].toISOString(),
        'CustomReference': value['customReference'],
        'RaisedByUserName': value['raisedByUserName'],
        'OwnerName': value['ownerName'],
        'TagsJson': value['tagsJson'],
    };
}

