/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const JoblogicAPIPOLineDeliveryStatus = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4
} as const;
export type JoblogicAPIPOLineDeliveryStatus = typeof JoblogicAPIPOLineDeliveryStatus[keyof typeof JoblogicAPIPOLineDeliveryStatus];


export function instanceOfJoblogicAPIPOLineDeliveryStatus(value: any): boolean {
    for (const key in JoblogicAPIPOLineDeliveryStatus) {
        if (Object.prototype.hasOwnProperty.call(JoblogicAPIPOLineDeliveryStatus, key)) {
            if (JoblogicAPIPOLineDeliveryStatus[key as keyof typeof JoblogicAPIPOLineDeliveryStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function JoblogicAPIPOLineDeliveryStatusFromJSON(json: any): JoblogicAPIPOLineDeliveryStatus {
    return JoblogicAPIPOLineDeliveryStatusFromJSONTyped(json, false);
}

export function JoblogicAPIPOLineDeliveryStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIPOLineDeliveryStatus {
    return json as JoblogicAPIPOLineDeliveryStatus;
}

export function JoblogicAPIPOLineDeliveryStatusToJSON(value?: JoblogicAPIPOLineDeliveryStatus | null): any {
    return value as any;
}

export function JoblogicAPIPOLineDeliveryStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): JoblogicAPIPOLineDeliveryStatus {
    return value as JoblogicAPIPOLineDeliveryStatus;
}

