/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JoblogicAPIModelsCreateCustomerTypeRequest
 */
export interface JoblogicAPIModelsCreateCustomerTypeRequest {
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCreateCustomerTypeRequest
     */
    description: string;
    /**
     * Contractor Id in Joblogic
     * @type {string}
     * @memberof JoblogicAPIModelsCreateCustomerTypeRequest
     */
    tenantId: string;
}

/**
 * Check if a given object implements the JoblogicAPIModelsCreateCustomerTypeRequest interface.
 */
export function instanceOfJoblogicAPIModelsCreateCustomerTypeRequest(value: object): value is JoblogicAPIModelsCreateCustomerTypeRequest {
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    return true;
}

export function JoblogicAPIModelsCreateCustomerTypeRequestFromJSON(json: any): JoblogicAPIModelsCreateCustomerTypeRequest {
    return JoblogicAPIModelsCreateCustomerTypeRequestFromJSONTyped(json, false);
}

export function JoblogicAPIModelsCreateCustomerTypeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsCreateCustomerTypeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['Description'],
        'tenantId': json['TenantId'],
    };
}

export function JoblogicAPIModelsCreateCustomerTypeRequestToJSON(json: any): JoblogicAPIModelsCreateCustomerTypeRequest {
    return JoblogicAPIModelsCreateCustomerTypeRequestToJSONTyped(json, false);
}

export function JoblogicAPIModelsCreateCustomerTypeRequestToJSONTyped(value?: JoblogicAPIModelsCreateCustomerTypeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Description': value['description'],
        'TenantId': value['tenantId'],
    };
}

