/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JoblogicAPIModelsUpdateCustomerTypeRequest
 */
export interface JoblogicAPIModelsUpdateCustomerTypeRequest {
    /**
     * The Id of the Customer Type in Joblogic
     * @type {string}
     * @memberof JoblogicAPIModelsUpdateCustomerTypeRequest
     */
    uniqueId: string;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsUpdateCustomerTypeRequest
     */
    description?: string | null;
    /**
     * Contractor Id in Joblogic
     * @type {string}
     * @memberof JoblogicAPIModelsUpdateCustomerTypeRequest
     */
    tenantId: string;
}

/**
 * Check if a given object implements the JoblogicAPIModelsUpdateCustomerTypeRequest interface.
 */
export function instanceOfJoblogicAPIModelsUpdateCustomerTypeRequest(value: object): value is JoblogicAPIModelsUpdateCustomerTypeRequest {
    if (!('uniqueId' in value) || value['uniqueId'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    return true;
}

export function JoblogicAPIModelsUpdateCustomerTypeRequestFromJSON(json: any): JoblogicAPIModelsUpdateCustomerTypeRequest {
    return JoblogicAPIModelsUpdateCustomerTypeRequestFromJSONTyped(json, false);
}

export function JoblogicAPIModelsUpdateCustomerTypeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsUpdateCustomerTypeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'uniqueId': json['UniqueId'],
        'description': json['Description'] == null ? undefined : json['Description'],
        'tenantId': json['TenantId'],
    };
}

export function JoblogicAPIModelsUpdateCustomerTypeRequestToJSON(json: any): JoblogicAPIModelsUpdateCustomerTypeRequest {
    return JoblogicAPIModelsUpdateCustomerTypeRequestToJSONTyped(json, false);
}

export function JoblogicAPIModelsUpdateCustomerTypeRequestToJSONTyped(value?: JoblogicAPIModelsUpdateCustomerTypeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'UniqueId': value['uniqueId'],
        'Description': value['description'],
        'TenantId': value['tenantId'],
    };
}

