/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JoblogicAPIModelsSearchPayBandResponseItem } from './JoblogicAPIModelsSearchPayBandResponseItem';
import {
    JoblogicAPIModelsSearchPayBandResponseItemFromJSON,
    JoblogicAPIModelsSearchPayBandResponseItemFromJSONTyped,
    JoblogicAPIModelsSearchPayBandResponseItemToJSON,
    JoblogicAPIModelsSearchPayBandResponseItemToJSONTyped,
} from './JoblogicAPIModelsSearchPayBandResponseItem';

/**
 * 
 * @export
 * @interface JoblogicAPIModelsSearchPayBandResponse
 */
export interface JoblogicAPIModelsSearchPayBandResponse {
    /**
     * 
     * @type {Array<JoblogicAPIModelsSearchPayBandResponseItem>}
     * @memberof JoblogicAPIModelsSearchPayBandResponse
     */
    results?: Array<JoblogicAPIModelsSearchPayBandResponseItem> | null;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsSearchPayBandResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsSearchPayBandResponse
     */
    pageIndex?: number;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsSearchPayBandResponse
     */
    pageSize?: number;
}

/**
 * Check if a given object implements the JoblogicAPIModelsSearchPayBandResponse interface.
 */
export function instanceOfJoblogicAPIModelsSearchPayBandResponse(value: object): value is JoblogicAPIModelsSearchPayBandResponse {
    return true;
}

export function JoblogicAPIModelsSearchPayBandResponseFromJSON(json: any): JoblogicAPIModelsSearchPayBandResponse {
    return JoblogicAPIModelsSearchPayBandResponseFromJSONTyped(json, false);
}

export function JoblogicAPIModelsSearchPayBandResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsSearchPayBandResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'results': json['Results'] == null ? undefined : ((json['Results'] as Array<any>).map(JoblogicAPIModelsSearchPayBandResponseItemFromJSON)),
        'totalCount': json['TotalCount'] == null ? undefined : json['TotalCount'],
        'pageIndex': json['PageIndex'] == null ? undefined : json['PageIndex'],
        'pageSize': json['PageSize'] == null ? undefined : json['PageSize'],
    };
}

export function JoblogicAPIModelsSearchPayBandResponseToJSON(json: any): JoblogicAPIModelsSearchPayBandResponse {
    return JoblogicAPIModelsSearchPayBandResponseToJSONTyped(json, false);
}

export function JoblogicAPIModelsSearchPayBandResponseToJSONTyped(value?: JoblogicAPIModelsSearchPayBandResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(JoblogicAPIModelsSearchPayBandResponseItemToJSON)),
        'TotalCount': value['totalCount'],
        'PageIndex': value['pageIndex'],
        'PageSize': value['pageSize'],
    };
}

