/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const JobLogicMicroserviceCoreContractFrequencyPeriod = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4
} as const;
export type JobLogicMicroserviceCoreContractFrequencyPeriod = typeof JobLogicMicroserviceCoreContractFrequencyPeriod[keyof typeof JobLogicMicroserviceCoreContractFrequencyPeriod];


export function instanceOfJobLogicMicroserviceCoreContractFrequencyPeriod(value: any): boolean {
    for (const key in JobLogicMicroserviceCoreContractFrequencyPeriod) {
        if (Object.prototype.hasOwnProperty.call(JobLogicMicroserviceCoreContractFrequencyPeriod, key)) {
            if (JobLogicMicroserviceCoreContractFrequencyPeriod[key as keyof typeof JobLogicMicroserviceCoreContractFrequencyPeriod] === value) {
                return true;
            }
        }
    }
    return false;
}

export function JobLogicMicroserviceCoreContractFrequencyPeriodFromJSON(json: any): JobLogicMicroserviceCoreContractFrequencyPeriod {
    return JobLogicMicroserviceCoreContractFrequencyPeriodFromJSONTyped(json, false);
}

export function JobLogicMicroserviceCoreContractFrequencyPeriodFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobLogicMicroserviceCoreContractFrequencyPeriod {
    return json as JobLogicMicroserviceCoreContractFrequencyPeriod;
}

export function JobLogicMicroserviceCoreContractFrequencyPeriodToJSON(value?: JobLogicMicroserviceCoreContractFrequencyPeriod | null): any {
    return value as any;
}

export function JobLogicMicroserviceCoreContractFrequencyPeriodToJSONTyped(value: any, ignoreDiscriminator: boolean): JobLogicMicroserviceCoreContractFrequencyPeriod {
    return value as JobLogicMicroserviceCoreContractFrequencyPeriod;
}

