/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JoblogicAPIModelsNGBSubContractorPOAreaItemResponse
 */
export interface JoblogicAPIModelsNGBSubContractorPOAreaItemResponse {
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsNGBSubContractorPOAreaItemResponse
     */
    stringId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsNGBSubContractorPOAreaItemResponse
     */
    description?: string | null;
}

/**
 * Check if a given object implements the JoblogicAPIModelsNGBSubContractorPOAreaItemResponse interface.
 */
export function instanceOfJoblogicAPIModelsNGBSubContractorPOAreaItemResponse(value: object): value is JoblogicAPIModelsNGBSubContractorPOAreaItemResponse {
    return true;
}

export function JoblogicAPIModelsNGBSubContractorPOAreaItemResponseFromJSON(json: any): JoblogicAPIModelsNGBSubContractorPOAreaItemResponse {
    return JoblogicAPIModelsNGBSubContractorPOAreaItemResponseFromJSONTyped(json, false);
}

export function JoblogicAPIModelsNGBSubContractorPOAreaItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsNGBSubContractorPOAreaItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'stringId': json['StringId'] == null ? undefined : json['StringId'],
        'description': json['Description'] == null ? undefined : json['Description'],
    };
}

export function JoblogicAPIModelsNGBSubContractorPOAreaItemResponseToJSON(json: any): JoblogicAPIModelsNGBSubContractorPOAreaItemResponse {
    return JoblogicAPIModelsNGBSubContractorPOAreaItemResponseToJSONTyped(json, false);
}

export function JoblogicAPIModelsNGBSubContractorPOAreaItemResponseToJSONTyped(value?: JoblogicAPIModelsNGBSubContractorPOAreaItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'StringId': value['stringId'],
        'Description': value['description'],
    };
}

