/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobLogicMicroserviceCoreContractEntityType } from './JobLogicMicroserviceCoreContractEntityType';
import {
    JobLogicMicroserviceCoreContractEntityTypeFromJSON,
    JobLogicMicroserviceCoreContractEntityTypeFromJSONTyped,
    JobLogicMicroserviceCoreContractEntityTypeToJSON,
    JobLogicMicroserviceCoreContractEntityTypeToJSONTyped,
} from './JobLogicMicroserviceCoreContractEntityType';

/**
 * 
 * @export
 * @interface JoblogicAPIModelsContactItemResponseContactLevelItemResponse
 */
export interface JoblogicAPIModelsContactItemResponseContactLevelItemResponse {
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsContactItemResponseContactLevelItemResponse
     */
    id?: string;
    /**
     * 
     * @type {JobLogicMicroserviceCoreContractEntityType}
     * @memberof JoblogicAPIModelsContactItemResponseContactLevelItemResponse
     */
    entityType?: JobLogicMicroserviceCoreContractEntityType;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsContactItemResponseContactLevelItemResponse
     */
    entityId?: string;
}



/**
 * Check if a given object implements the JoblogicAPIModelsContactItemResponseContactLevelItemResponse interface.
 */
export function instanceOfJoblogicAPIModelsContactItemResponseContactLevelItemResponse(value: object): value is JoblogicAPIModelsContactItemResponseContactLevelItemResponse {
    return true;
}

export function JoblogicAPIModelsContactItemResponseContactLevelItemResponseFromJSON(json: any): JoblogicAPIModelsContactItemResponseContactLevelItemResponse {
    return JoblogicAPIModelsContactItemResponseContactLevelItemResponseFromJSONTyped(json, false);
}

export function JoblogicAPIModelsContactItemResponseContactLevelItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsContactItemResponseContactLevelItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['Id'] == null ? undefined : json['Id'],
        'entityType': json['EntityType'] == null ? undefined : JobLogicMicroserviceCoreContractEntityTypeFromJSON(json['EntityType']),
        'entityId': json['EntityId'] == null ? undefined : json['EntityId'],
    };
}

export function JoblogicAPIModelsContactItemResponseContactLevelItemResponseToJSON(json: any): JoblogicAPIModelsContactItemResponseContactLevelItemResponse {
    return JoblogicAPIModelsContactItemResponseContactLevelItemResponseToJSONTyped(json, false);
}

export function JoblogicAPIModelsContactItemResponseContactLevelItemResponseToJSONTyped(value?: JoblogicAPIModelsContactItemResponseContactLevelItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Id': value['id'],
        'EntityType': JobLogicMicroserviceCoreContractEntityTypeToJSON(value['entityType']),
        'EntityId': value['entityId'],
    };
}

