/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JoblogicAPIModelsJobDetail
 */
export interface JoblogicAPIModelsJobDetail {
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsJobDetail
     */
    text?: string | null;
}

/**
 * Check if a given object implements the JoblogicAPIModelsJobDetail interface.
 */
export function instanceOfJoblogicAPIModelsJobDetail(value: object): value is JoblogicAPIModelsJobDetail {
    return true;
}

export function JoblogicAPIModelsJobDetailFromJSON(json: any): JoblogicAPIModelsJobDetail {
    return JoblogicAPIModelsJobDetailFromJSONTyped(json, false);
}

export function JoblogicAPIModelsJobDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsJobDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'] == null ? undefined : json['text'],
    };
}

export function JoblogicAPIModelsJobDetailToJSON(json: any): JoblogicAPIModelsJobDetail {
    return JoblogicAPIModelsJobDetailToJSONTyped(json, false);
}

export function JoblogicAPIModelsJobDetailToJSONTyped(value?: JoblogicAPIModelsJobDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
    };
}

