/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JoblogicAPIModelsUpdateStockRackRequest
 */
export interface JoblogicAPIModelsUpdateStockRackRequest {
    /**
     * The Id of the Stock Rack in Joblogic
     * @type {number}
     * @memberof JoblogicAPIModelsUpdateStockRackRequest
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsUpdateStockRackRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsUpdateStockRackRequest
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsUpdateStockRackRequest
     */
    stockLocationId?: number;
    /**
     * Contractor Id in Joblogic
     * @type {string}
     * @memberof JoblogicAPIModelsUpdateStockRackRequest
     */
    tenantId: string;
}

/**
 * Check if a given object implements the JoblogicAPIModelsUpdateStockRackRequest interface.
 */
export function instanceOfJoblogicAPIModelsUpdateStockRackRequest(value: object): value is JoblogicAPIModelsUpdateStockRackRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    return true;
}

export function JoblogicAPIModelsUpdateStockRackRequestFromJSON(json: any): JoblogicAPIModelsUpdateStockRackRequest {
    return JoblogicAPIModelsUpdateStockRackRequestFromJSONTyped(json, false);
}

export function JoblogicAPIModelsUpdateStockRackRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsUpdateStockRackRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['Id'] == null ? undefined : json['Id'],
        'name': json['Name'],
        'description': json['Description'] == null ? undefined : json['Description'],
        'stockLocationId': json['StockLocationId'] == null ? undefined : json['StockLocationId'],
        'tenantId': json['TenantId'],
    };
}

export function JoblogicAPIModelsUpdateStockRackRequestToJSON(json: any): JoblogicAPIModelsUpdateStockRackRequest {
    return JoblogicAPIModelsUpdateStockRackRequestToJSONTyped(json, false);
}

export function JoblogicAPIModelsUpdateStockRackRequestToJSONTyped(value?: JoblogicAPIModelsUpdateStockRackRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Id': value['id'],
        'Name': value['name'],
        'Description': value['description'],
        'StockLocationId': value['stockLocationId'],
        'TenantId': value['tenantId'],
    };
}

