/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobLogicMicroserviceCoreContractSiteTypeOrderBy } from './JobLogicMicroserviceCoreContractSiteTypeOrderBy';
import {
    JobLogicMicroserviceCoreContractSiteTypeOrderByFromJSON,
    JobLogicMicroserviceCoreContractSiteTypeOrderByFromJSONTyped,
    JobLogicMicroserviceCoreContractSiteTypeOrderByToJSON,
    JobLogicMicroserviceCoreContractSiteTypeOrderByToJSONTyped,
} from './JobLogicMicroserviceCoreContractSiteTypeOrderBy';

/**
 * 
 * @export
 * @interface JoblogicAPIModelsSearchSiteTypeRequest
 */
export interface JoblogicAPIModelsSearchSiteTypeRequest {
    /**
     * 
     * @type {JobLogicMicroserviceCoreContractSiteTypeOrderBy}
     * @memberof JoblogicAPIModelsSearchSiteTypeRequest
     */
    orderBy?: JobLogicMicroserviceCoreContractSiteTypeOrderBy;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsSearchSiteTypeRequest
     */
    searchTerm?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof JoblogicAPIModelsSearchSiteTypeRequest
     */
    includeInactive?: boolean;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsSearchSiteTypeRequest
     */
    pageIndex?: number;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsSearchSiteTypeRequest
     */
    pageSize?: number;
    /**
     * Contractor Id in Joblogic
     * @type {string}
     * @memberof JoblogicAPIModelsSearchSiteTypeRequest
     */
    tenantId: string;
}



/**
 * Check if a given object implements the JoblogicAPIModelsSearchSiteTypeRequest interface.
 */
export function instanceOfJoblogicAPIModelsSearchSiteTypeRequest(value: object): value is JoblogicAPIModelsSearchSiteTypeRequest {
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    return true;
}

export function JoblogicAPIModelsSearchSiteTypeRequestFromJSON(json: any): JoblogicAPIModelsSearchSiteTypeRequest {
    return JoblogicAPIModelsSearchSiteTypeRequestFromJSONTyped(json, false);
}

export function JoblogicAPIModelsSearchSiteTypeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsSearchSiteTypeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'orderBy': json['OrderBy'] == null ? undefined : JobLogicMicroserviceCoreContractSiteTypeOrderByFromJSON(json['OrderBy']),
        'searchTerm': json['SearchTerm'] == null ? undefined : json['SearchTerm'],
        'includeInactive': json['IncludeInactive'] == null ? undefined : json['IncludeInactive'],
        'pageIndex': json['PageIndex'] == null ? undefined : json['PageIndex'],
        'pageSize': json['PageSize'] == null ? undefined : json['PageSize'],
        'tenantId': json['TenantId'],
    };
}

export function JoblogicAPIModelsSearchSiteTypeRequestToJSON(json: any): JoblogicAPIModelsSearchSiteTypeRequest {
    return JoblogicAPIModelsSearchSiteTypeRequestToJSONTyped(json, false);
}

export function JoblogicAPIModelsSearchSiteTypeRequestToJSONTyped(value?: JoblogicAPIModelsSearchSiteTypeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'OrderBy': JobLogicMicroserviceCoreContractSiteTypeOrderByToJSON(value['orderBy']),
        'SearchTerm': value['searchTerm'],
        'IncludeInactive': value['includeInactive'],
        'PageIndex': value['pageIndex'],
        'PageSize': value['pageSize'],
        'TenantId': value['tenantId'],
    };
}

