/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JoblogicAPINoteEntityType } from './JoblogicAPINoteEntityType';
import {
    JoblogicAPINoteEntityTypeFromJSON,
    JoblogicAPINoteEntityTypeFromJSONTyped,
    JoblogicAPINoteEntityTypeToJSON,
    JoblogicAPINoteEntityTypeToJSONTyped,
} from './JoblogicAPINoteEntityType';
import type { JoblogicAPIModelsAttachmentRequest } from './JoblogicAPIModelsAttachmentRequest';
import {
    JoblogicAPIModelsAttachmentRequestFromJSON,
    JoblogicAPIModelsAttachmentRequestFromJSONTyped,
    JoblogicAPIModelsAttachmentRequestToJSON,
    JoblogicAPIModelsAttachmentRequestToJSONTyped,
} from './JoblogicAPIModelsAttachmentRequest';

/**
 * 
 * @export
 * @interface JoblogicAPIModelsCreateNoteRequest
 */
export interface JoblogicAPIModelsCreateNoteRequest {
    /**
     * Unique Id of the entity associated with the created note
     * @type {string}
     * @memberof JoblogicAPIModelsCreateNoteRequest
     */
    entityId: string;
    /**
     * 
     * @type {JoblogicAPINoteEntityType}
     * @memberof JoblogicAPIModelsCreateNoteRequest
     */
    entityType?: JoblogicAPINoteEntityType;
    /**
     * Detail note information
     * @type {string}
     * @memberof JoblogicAPIModelsCreateNoteRequest
     */
    noteText?: string | null;
    /**
     * The date the note was added, default to current datetime if passed as null
     * @type {Date}
     * @memberof JoblogicAPIModelsCreateNoteRequest
     */
    dateAdded?: Date | null;
    /**
     * Set to true if this note is private
     * @type {boolean}
     * @memberof JoblogicAPIModelsCreateNoteRequest
     */
    isPrivate?: boolean;
    /**
     * A list of attachments for note
     * @type {Array<JoblogicAPIModelsAttachmentRequest>}
     * @memberof JoblogicAPIModelsCreateNoteRequest
     */
    attachments?: Array<JoblogicAPIModelsAttachmentRequest> | null;
    /**
     * A list of tags, associated to the Note that can be used for searching/filtering
     * @type {Array<string>}
     * @memberof JoblogicAPIModelsCreateNoteRequest
     */
    tags?: Array<string> | null;
    /**
     * Contractor Id in Joblogic
     * @type {string}
     * @memberof JoblogicAPIModelsCreateNoteRequest
     */
    tenantId: string;
}



/**
 * Check if a given object implements the JoblogicAPIModelsCreateNoteRequest interface.
 */
export function instanceOfJoblogicAPIModelsCreateNoteRequest(value: object): value is JoblogicAPIModelsCreateNoteRequest {
    if (!('entityId' in value) || value['entityId'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    return true;
}

export function JoblogicAPIModelsCreateNoteRequestFromJSON(json: any): JoblogicAPIModelsCreateNoteRequest {
    return JoblogicAPIModelsCreateNoteRequestFromJSONTyped(json, false);
}

export function JoblogicAPIModelsCreateNoteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsCreateNoteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'entityId': json['EntityId'],
        'entityType': json['EntityType'] == null ? undefined : JoblogicAPINoteEntityTypeFromJSON(json['EntityType']),
        'noteText': json['NoteText'] == null ? undefined : json['NoteText'],
        'dateAdded': json['DateAdded'] == null ? undefined : (new Date(json['DateAdded'])),
        'isPrivate': json['IsPrivate'] == null ? undefined : json['IsPrivate'],
        'attachments': json['Attachments'] == null ? undefined : ((json['Attachments'] as Array<any>).map(JoblogicAPIModelsAttachmentRequestFromJSON)),
        'tags': json['Tags'] == null ? undefined : json['Tags'],
        'tenantId': json['TenantId'],
    };
}

export function JoblogicAPIModelsCreateNoteRequestToJSON(json: any): JoblogicAPIModelsCreateNoteRequest {
    return JoblogicAPIModelsCreateNoteRequestToJSONTyped(json, false);
}

export function JoblogicAPIModelsCreateNoteRequestToJSONTyped(value?: JoblogicAPIModelsCreateNoteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'EntityId': value['entityId'],
        'EntityType': JoblogicAPINoteEntityTypeToJSON(value['entityType']),
        'NoteText': value['noteText'],
        'DateAdded': value['dateAdded'] == null ? value['dateAdded'] : value['dateAdded'].toISOString(),
        'IsPrivate': value['isPrivate'],
        'Attachments': value['attachments'] == null ? undefined : ((value['attachments'] as Array<any>).map(JoblogicAPIModelsAttachmentRequestToJSON)),
        'Tags': value['tags'],
        'TenantId': value['tenantId'],
    };
}

