/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const JobLogicMicroserviceCoreContractAppointmentStatus = {
    NUMBER_0: 0,
    NUMBER_1: 1
} as const;
export type JobLogicMicroserviceCoreContractAppointmentStatus = typeof JobLogicMicroserviceCoreContractAppointmentStatus[keyof typeof JobLogicMicroserviceCoreContractAppointmentStatus];


export function instanceOfJobLogicMicroserviceCoreContractAppointmentStatus(value: any): boolean {
    for (const key in JobLogicMicroserviceCoreContractAppointmentStatus) {
        if (Object.prototype.hasOwnProperty.call(JobLogicMicroserviceCoreContractAppointmentStatus, key)) {
            if (JobLogicMicroserviceCoreContractAppointmentStatus[key as keyof typeof JobLogicMicroserviceCoreContractAppointmentStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function JobLogicMicroserviceCoreContractAppointmentStatusFromJSON(json: any): JobLogicMicroserviceCoreContractAppointmentStatus {
    return JobLogicMicroserviceCoreContractAppointmentStatusFromJSONTyped(json, false);
}

export function JobLogicMicroserviceCoreContractAppointmentStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobLogicMicroserviceCoreContractAppointmentStatus {
    return json as JobLogicMicroserviceCoreContractAppointmentStatus;
}

export function JobLogicMicroserviceCoreContractAppointmentStatusToJSON(value?: JobLogicMicroserviceCoreContractAppointmentStatus | null): any {
    return value as any;
}

export function JobLogicMicroserviceCoreContractAppointmentStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): JobLogicMicroserviceCoreContractAppointmentStatus {
    return value as JobLogicMicroserviceCoreContractAppointmentStatus;
}

