/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JoblogicAPIModelsSearchAuditItemResponse } from './JoblogicAPIModelsSearchAuditItemResponse';
import {
    JoblogicAPIModelsSearchAuditItemResponseFromJSON,
    JoblogicAPIModelsSearchAuditItemResponseFromJSONTyped,
    JoblogicAPIModelsSearchAuditItemResponseToJSON,
    JoblogicAPIModelsSearchAuditItemResponseToJSONTyped,
} from './JoblogicAPIModelsSearchAuditItemResponse';

/**
 * 
 * @export
 * @interface JoblogicAPIModelsSearchAuditResponse
 */
export interface JoblogicAPIModelsSearchAuditResponse {
    /**
     * 
     * @type {Array<JoblogicAPIModelsSearchAuditItemResponse>}
     * @memberof JoblogicAPIModelsSearchAuditResponse
     */
    items?: Array<JoblogicAPIModelsSearchAuditItemResponse> | null;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsSearchAuditResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsSearchAuditResponse
     */
    pageIndex?: number;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsSearchAuditResponse
     */
    pageSize?: number;
}

/**
 * Check if a given object implements the JoblogicAPIModelsSearchAuditResponse interface.
 */
export function instanceOfJoblogicAPIModelsSearchAuditResponse(value: object): value is JoblogicAPIModelsSearchAuditResponse {
    return true;
}

export function JoblogicAPIModelsSearchAuditResponseFromJSON(json: any): JoblogicAPIModelsSearchAuditResponse {
    return JoblogicAPIModelsSearchAuditResponseFromJSONTyped(json, false);
}

export function JoblogicAPIModelsSearchAuditResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsSearchAuditResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['Items'] == null ? undefined : ((json['Items'] as Array<any>).map(JoblogicAPIModelsSearchAuditItemResponseFromJSON)),
        'totalCount': json['TotalCount'] == null ? undefined : json['TotalCount'],
        'pageIndex': json['PageIndex'] == null ? undefined : json['PageIndex'],
        'pageSize': json['PageSize'] == null ? undefined : json['PageSize'],
    };
}

export function JoblogicAPIModelsSearchAuditResponseToJSON(json: any): JoblogicAPIModelsSearchAuditResponse {
    return JoblogicAPIModelsSearchAuditResponseToJSONTyped(json, false);
}

export function JoblogicAPIModelsSearchAuditResponseToJSONTyped(value?: JoblogicAPIModelsSearchAuditResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(JoblogicAPIModelsSearchAuditItemResponseToJSON)),
        'TotalCount': value['totalCount'],
        'PageIndex': value['pageIndex'],
        'PageSize': value['pageSize'],
    };
}

