/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const JoblogicAPIPurchaseOrderAddressTypeOption = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5,
    NUMBER_6: 6
} as const;
export type JoblogicAPIPurchaseOrderAddressTypeOption = typeof JoblogicAPIPurchaseOrderAddressTypeOption[keyof typeof JoblogicAPIPurchaseOrderAddressTypeOption];


export function instanceOfJoblogicAPIPurchaseOrderAddressTypeOption(value: any): boolean {
    for (const key in JoblogicAPIPurchaseOrderAddressTypeOption) {
        if (Object.prototype.hasOwnProperty.call(JoblogicAPIPurchaseOrderAddressTypeOption, key)) {
            if (JoblogicAPIPurchaseOrderAddressTypeOption[key as keyof typeof JoblogicAPIPurchaseOrderAddressTypeOption] === value) {
                return true;
            }
        }
    }
    return false;
}

export function JoblogicAPIPurchaseOrderAddressTypeOptionFromJSON(json: any): JoblogicAPIPurchaseOrderAddressTypeOption {
    return JoblogicAPIPurchaseOrderAddressTypeOptionFromJSONTyped(json, false);
}

export function JoblogicAPIPurchaseOrderAddressTypeOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIPurchaseOrderAddressTypeOption {
    return json as JoblogicAPIPurchaseOrderAddressTypeOption;
}

export function JoblogicAPIPurchaseOrderAddressTypeOptionToJSON(value?: JoblogicAPIPurchaseOrderAddressTypeOption | null): any {
    return value as any;
}

export function JoblogicAPIPurchaseOrderAddressTypeOptionToJSONTyped(value: any, ignoreDiscriminator: boolean): JoblogicAPIPurchaseOrderAddressTypeOption {
    return value as JoblogicAPIPurchaseOrderAddressTypeOption;
}

