/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JoblogicAPIModelsPartAdditionalDetailsRequest
 */
export interface JoblogicAPIModelsPartAdditionalDetailsRequest {
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsPartAdditionalDetailsRequest
     */
    make?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsPartAdditionalDetailsRequest
     */
    model?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsPartAdditionalDetailsRequest
     */
    partReference?: string | null;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsPartAdditionalDetailsRequest
     */
    partLibraryId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsPartAdditionalDetailsRequest
     */
    partCategoryId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsPartAdditionalDetailsRequest
     */
    taxCodeId?: string | null;
}

/**
 * Check if a given object implements the JoblogicAPIModelsPartAdditionalDetailsRequest interface.
 */
export function instanceOfJoblogicAPIModelsPartAdditionalDetailsRequest(value: object): value is JoblogicAPIModelsPartAdditionalDetailsRequest {
    return true;
}

export function JoblogicAPIModelsPartAdditionalDetailsRequestFromJSON(json: any): JoblogicAPIModelsPartAdditionalDetailsRequest {
    return JoblogicAPIModelsPartAdditionalDetailsRequestFromJSONTyped(json, false);
}

export function JoblogicAPIModelsPartAdditionalDetailsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsPartAdditionalDetailsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'make': json['Make'] == null ? undefined : json['Make'],
        'model': json['Model'] == null ? undefined : json['Model'],
        'partReference': json['PartReference'] == null ? undefined : json['PartReference'],
        'partLibraryId': json['PartLibraryId'] == null ? undefined : json['PartLibraryId'],
        'partCategoryId': json['PartCategoryId'] == null ? undefined : json['PartCategoryId'],
        'taxCodeId': json['TaxCodeId'] == null ? undefined : json['TaxCodeId'],
    };
}

export function JoblogicAPIModelsPartAdditionalDetailsRequestToJSON(json: any): JoblogicAPIModelsPartAdditionalDetailsRequest {
    return JoblogicAPIModelsPartAdditionalDetailsRequestToJSONTyped(json, false);
}

export function JoblogicAPIModelsPartAdditionalDetailsRequestToJSONTyped(value?: JoblogicAPIModelsPartAdditionalDetailsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Make': value['make'],
        'Model': value['model'],
        'PartReference': value['partReference'],
        'PartLibraryId': value['partLibraryId'],
        'PartCategoryId': value['partCategoryId'],
        'TaxCodeId': value['taxCodeId'],
    };
}

