/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JoblogicAPIModelsCustomerAdditionalDetailsWarningNotes
 */
export interface JoblogicAPIModelsCustomerAdditionalDetailsWarningNotes {
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCustomerAdditionalDetailsWarningNotes
     */
    notes?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof JoblogicAPIModelsCustomerAdditionalDetailsWarningNotes
     */
    show?: boolean;
}

/**
 * Check if a given object implements the JoblogicAPIModelsCustomerAdditionalDetailsWarningNotes interface.
 */
export function instanceOfJoblogicAPIModelsCustomerAdditionalDetailsWarningNotes(value: object): value is JoblogicAPIModelsCustomerAdditionalDetailsWarningNotes {
    return true;
}

export function JoblogicAPIModelsCustomerAdditionalDetailsWarningNotesFromJSON(json: any): JoblogicAPIModelsCustomerAdditionalDetailsWarningNotes {
    return JoblogicAPIModelsCustomerAdditionalDetailsWarningNotesFromJSONTyped(json, false);
}

export function JoblogicAPIModelsCustomerAdditionalDetailsWarningNotesFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsCustomerAdditionalDetailsWarningNotes {
    if (json == null) {
        return json;
    }
    return {
        
        'notes': json['Notes'] == null ? undefined : json['Notes'],
        'show': json['Show'] == null ? undefined : json['Show'],
    };
}

export function JoblogicAPIModelsCustomerAdditionalDetailsWarningNotesToJSON(json: any): JoblogicAPIModelsCustomerAdditionalDetailsWarningNotes {
    return JoblogicAPIModelsCustomerAdditionalDetailsWarningNotesToJSONTyped(json, false);
}

export function JoblogicAPIModelsCustomerAdditionalDetailsWarningNotesToJSONTyped(value?: JoblogicAPIModelsCustomerAdditionalDetailsWarningNotes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Notes': value['notes'],
        'Show': value['show'],
    };
}

