/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobLogicMicroserviceCoreContractInvoicePaymentDueType } from './JobLogicMicroserviceCoreContractInvoicePaymentDueType';
import {
    JobLogicMicroserviceCoreContractInvoicePaymentDueTypeFromJSON,
    JobLogicMicroserviceCoreContractInvoicePaymentDueTypeFromJSONTyped,
    JobLogicMicroserviceCoreContractInvoicePaymentDueTypeToJSON,
    JobLogicMicroserviceCoreContractInvoicePaymentDueTypeToJSONTyped,
} from './JobLogicMicroserviceCoreContractInvoicePaymentDueType';

/**
 * 
 * @export
 * @interface JoblogicAPIModelsCustomerAdditionalDetailsRequestCustomerInvoiceDetails
 */
export interface JoblogicAPIModelsCustomerAdditionalDetailsRequestCustomerInvoiceDetails {
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsCustomerAdditionalDetailsRequestCustomerInvoiceDetails
     */
    paymentDue?: number | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCustomerAdditionalDetailsRequestCustomerInvoiceDetails
     */
    paymentTerm?: string | null;
    /**
     * 
     * @type {JobLogicMicroserviceCoreContractInvoicePaymentDueType}
     * @memberof JoblogicAPIModelsCustomerAdditionalDetailsRequestCustomerInvoiceDetails
     */
    methodOfPayment?: JobLogicMicroserviceCoreContractInvoicePaymentDueType;
}



/**
 * Check if a given object implements the JoblogicAPIModelsCustomerAdditionalDetailsRequestCustomerInvoiceDetails interface.
 */
export function instanceOfJoblogicAPIModelsCustomerAdditionalDetailsRequestCustomerInvoiceDetails(value: object): value is JoblogicAPIModelsCustomerAdditionalDetailsRequestCustomerInvoiceDetails {
    return true;
}

export function JoblogicAPIModelsCustomerAdditionalDetailsRequestCustomerInvoiceDetailsFromJSON(json: any): JoblogicAPIModelsCustomerAdditionalDetailsRequestCustomerInvoiceDetails {
    return JoblogicAPIModelsCustomerAdditionalDetailsRequestCustomerInvoiceDetailsFromJSONTyped(json, false);
}

export function JoblogicAPIModelsCustomerAdditionalDetailsRequestCustomerInvoiceDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsCustomerAdditionalDetailsRequestCustomerInvoiceDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'paymentDue': json['PaymentDue'] == null ? undefined : json['PaymentDue'],
        'paymentTerm': json['PaymentTerm'] == null ? undefined : json['PaymentTerm'],
        'methodOfPayment': json['MethodOfPayment'] == null ? undefined : JobLogicMicroserviceCoreContractInvoicePaymentDueTypeFromJSON(json['MethodOfPayment']),
    };
}

export function JoblogicAPIModelsCustomerAdditionalDetailsRequestCustomerInvoiceDetailsToJSON(json: any): JoblogicAPIModelsCustomerAdditionalDetailsRequestCustomerInvoiceDetails {
    return JoblogicAPIModelsCustomerAdditionalDetailsRequestCustomerInvoiceDetailsToJSONTyped(json, false);
}

export function JoblogicAPIModelsCustomerAdditionalDetailsRequestCustomerInvoiceDetailsToJSONTyped(value?: JoblogicAPIModelsCustomerAdditionalDetailsRequestCustomerInvoiceDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'PaymentDue': value['paymentDue'],
        'PaymentTerm': value['paymentTerm'],
        'MethodOfPayment': JobLogicMicroserviceCoreContractInvoicePaymentDueTypeToJSON(value['methodOfPayment']),
    };
}

