/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JoblogicAPIModelsSearchEngineerTeamRequest
 */
export interface JoblogicAPIModelsSearchEngineerTeamRequest {
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsSearchEngineerTeamRequest
     */
    orderBy?: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof JoblogicAPIModelsSearchEngineerTeamRequest
     */
    engineerIds?: Array<number> | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof JoblogicAPIModelsSearchEngineerTeamRequest
     */
    classIds?: Array<number> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof JoblogicAPIModelsSearchEngineerTeamRequest
     */
    areaIds?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof JoblogicAPIModelsSearchEngineerTeamRequest
     */
    tradeIds?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsSearchEngineerTeamRequest
     */
    searchTerm?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof JoblogicAPIModelsSearchEngineerTeamRequest
     */
    includeInactive?: boolean;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsSearchEngineerTeamRequest
     */
    pageIndex?: number;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsSearchEngineerTeamRequest
     */
    pageSize?: number;
    /**
     * Contractor Id in Joblogic
     * @type {string}
     * @memberof JoblogicAPIModelsSearchEngineerTeamRequest
     */
    tenantId: string;
}

/**
 * Check if a given object implements the JoblogicAPIModelsSearchEngineerTeamRequest interface.
 */
export function instanceOfJoblogicAPIModelsSearchEngineerTeamRequest(value: object): value is JoblogicAPIModelsSearchEngineerTeamRequest {
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    return true;
}

export function JoblogicAPIModelsSearchEngineerTeamRequestFromJSON(json: any): JoblogicAPIModelsSearchEngineerTeamRequest {
    return JoblogicAPIModelsSearchEngineerTeamRequestFromJSONTyped(json, false);
}

export function JoblogicAPIModelsSearchEngineerTeamRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsSearchEngineerTeamRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'orderBy': json['OrderBy'] == null ? undefined : json['OrderBy'],
        'engineerIds': json['EngineerIds'] == null ? undefined : json['EngineerIds'],
        'classIds': json['ClassIds'] == null ? undefined : json['ClassIds'],
        'areaIds': json['AreaIds'] == null ? undefined : json['AreaIds'],
        'tradeIds': json['TradeIds'] == null ? undefined : json['TradeIds'],
        'searchTerm': json['SearchTerm'] == null ? undefined : json['SearchTerm'],
        'includeInactive': json['IncludeInactive'] == null ? undefined : json['IncludeInactive'],
        'pageIndex': json['PageIndex'] == null ? undefined : json['PageIndex'],
        'pageSize': json['PageSize'] == null ? undefined : json['PageSize'],
        'tenantId': json['TenantId'],
    };
}

export function JoblogicAPIModelsSearchEngineerTeamRequestToJSON(json: any): JoblogicAPIModelsSearchEngineerTeamRequest {
    return JoblogicAPIModelsSearchEngineerTeamRequestToJSONTyped(json, false);
}

export function JoblogicAPIModelsSearchEngineerTeamRequestToJSONTyped(value?: JoblogicAPIModelsSearchEngineerTeamRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'OrderBy': value['orderBy'],
        'EngineerIds': value['engineerIds'],
        'ClassIds': value['classIds'],
        'AreaIds': value['areaIds'],
        'TradeIds': value['tradeIds'],
        'SearchTerm': value['searchTerm'],
        'IncludeInactive': value['includeInactive'],
        'PageIndex': value['pageIndex'],
        'PageSize': value['pageSize'],
        'TenantId': value['tenantId'],
    };
}

