/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobLogicMicroserviceCoreContractServiceTypeFrequency } from './JobLogicMicroserviceCoreContractServiceTypeFrequency';
import {
    JobLogicMicroserviceCoreContractServiceTypeFrequencyFromJSON,
    JobLogicMicroserviceCoreContractServiceTypeFrequencyFromJSONTyped,
    JobLogicMicroserviceCoreContractServiceTypeFrequencyToJSON,
    JobLogicMicroserviceCoreContractServiceTypeFrequencyToJSONTyped,
} from './JobLogicMicroserviceCoreContractServiceTypeFrequency';
import type { JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAssetServiceTypeTask } from './JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAssetServiceTypeTask';
import {
    JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAssetServiceTypeTaskFromJSON,
    JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAssetServiceTypeTaskFromJSONTyped,
    JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAssetServiceTypeTaskToJSON,
    JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAssetServiceTypeTaskToJSONTyped,
} from './JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAssetServiceTypeTask';
import type { JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAssetServiceKitTask } from './JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAssetServiceKitTask';
import {
    JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAssetServiceKitTaskFromJSON,
    JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAssetServiceKitTaskFromJSONTyped,
    JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAssetServiceKitTaskToJSON,
    JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAssetServiceKitTaskToJSONTyped,
} from './JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAssetServiceKitTask';

/**
 * 
 * @export
 * @interface JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAsset
 */
export interface JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAsset {
    /**
     * 
     * @type {number}
     * @memberof JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAsset
     */
    assetId?: number;
    /**
     * 
     * @type {number}
     * @memberof JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAsset
     */
    siteId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAsset
     */
    jobAssetId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAsset
     */
    jobAssetClassId?: number | null;
    /**
     * 
     * @type {JobLogicMicroserviceCoreContractServiceTypeFrequency}
     * @memberof JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAsset
     */
    frequency?: JobLogicMicroserviceCoreContractServiceTypeFrequency;
    /**
     * 
     * @type {string}
     * @memberof JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAsset
     */
    jobAssetNotes?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAsset
     */
    jobActionRequiredNotes?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAsset
     */
    jobAssetComplete?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAsset
     */
    completionDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAsset
     */
    jobAssetServiceTypeId?: string | null;
    /**
     * 
     * @type {number}
     * @memberof JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAsset
     */
    jobAssetDuration?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAsset
     */
    isServiceTypeChanged?: boolean;
    /**
     * 
     * @type {Array<JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAssetServiceTypeTask>}
     * @memberof JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAsset
     */
    jobAssetServiceTypeTasks?: Array<JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAssetServiceTypeTask> | null;
    /**
     * 
     * @type {number}
     * @memberof JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAsset
     */
    assetConditionId?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAsset
     */
    isMandatory?: boolean;
    /**
     * 
     * @type {number}
     * @memberof JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAsset
     */
    serviceOrder?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAsset
     */
    isServiceKitChanged?: boolean;
    /**
     * 
     * @type {string}
     * @memberof JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAsset
     */
    jobAssetServiceKitId?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAsset
     */
    pPMStartDate?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAsset
     */
    pPMEndDate?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAsset
     */
    pPMServiceFee?: number | null;
    /**
     * 
     * @type {Array<JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAssetServiceKitTask>}
     * @memberof JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAsset
     */
    jobAssetServiceKitTasks?: Array<JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAssetServiceKitTask> | null;
    /**
     * 
     * @type {boolean}
     * @memberof JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAsset
     */
    isNew?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAsset
     */
    isDeleted?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAsset
     */
    isEdited?: boolean;
}

/**
 * Check if a given object implements the JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAsset interface.
 */
export function instanceOfJobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAsset(value: object): value is JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAsset {
    return true;
}

export function JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAssetFromJSON(json: any): JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAsset {
    return JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAssetFromJSONTyped(json, false);
}

export function JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAssetFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAsset {
    if (json == null) {
        return json;
    }
    return {
        
        'assetId': json['AssetId'] == null ? undefined : json['AssetId'],
        'siteId': json['SiteId'] == null ? undefined : json['SiteId'],
        'jobAssetId': json['JobAssetId'] == null ? undefined : json['JobAssetId'],
        'jobAssetClassId': json['JobAssetClassId'] == null ? undefined : json['JobAssetClassId'],
        'frequency': json['Frequency'] == null ? undefined : JobLogicMicroserviceCoreContractServiceTypeFrequencyFromJSON(json['Frequency']),
        'jobAssetNotes': json['JobAssetNotes'] == null ? undefined : json['JobAssetNotes'],
        'jobActionRequiredNotes': json['JobActionRequiredNotes'] == null ? undefined : json['JobActionRequiredNotes'],
        'jobAssetComplete': json['JobAssetComplete'] == null ? undefined : json['JobAssetComplete'],
        'completionDate': json['CompletionDate'] == null ? undefined : (new Date(json['CompletionDate'])),
        'jobAssetServiceTypeId': json['JobAssetServiceTypeId'] == null ? undefined : json['JobAssetServiceTypeId'],
        'jobAssetDuration': json['JobAssetDuration'] == null ? undefined : json['JobAssetDuration'],
        'isServiceTypeChanged': json['IsServiceTypeChanged'] == null ? undefined : json['IsServiceTypeChanged'],
        'jobAssetServiceTypeTasks': json['JobAssetServiceTypeTasks'] == null ? undefined : ((json['JobAssetServiceTypeTasks'] as Array<any>).map(JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAssetServiceTypeTaskFromJSON)),
        'assetConditionId': json['AssetConditionId'] == null ? undefined : json['AssetConditionId'],
        'isMandatory': json['IsMandatory'] == null ? undefined : json['IsMandatory'],
        'serviceOrder': json['ServiceOrder'] == null ? undefined : json['ServiceOrder'],
        'isServiceKitChanged': json['IsServiceKitChanged'] == null ? undefined : json['IsServiceKitChanged'],
        'jobAssetServiceKitId': json['JobAssetServiceKitId'] == null ? undefined : json['JobAssetServiceKitId'],
        'pPMStartDate': json['PPMStartDate'] == null ? undefined : (new Date(json['PPMStartDate'])),
        'pPMEndDate': json['PPMEndDate'] == null ? undefined : (new Date(json['PPMEndDate'])),
        'pPMServiceFee': json['PPMServiceFee'] == null ? undefined : json['PPMServiceFee'],
        'jobAssetServiceKitTasks': json['JobAssetServiceKitTasks'] == null ? undefined : ((json['JobAssetServiceKitTasks'] as Array<any>).map(JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAssetServiceKitTaskFromJSON)),
        'isNew': json['IsNew'] == null ? undefined : json['IsNew'],
        'isDeleted': json['IsDeleted'] == null ? undefined : json['IsDeleted'],
        'isEdited': json['IsEdited'] == null ? undefined : json['IsEdited'],
    };
}

export function JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAssetToJSON(json: any): JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAsset {
    return JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAssetToJSONTyped(json, false);
}

export function JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAssetToJSONTyped(value?: JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAsset | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'AssetId': value['assetId'],
        'SiteId': value['siteId'],
        'JobAssetId': value['jobAssetId'],
        'JobAssetClassId': value['jobAssetClassId'],
        'Frequency': JobLogicMicroserviceCoreContractServiceTypeFrequencyToJSON(value['frequency']),
        'JobAssetNotes': value['jobAssetNotes'],
        'JobActionRequiredNotes': value['jobActionRequiredNotes'],
        'JobAssetComplete': value['jobAssetComplete'],
        'CompletionDate': value['completionDate'] == null ? value['completionDate'] : value['completionDate'].toISOString(),
        'JobAssetServiceTypeId': value['jobAssetServiceTypeId'],
        'JobAssetDuration': value['jobAssetDuration'],
        'IsServiceTypeChanged': value['isServiceTypeChanged'],
        'JobAssetServiceTypeTasks': value['jobAssetServiceTypeTasks'] == null ? undefined : ((value['jobAssetServiceTypeTasks'] as Array<any>).map(JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAssetServiceTypeTaskToJSON)),
        'AssetConditionId': value['assetConditionId'],
        'IsMandatory': value['isMandatory'],
        'ServiceOrder': value['serviceOrder'],
        'IsServiceKitChanged': value['isServiceKitChanged'],
        'JobAssetServiceKitId': value['jobAssetServiceKitId'],
        'PPMStartDate': value['pPMStartDate'] == null ? value['pPMStartDate'] : value['pPMStartDate'].toISOString(),
        'PPMEndDate': value['pPMEndDate'] == null ? value['pPMEndDate'] : value['pPMEndDate'].toISOString(),
        'PPMServiceFee': value['pPMServiceFee'],
        'JobAssetServiceKitTasks': value['jobAssetServiceKitTasks'] == null ? undefined : ((value['jobAssetServiceKitTasks'] as Array<any>).map(JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAssetServiceKitTaskToJSON)),
        'IsNew': value['isNew'],
        'IsDeleted': value['isDeleted'],
        'IsEdited': value['isEdited'],
    };
}

