/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceLineModel } from './JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceLineModel';
import {
    JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceLineModelFromJSON,
    JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceLineModelFromJSONTyped,
    JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceLineModelToJSON,
    JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceLineModelToJSONTyped,
} from './JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceLineModel';
import type { JobLogicMicroserviceCoreContractContractPurchaseOrderInvoiceType } from './JobLogicMicroserviceCoreContractContractPurchaseOrderInvoiceType';
import {
    JobLogicMicroserviceCoreContractContractPurchaseOrderInvoiceTypeFromJSON,
    JobLogicMicroserviceCoreContractContractPurchaseOrderInvoiceTypeFromJSONTyped,
    JobLogicMicroserviceCoreContractContractPurchaseOrderInvoiceTypeToJSON,
    JobLogicMicroserviceCoreContractContractPurchaseOrderInvoiceTypeToJSONTyped,
} from './JobLogicMicroserviceCoreContractContractPurchaseOrderInvoiceType';

/**
 * 
 * @export
 * @interface JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceModel
 */
export interface JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceModel {
    /**
     * 
     * @type {string}
     * @memberof JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceModel
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceModel
     */
    purchaseOrderId?: string;
    /**
     * 
     * @type {string}
     * @memberof JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceModel
     */
    invoiceNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceModel
     */
    reference?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceModel
     */
    isFinalInvoice?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceModel
     */
    createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceModel
     */
    azureBlobReference?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceModel
     */
    date?: Date;
    /**
     * 
     * @type {JobLogicMicroserviceCoreContractContractPurchaseOrderInvoiceType}
     * @memberof JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceModel
     */
    type?: JobLogicMicroserviceCoreContractContractPurchaseOrderInvoiceType;
    /**
     * 
     * @type {Array<JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsg ContractPurchaseOrderInvoiceLineModel>}
     * @memberof JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceModel
     */
    invoiceLines?: Array<JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceLineModel> | null;
}



/**
 * Check if a given object implements the JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceModel interface.
 */
export function instanceOfJobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceModel(value: object): value is JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceModel {
    return true;
}

export function JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceModelFromJSON(json: any): JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceModel {
    return JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceModelFromJSONTyped(json, false);
}

export function JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['Id'] == null ? undefined : json['Id'],
        'purchaseOrderId': json['PurchaseOrderId'] == null ? undefined : json['PurchaseOrderId'],
        'invoiceNumber': json['InvoiceNumber'] == null ? undefined : json['InvoiceNumber'],
        'reference': json['Reference'] == null ? undefined : json['Reference'],
        'isFinalInvoice': json['IsFinalInvoice'] == null ? undefined : json['IsFinalInvoice'],
        'createdAt': json['CreatedAt'] == null ? undefined : (new Date(json['CreatedAt'])),
        'azureBlobReference': json['AzureBlobReference'] == null ? undefined : json['AzureBlobReference'],
        'date': json['Date'] == null ? undefined : (new Date(json['Date'])),
        'type': json['Type'] == null ? undefined : JobLogicMicroserviceCoreContractContractPurchaseOrderInvoiceTypeFromJSON(json['Type']),
        'invoiceLines': json['InvoiceLines'] == null ? undefined : ((json['InvoiceLines'] as Array<any>).map(JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceLineModelFromJSON)),
    };
}

export function JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceModelToJSON(json: any): JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceModel {
    return JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceModelToJSONTyped(json, false);
}

export function JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceModelToJSONTyped(value?: JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Id': value['id'],
        'PurchaseOrderId': value['purchaseOrderId'],
        'InvoiceNumber': value['invoiceNumber'],
        'Reference': value['reference'],
        'IsFinalInvoice': value['isFinalInvoice'],
        'CreatedAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'AzureBlobReference': value['azureBlobReference'],
        'Date': value['date'] == null ? value['date'] : value['date'].toISOString(),
        'Type': JobLogicMicroserviceCoreContractContractPurchaseOrderInvoiceTypeToJSON(value['type']),
        'InvoiceLines': value['invoiceLines'] == null ? undefined : ((value['invoiceLines'] as Array<any>).map(JobLogicMicroserviceCoreContractGetContractPurchaseOrderDetailByIdMsgContractPurchaseOrderInvoiceLineModelToJSON)),
    };
}

