/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobLogicMicroserviceDocGenContractDocumentTemplateType } from './JobLogicMicroserviceDocGenContractDocumentTemplateType';
import {
    JobLogicMicroserviceDocGenContractDocumentTemplateTypeFromJSON,
    JobLogicMicroserviceDocGenContractDocumentTemplateTypeFromJSONTyped,
    JobLogicMicroserviceDocGenContractDocumentTemplateTypeToJSON,
    JobLogicMicroserviceDocGenContractDocumentTemplateTypeToJSONTyped,
} from './JobLogicMicroserviceDocGenContractDocumentTemplateType';

/**
 * 
 * @export
 * @interface JoblogicAPIModelsSubcontractorPODocumentTemplateModel
 */
export interface JoblogicAPIModelsSubcontractorPODocumentTemplateModel {
    /**
     * 
     * @type {JobLogicMicroserviceDocGenContractDocumentTemplateType}
     * @memberof JoblogicAPIModelsSubcontractorPODocumentTemplateModel
     */
    type?: JobLogicMicroserviceDocGenContractDocumentTemplateType;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsSubcontractorPODocumentTemplateModel
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsSubcontractorPODocumentTemplateModel
     */
    fileName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsSubcontractorPODocumentTemplateModel
     */
    uploadedBy?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof JoblogicAPIModelsSubcontractorPODocumentTemplateModel
     */
    isDefault?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof JoblogicAPIModelsSubcontractorPODocumentTemplateModel
     */
    isSystemTemplate?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof JoblogicAPIModelsSubcontractorPODocumentTemplateModel
     */
    active?: boolean;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsSubcontractorPODocumentTemplateModel
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsSubcontractorPODocumentTemplateModel
     */
    id?: string;
}



/**
 * Check if a given object implements the JoblogicAPIModelsSubcontractorPODocumentTemplateModel interface.
 */
export function instanceOfJoblogicAPIModelsSubcontractorPODocumentTemplateModel(value: object): value is JoblogicAPIModelsSubcontractorPODocumentTemplateModel {
    return true;
}

export function JoblogicAPIModelsSubcontractorPODocumentTemplateModelFromJSON(json: any): JoblogicAPIModelsSubcontractorPODocumentTemplateModel {
    return JoblogicAPIModelsSubcontractorPODocumentTemplateModelFromJSONTyped(json, false);
}

export function JoblogicAPIModelsSubcontractorPODocumentTemplateModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsSubcontractorPODocumentTemplateModel {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['Type'] == null ? undefined : JobLogicMicroserviceDocGenContractDocumentTemplateTypeFromJSON(json['Type']),
        'description': json['Description'] == null ? undefined : json['Description'],
        'fileName': json['FileName'] == null ? undefined : json['FileName'],
        'uploadedBy': json['UploadedBy'] == null ? undefined : json['UploadedBy'],
        'isDefault': json['IsDefault'] == null ? undefined : json['IsDefault'],
        'isSystemTemplate': json['IsSystemTemplate'] == null ? undefined : json['IsSystemTemplate'],
        'active': json['Active'] == null ? undefined : json['Active'],
        'title': json['Title'] == null ? undefined : json['Title'],
        'id': json['Id'] == null ? undefined : json['Id'],
    };
}

export function JoblogicAPIModelsSubcontractorPODocumentTemplateModelToJSON(json: any): JoblogicAPIModelsSubcontractorPODocumentTemplateModel {
    return JoblogicAPIModelsSubcontractorPODocumentTemplateModelToJSONTyped(json, false);
}

export function JoblogicAPIModelsSubcontractorPODocumentTemplateModelToJSONTyped(value?: JoblogicAPIModelsSubcontractorPODocumentTemplateModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Type': JobLogicMicroserviceDocGenContractDocumentTemplateTypeToJSON(value['type']),
        'Description': value['description'],
        'FileName': value['fileName'],
        'UploadedBy': value['uploadedBy'],
        'IsDefault': value['isDefault'],
        'IsSystemTemplate': value['isSystemTemplate'],
        'Active': value['active'],
        'Title': value['title'],
        'Id': value['id'],
    };
}

