/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobLogicMicroserviceCoreContractNonProductiveTimeStart } from './JobLogicMicroserviceCoreContractNonProductiveTimeStart';
import {
    JobLogicMicroserviceCoreContractNonProductiveTimeStartFromJSON,
    JobLogicMicroserviceCoreContractNonProductiveTimeStartFromJSONTyped,
    JobLogicMicroserviceCoreContractNonProductiveTimeStartToJSON,
    JobLogicMicroserviceCoreContractNonProductiveTimeStartToJSONTyped,
} from './JobLogicMicroserviceCoreContractNonProductiveTimeStart';
import type { JobLogicMicroserviceCoreContractNonProductiveTimeEnd } from './JobLogicMicroserviceCoreContractNonProductiveTimeEnd';
import {
    JobLogicMicroserviceCoreContractNonProductiveTimeEndFromJSON,
    JobLogicMicroserviceCoreContractNonProductiveTimeEndFromJSONTyped,
    JobLogicMicroserviceCoreContractNonProductiveTimeEndToJSON,
    JobLogicMicroserviceCoreContractNonProductiveTimeEndToJSONTyped,
} from './JobLogicMicroserviceCoreContractNonProductiveTimeEnd';
import type { JoblogicAPITimesheetTypeRequest } from './JoblogicAPITimesheetTypeRequest';
import {
    JoblogicAPITimesheetTypeRequestFromJSON,
    JoblogicAPITimesheetTypeRequestFromJSONTyped,
    JoblogicAPITimesheetTypeRequestToJSON,
    JoblogicAPITimesheetTypeRequestToJSONTyped,
} from './JoblogicAPITimesheetTypeRequest';

/**
 * 
 * @export
 * @interface JoblogicAPIModelsUpdateTimeRequest
 */
export interface JoblogicAPIModelsUpdateTimeRequest {
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsUpdateTimeRequest
     */
    uniqueId: string;
    /**
     * 
     * @type {JoblogicAPITimesheetTypeRequest}
     * @memberof JoblogicAPIModelsUpdateTimeRequest
     */
    timesheetType: JoblogicAPITimesheetTypeRequest;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsUpdateTimeRequest
     */
    nonProductiveTypeId?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof JoblogicAPIModelsUpdateTimeRequest
     */
    travelStart?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof JoblogicAPIModelsUpdateTimeRequest
     */
    labourStart: Date;
    /**
     * 
     * @type {Date}
     * @memberof JoblogicAPIModelsUpdateTimeRequest
     */
    labourEnd?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsUpdateTimeRequest
     */
    mileage?: number;
    /**
     * 
     * @type {JobLogicMicroserviceCoreContractNonProductiveTimeStart}
     * @memberof JoblogicAPIModelsUpdateTimeRequest
     */
    startTime?: JobLogicMicroserviceCoreContractNonProductiveTimeStart;
    /**
     * 
     * @type {JobLogicMicroserviceCoreContractNonProductiveTimeEnd}
     * @memberof JoblogicAPIModelsUpdateTimeRequest
     */
    endTime?: JobLogicMicroserviceCoreContractNonProductiveTimeEnd;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsUpdateTimeRequest
     */
    reason?: string | null;
    /**
     * Contractor Id in Joblogic
     * @type {string}
     * @memberof JoblogicAPIModelsUpdateTimeRequest
     */
    tenantId: string;
}



/**
 * Check if a given object implements the JoblogicAPIModelsUpdateTimeRequest interface.
 */
export function instanceOfJoblogicAPIModelsUpdateTimeRequest(value: object): value is JoblogicAPIModelsUpdateTimeRequest {
    if (!('uniqueId' in value) || value['uniqueId'] === undefined) return false;
    if (!('timesheetType' in value) || value['timesheetType'] === undefined) return false;
    if (!('labourStart' in value) || value['labourStart'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    return true;
}

export function JoblogicAPIModelsUpdateTimeRequestFromJSON(json: any): JoblogicAPIModelsUpdateTimeRequest {
    return JoblogicAPIModelsUpdateTimeRequestFromJSONTyped(json, false);
}

export function JoblogicAPIModelsUpdateTimeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsUpdateTimeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'uniqueId': json['UniqueId'],
        'timesheetType': JoblogicAPITimesheetTypeRequestFromJSON(json['TimesheetType']),
        'nonProductiveTypeId': json['NonProductiveTypeId'] == null ? undefined : json['NonProductiveTypeId'],
        'travelStart': json['TravelStart'] == null ? undefined : (new Date(json['TravelStart'])),
        'labourStart': (new Date(json['LabourStart'])),
        'labourEnd': json['LabourEnd'] == null ? undefined : (new Date(json['LabourEnd'])),
        'mileage': json['Mileage'] == null ? undefined : json['Mileage'],
        'startTime': json['StartTime'] == null ? undefined : JobLogicMicroserviceCoreContractNonProductiveTimeStartFromJSON(json['StartTime']),
        'endTime': json['EndTime'] == null ? undefined : JobLogicMicroserviceCoreContractNonProductiveTimeEndFromJSON(json['EndTime']),
        'reason': json['Reason'] == null ? undefined : json['Reason'],
        'tenantId': json['TenantId'],
    };
}

export function JoblogicAPIModelsUpdateTimeRequestToJSON(json: any): JoblogicAPIModelsUpdateTimeRequest {
    return JoblogicAPIModelsUpdateTimeRequestToJSONTyped(json, false);
}

export function JoblogicAPIModelsUpdateTimeRequestToJSONTyped(value?: JoblogicAPIModelsUpdateTimeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'UniqueId': value['uniqueId'],
        'TimesheetType': JoblogicAPITimesheetTypeRequestToJSON(value['timesheetType']),
        'NonProductiveTypeId': value['nonProductiveTypeId'],
        'TravelStart': value['travelStart'] == null ? value['travelStart'] : value['travelStart'].toISOString(),
        'LabourStart': value['labourStart'].toISOString(),
        'LabourEnd': value['labourEnd'] == null ? value['labourEnd'] : value['labourEnd'].toISOString(),
        'Mileage': value['mileage'],
        'StartTime': JobLogicMicroserviceCoreContractNonProductiveTimeStartToJSON(value['startTime']),
        'EndTime': JobLogicMicroserviceCoreContractNonProductiveTimeEndToJSON(value['endTime']),
        'Reason': value['reason'],
        'TenantId': value['tenantId'],
    };
}

