/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JoblogicAPIModelsTaskLineResponse } from './JoblogicAPIModelsTaskLineResponse';
import {
    JoblogicAPIModelsTaskLineResponseFromJSON,
    JoblogicAPIModelsTaskLineResponseFromJSONTyped,
    JoblogicAPIModelsTaskLineResponseToJSON,
    JoblogicAPIModelsTaskLineResponseToJSONTyped,
} from './JoblogicAPIModelsTaskLineResponse';

/**
 * 
 * @export
 * @interface JoblogicAPIModelsTaskItemResponse
 */
export interface JoblogicAPIModelsTaskItemResponse {
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsTaskItemResponse
     */
    id?: string;
    /**
     * 
     * @type {boolean}
     * @memberof JoblogicAPIModelsTaskItemResponse
     */
    active?: boolean;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsTaskItemResponse
     */
    task?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsTaskItemResponse
     */
    summary?: string | null;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsTaskItemResponse
     */
    totalTask?: number;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsTaskItemResponse
     */
    totalDuration?: number;
    /**
     * 
     * @type {Array<JoblogicAPIModelsTaskLineResponse>}
     * @memberof JoblogicAPIModelsTaskItemResponse
     */
    subTasks?: Array<JoblogicAPIModelsTaskLineResponse> | null;
}

/**
 * Check if a given object implements the JoblogicAPIModelsTaskItemResponse interface.
 */
export function instanceOfJoblogicAPIModelsTaskItemResponse(value: object): value is JoblogicAPIModelsTaskItemResponse {
    return true;
}

export function JoblogicAPIModelsTaskItemResponseFromJSON(json: any): JoblogicAPIModelsTaskItemResponse {
    return JoblogicAPIModelsTaskItemResponseFromJSONTyped(json, false);
}

export function JoblogicAPIModelsTaskItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsTaskItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['Id'] == null ? undefined : json['Id'],
        'active': json['Active'] == null ? undefined : json['Active'],
        'task': json['Task'] == null ? undefined : json['Task'],
        'summary': json['Summary'] == null ? undefined : json['Summary'],
        'totalTask': json['TotalTask'] == null ? undefined : json['TotalTask'],
        'totalDuration': json['TotalDuration'] == null ? undefined : json['TotalDuration'],
        'subTasks': json['SubTasks'] == null ? undefined : ((json['SubTasks'] as Array<any>).map(JoblogicAPIModelsTaskLineResponseFromJSON)),
    };
}

export function JoblogicAPIModelsTaskItemResponseToJSON(json: any): JoblogicAPIModelsTaskItemResponse {
    return JoblogicAPIModelsTaskItemResponseToJSONTyped(json, false);
}

export function JoblogicAPIModelsTaskItemResponseToJSONTyped(value?: JoblogicAPIModelsTaskItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Id': value['id'],
        'Active': value['active'],
        'Task': value['task'],
        'Summary': value['summary'],
        'TotalTask': value['totalTask'],
        'TotalDuration': value['totalDuration'],
        'SubTasks': value['subTasks'] == null ? undefined : ((value['subTasks'] as Array<any>).map(JoblogicAPIModelsTaskLineResponseToJSON)),
    };
}

