/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JoblogicAPIModelsGetSubcontractorResponseTrade
 */
export interface JoblogicAPIModelsGetSubcontractorResponseTrade {
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsGetSubcontractorResponseTrade
     */
    uniqueId?: string;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsGetSubcontractorResponseTrade
     */
    description?: string | null;
}

/**
 * Check if a given object implements the JoblogicAPIModelsGetSubcontractorResponseTrade interface.
 */
export function instanceOfJoblogicAPIModelsGetSubcontractorResponseTrade(value: object): value is JoblogicAPIModelsGetSubcontractorResponseTrade {
    return true;
}

export function JoblogicAPIModelsGetSubcontractorResponseTradeFromJSON(json: any): JoblogicAPIModelsGetSubcontractorResponseTrade {
    return JoblogicAPIModelsGetSubcontractorResponseTradeFromJSONTyped(json, false);
}

export function JoblogicAPIModelsGetSubcontractorResponseTradeFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsGetSubcontractorResponseTrade {
    if (json == null) {
        return json;
    }
    return {
        
        'uniqueId': json['UniqueId'] == null ? undefined : json['UniqueId'],
        'description': json['Description'] == null ? undefined : json['Description'],
    };
}

export function JoblogicAPIModelsGetSubcontractorResponseTradeToJSON(json: any): JoblogicAPIModelsGetSubcontractorResponseTrade {
    return JoblogicAPIModelsGetSubcontractorResponseTradeToJSONTyped(json, false);
}

export function JoblogicAPIModelsGetSubcontractorResponseTradeToJSONTyped(value?: JoblogicAPIModelsGetSubcontractorResponseTrade | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'UniqueId': value['uniqueId'],
        'Description': value['description'],
    };
}

