/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JoblogicAPIModelsSearchNoteTagResponse } from './JoblogicAPIModelsSearchNoteTagResponse';
import {
    JoblogicAPIModelsSearchNoteTagResponseFromJSON,
    JoblogicAPIModelsSearchNoteTagResponseFromJSONTyped,
    JoblogicAPIModelsSearchNoteTagResponseToJSON,
    JoblogicAPIModelsSearchNoteTagResponseToJSONTyped,
} from './JoblogicAPIModelsSearchNoteTagResponse';
import type { JobLogicMicroserviceCoreContractNoteVisibilityOption } from './JobLogicMicroserviceCoreContractNoteVisibilityOption';
import {
    JobLogicMicroserviceCoreContractNoteVisibilityOptionFromJSON,
    JobLogicMicroserviceCoreContractNoteVisibilityOptionFromJSONTyped,
    JobLogicMicroserviceCoreContractNoteVisibilityOptionToJSON,
    JobLogicMicroserviceCoreContractNoteVisibilityOptionToJSONTyped,
} from './JobLogicMicroserviceCoreContractNoteVisibilityOption';
import type { JoblogicAPIModelsSearchNoteAttachmentResponse } from './JoblogicAPIModelsSearchNoteAttachmentResponse';
import {
    JoblogicAPIModelsSearchNoteAttachmentResponseFromJSON,
    JoblogicAPIModelsSearchNoteAttachmentResponseFromJSONTyped,
    JoblogicAPIModelsSearchNoteAttachmentResponseToJSON,
    JoblogicAPIModelsSearchNoteAttachmentResponseToJSONTyped,
} from './JoblogicAPIModelsSearchNoteAttachmentResponse';

/**
 * 
 * @export
 * @interface JoblogicAPIModelsSearchNoteItemResponse
 */
export interface JoblogicAPIModelsSearchNoteItemResponse {
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsSearchNoteItemResponse
     */
    noteText?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof JoblogicAPIModelsSearchNoteItemResponse
     */
    dateAdded?: Date;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsSearchNoteItemResponse
     */
    author?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsSearchNoteItemResponse
     */
    modifiedByUser?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof JoblogicAPIModelsSearchNoteItemResponse
     */
    modifiedDate?: Date;
    /**
     * 
     * @type {JobLogicMicroserviceCoreContractNoteVisibilityOption}
     * @memberof JoblogicAPIModelsSearchNoteItemResponse
     */
    noteVisibility?: JobLogicMicroserviceCoreContractNoteVisibilityOption;
    /**
     * 
     * @type {boolean}
     * @memberof JoblogicAPIModelsSearchNoteItemResponse
     */
    isPinned?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof JoblogicAPIModelsSearchNoteItemResponse
     */
    pinnedDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsSearchNoteItemResponse
     */
    uniqueId?: string;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsSearchNoteItemResponse
     */
    id?: number;
    /**
     * 
     * @type {Array<JoblogicAPIModelsSearchNoteAttachmentResponse>}
     * @memberof JoblogicAPIModelsSearchNoteItemResponse
     */
    attachments?: Array<JoblogicAPIModelsSearchNoteAttachmentResponse> | null;
    /**
     * 
     * @type {Array<JoblogicAPIModelsSearchNoteTagResponse>}
     * @memberof JoblogicAPIModelsSearchNoteItemResponse
     */
    tags?: Array<JoblogicAPIModelsSearchNoteTagResponse> | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsSearchNoteItemResponse
     */
    toDoId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsSearchNoteItemResponse
     */
    entityId?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof JoblogicAPIModelsSearchNoteItemResponse
     */
    isFakeNote?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof JoblogicAPIModelsSearchNoteItemResponse
     */
    isFrozen?: boolean;
}



/**
 * Check if a given object implements the JoblogicAPIModelsSearchNoteItemResponse interface.
 */
export function instanceOfJoblogicAPIModelsSearchNoteItemResponse(value: object): value is JoblogicAPIModelsSearchNoteItemResponse {
    return true;
}

export function JoblogicAPIModelsSearchNoteItemResponseFromJSON(json: any): JoblogicAPIModelsSearchNoteItemResponse {
    return JoblogicAPIModelsSearchNoteItemResponseFromJSONTyped(json, false);
}

export function JoblogicAPIModelsSearchNoteItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsSearchNoteItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'noteText': json['NoteText'] == null ? undefined : json['NoteText'],
        'dateAdded': json['DateAdded'] == null ? undefined : (new Date(json['DateAdded'])),
        'author': json['Author'] == null ? undefined : json['Author'],
        'modifiedByUser': json['ModifiedByUser'] == null ? undefined : json['ModifiedByUser'],
        'modifiedDate': json['ModifiedDate'] == null ? undefined : (new Date(json['ModifiedDate'])),
        'noteVisibility': json['NoteVisibility'] == null ? undefined : JobLogicMicroserviceCoreContractNoteVisibilityOptionFromJSON(json['NoteVisibility']),
        'isPinned': json['IsPinned'] == null ? undefined : json['IsPinned'],
        'pinnedDate': json['PinnedDate'] == null ? undefined : (new Date(json['PinnedDate'])),
        'uniqueId': json['UniqueId'] == null ? undefined : json['UniqueId'],
        'id': json['Id'] == null ? undefined : json['Id'],
        'attachments': json['Attachments'] == null ? undefined : ((json['Attachments'] as Array<any>).map(JoblogicAPIModelsSearchNoteAttachmentResponseFromJSON)),
        'tags': json['Tags'] == null ? undefined : ((json['Tags'] as Array<any>).map(JoblogicAPIModelsSearchNoteTagResponseFromJSON)),
        'toDoId': json['ToDoId'] == null ? undefined : json['ToDoId'],
        'entityId': json['EntityId'] == null ? undefined : json['EntityId'],
        'isFakeNote': json['IsFakeNote'] == null ? undefined : json['IsFakeNote'],
        'isFrozen': json['IsFrozen'] == null ? undefined : json['IsFrozen'],
    };
}

export function JoblogicAPIModelsSearchNoteItemResponseToJSON(json: any): JoblogicAPIModelsSearchNoteItemResponse {
    return JoblogicAPIModelsSearchNoteItemResponseToJSONTyped(json, false);
}

export function JoblogicAPIModelsSearchNoteItemResponseToJSONTyped(value?: JoblogicAPIModelsSearchNoteItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'NoteText': value['noteText'],
        'DateAdded': value['dateAdded'] == null ? value['dateAdded'] : value['dateAdded'].toISOString(),
        'Author': value['author'],
        'ModifiedByUser': value['modifiedByUser'],
        'ModifiedDate': value['modifiedDate'] == null ? value['modifiedDate'] : value['modifiedDate'].toISOString(),
        'NoteVisibility': JobLogicMicroserviceCoreContractNoteVisibilityOptionToJSON(value['noteVisibility']),
        'IsPinned': value['isPinned'],
        'PinnedDate': value['pinnedDate'] == null ? value['pinnedDate'] : value['pinnedDate'].toISOString(),
        'UniqueId': value['uniqueId'],
        'Id': value['id'],
        'Attachments': value['attachments'] == null ? undefined : ((value['attachments'] as Array<any>).map(JoblogicAPIModelsSearchNoteAttachmentResponseToJSON)),
        'Tags': value['tags'] == null ? undefined : ((value['tags'] as Array<any>).map(JoblogicAPIModelsSearchNoteTagResponseToJSON)),
        'ToDoId': value['toDoId'],
        'EntityId': value['entityId'],
        'IsFakeNote': value['isFakeNote'],
        'IsFrozen': value['isFrozen'],
    };
}

