/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JoblogicAPIModelsJobCategoryItemResponse } from './JoblogicAPIModelsJobCategoryItemResponse';
import {
    JoblogicAPIModelsJobCategoryItemResponseFromJSON,
    JoblogicAPIModelsJobCategoryItemResponseFromJSONTyped,
    JoblogicAPIModelsJobCategoryItemResponseToJSON,
    JoblogicAPIModelsJobCategoryItemResponseToJSONTyped,
} from './JoblogicAPIModelsJobCategoryItemResponse';

/**
 * 
 * @export
 * @interface JoblogicAPIModelsSearchJobCategoryResponse
 */
export interface JoblogicAPIModelsSearchJobCategoryResponse {
    /**
     * 
     * @type {Array<JoblogicAPIModelsJobCategoryItemResponse>}
     * @memberof JoblogicAPIModelsSearchJobCategoryResponse
     */
    items?: Array<JoblogicAPIModelsJobCategoryItemResponse> | null;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsSearchJobCategoryResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsSearchJobCategoryResponse
     */
    pageIndex?: number;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsSearchJobCategoryResponse
     */
    pageSize?: number;
}

/**
 * Check if a given object implements the JoblogicAPIModelsSearchJobCategoryResponse interface.
 */
export function instanceOfJoblogicAPIModelsSearchJobCategoryResponse(value: object): value is JoblogicAPIModelsSearchJobCategoryResponse {
    return true;
}

export function JoblogicAPIModelsSearchJobCategoryResponseFromJSON(json: any): JoblogicAPIModelsSearchJobCategoryResponse {
    return JoblogicAPIModelsSearchJobCategoryResponseFromJSONTyped(json, false);
}

export function JoblogicAPIModelsSearchJobCategoryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsSearchJobCategoryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['Items'] == null ? undefined : ((json['Items'] as Array<any>).map(JoblogicAPIModelsJobCategoryItemResponseFromJSON)),
        'totalCount': json['TotalCount'] == null ? undefined : json['TotalCount'],
        'pageIndex': json['PageIndex'] == null ? undefined : json['PageIndex'],
        'pageSize': json['PageSize'] == null ? undefined : json['PageSize'],
    };
}

export function JoblogicAPIModelsSearchJobCategoryResponseToJSON(json: any): JoblogicAPIModelsSearchJobCategoryResponse {
    return JoblogicAPIModelsSearchJobCategoryResponseToJSONTyped(json, false);
}

export function JoblogicAPIModelsSearchJobCategoryResponseToJSONTyped(value?: JoblogicAPIModelsSearchJobCategoryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(JoblogicAPIModelsJobCategoryItemResponseToJSON)),
        'TotalCount': value['totalCount'],
        'PageIndex': value['pageIndex'],
        'PageSize': value['pageSize'],
    };
}

