/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobLogicMicroserviceCoreContractPriceCalculationType } from './JobLogicMicroserviceCoreContractPriceCalculationType';
import {
    JobLogicMicroserviceCoreContractPriceCalculationTypeFromJSON,
    JobLogicMicroserviceCoreContractPriceCalculationTypeFromJSONTyped,
    JobLogicMicroserviceCoreContractPriceCalculationTypeToJSON,
    JobLogicMicroserviceCoreContractPriceCalculationTypeToJSONTyped,
} from './JobLogicMicroserviceCoreContractPriceCalculationType';

/**
 * 
 * @export
 * @interface JoblogicAPIModelsCreateMileageJobCostRequest
 */
export interface JoblogicAPIModelsCreateMileageJobCostRequest {
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsCreateMileageJobCostRequest
     */
    quantity?: number;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsCreateMileageJobCostRequest
     */
    engineerId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsCreateMileageJobCostRequest
     */
    visitMileageId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCreateMileageJobCostRequest
     */
    tradeId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCreateMileageJobCostRequest
     */
    payBandId?: string | null;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsCreateMileageJobCostRequest
     */
    engineerTeamId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsCreateMileageJobCostRequest
     */
    jobId?: number;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCreateMileageJobCostRequest
     */
    description?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof JoblogicAPIModelsCreateMileageJobCostRequest
     */
    dateIncurred?: Date;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsCreateMileageJobCostRequest
     */
    costPerUnit?: number;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsCreateMileageJobCostRequest
     */
    sellPerUnit?: number;
    /**
     * 
     * @type {boolean}
     * @memberof JoblogicAPIModelsCreateMileageJobCostRequest
     */
    isChargeable?: boolean;
    /**
     * 
     * @type {JobLogicMicroserviceCoreContractPriceCalculationType}
     * @memberof JoblogicAPIModelsCreateMileageJobCostRequest
     */
    priceCalculationType?: JobLogicMicroserviceCoreContractPriceCalculationType;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCreateMileageJobCostRequest
     */
    taxCodeId?: string;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCreateMileageJobCostRequest
     */
    userId?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof JoblogicAPIModelsCreateMileageJobCostRequest
     */
    tagIds?: Array<string> | null;
    /**
     * Contractor Id in Joblogic
     * @type {string}
     * @memberof JoblogicAPIModelsCreateMileageJobCostRequest
     */
    tenantId: string;
}



/**
 * Check if a given object implements the JoblogicAPIModelsCreateMileageJobCostRequest interface.
 */
export function instanceOfJoblogicAPIModelsCreateMileageJobCostRequest(value: object): value is JoblogicAPIModelsCreateMileageJobCostRequest {
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    return true;
}

export function JoblogicAPIModelsCreateMileageJobCostRequestFromJSON(json: any): JoblogicAPIModelsCreateMileageJobCostRequest {
    return JoblogicAPIModelsCreateMileageJobCostRequestFromJSONTyped(json, false);
}

export function JoblogicAPIModelsCreateMileageJobCostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsCreateMileageJobCostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'quantity': json['Quantity'] == null ? undefined : json['Quantity'],
        'engineerId': json['EngineerId'] == null ? undefined : json['EngineerId'],
        'visitMileageId': json['VisitMileageId'] == null ? undefined : json['VisitMileageId'],
        'tradeId': json['TradeId'] == null ? undefined : json['TradeId'],
        'payBandId': json['PayBandId'] == null ? undefined : json['PayBandId'],
        'engineerTeamId': json['EngineerTeamId'] == null ? undefined : json['EngineerTeamId'],
        'jobId': json['JobId'] == null ? undefined : json['JobId'],
        'description': json['Description'] == null ? undefined : json['Description'],
        'dateIncurred': json['DateIncurred'] == null ? undefined : (new Date(json['DateIncurred'])),
        'costPerUnit': json['CostPerUnit'] == null ? undefined : json['CostPerUnit'],
        'sellPerUnit': json['SellPerUnit'] == null ? undefined : json['SellPerUnit'],
        'isChargeable': json['IsChargeable'] == null ? undefined : json['IsChargeable'],
        'priceCalculationType': json['PriceCalculationType'] == null ? undefined : JobLogicMicroserviceCoreContractPriceCalculationTypeFromJSON(json['PriceCalculationType']),
        'taxCodeId': json['TaxCodeId'] == null ? undefined : json['TaxCodeId'],
        'userId': json['UserId'] == null ? undefined : json['UserId'],
        'tagIds': json['TagIds'] == null ? undefined : json['TagIds'],
        'tenantId': json['TenantId'],
    };
}

export function JoblogicAPIModelsCreateMileageJobCostRequestToJSON(json: any): JoblogicAPIModelsCreateMileageJobCostRequest {
    return JoblogicAPIModelsCreateMileageJobCostRequestToJSONTyped(json, false);
}

export function JoblogicAPIModelsCreateMileageJobCostRequestToJSONTyped(value?: JoblogicAPIModelsCreateMileageJobCostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Quantity': value['quantity'],
        'EngineerId': value['engineerId'],
        'VisitMileageId': value['visitMileageId'],
        'TradeId': value['tradeId'],
        'PayBandId': value['payBandId'],
        'EngineerTeamId': value['engineerTeamId'],
        'JobId': value['jobId'],
        'Description': value['description'],
        'DateIncurred': value['dateIncurred'] == null ? value['dateIncurred'] : value['dateIncurred'].toISOString(),
        'CostPerUnit': value['costPerUnit'],
        'SellPerUnit': value['sellPerUnit'],
        'IsChargeable': value['isChargeable'],
        'PriceCalculationType': JobLogicMicroserviceCoreContractPriceCalculationTypeToJSON(value['priceCalculationType']),
        'TaxCodeId': value['taxCodeId'],
        'UserId': value['userId'],
        'TagIds': value['tagIds'],
        'TenantId': value['tenantId'],
    };
}

