/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const JobLogicMicroserviceCoreContractEngineerRouteAddressType = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2
} as const;
export type JobLogicMicroserviceCoreContractEngineerRouteAddressType = typeof JobLogicMicroserviceCoreContractEngineerRouteAddressType[keyof typeof JobLogicMicroserviceCoreContractEngineerRouteAddressType];


export function instanceOfJobLogicMicroserviceCoreContractEngineerRouteAddressType(value: any): boolean {
    for (const key in JobLogicMicroserviceCoreContractEngineerRouteAddressType) {
        if (Object.prototype.hasOwnProperty.call(JobLogicMicroserviceCoreContractEngineerRouteAddressType, key)) {
            if (JobLogicMicroserviceCoreContractEngineerRouteAddressType[key as keyof typeof JobLogicMicroserviceCoreContractEngineerRouteAddressType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function JobLogicMicroserviceCoreContractEngineerRouteAddressTypeFromJSON(json: any): JobLogicMicroserviceCoreContractEngineerRouteAddressType {
    return JobLogicMicroserviceCoreContractEngineerRouteAddressTypeFromJSONTyped(json, false);
}

export function JobLogicMicroserviceCoreContractEngineerRouteAddressTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobLogicMicroserviceCoreContractEngineerRouteAddressType {
    return json as JobLogicMicroserviceCoreContractEngineerRouteAddressType;
}

export function JobLogicMicroserviceCoreContractEngineerRouteAddressTypeToJSON(value?: JobLogicMicroserviceCoreContractEngineerRouteAddressType | null): any {
    return value as any;
}

export function JobLogicMicroserviceCoreContractEngineerRouteAddressTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): JobLogicMicroserviceCoreContractEngineerRouteAddressType {
    return value as JobLogicMicroserviceCoreContractEngineerRouteAddressType;
}

