/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JoblogicAPIModelsRequestUpdateSiteReferenceRequest
 */
export interface JoblogicAPIModelsRequestUpdateSiteReferenceRequest {
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsRequestUpdateSiteReferenceRequest
     */
    uniqueId: string;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsRequestUpdateSiteReferenceRequest
     */
    referenceNumber?: string | null;
    /**
     * Contractor Id in Joblogic
     * @type {string}
     * @memberof JoblogicAPIModelsRequestUpdateSiteReferenceRequest
     */
    tenantId: string;
}

/**
 * Check if a given object implements the JoblogicAPIModelsRequestUpdateSiteReferenceRequest interface.
 */
export function instanceOfJoblogicAPIModelsRequestUpdateSiteReferenceRequest(value: object): value is JoblogicAPIModelsRequestUpdateSiteReferenceRequest {
    if (!('uniqueId' in value) || value['uniqueId'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    return true;
}

export function JoblogicAPIModelsRequestUpdateSiteReferenceRequestFromJSON(json: any): JoblogicAPIModelsRequestUpdateSiteReferenceRequest {
    return JoblogicAPIModelsRequestUpdateSiteReferenceRequestFromJSONTyped(json, false);
}

export function JoblogicAPIModelsRequestUpdateSiteReferenceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsRequestUpdateSiteReferenceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'uniqueId': json['UniqueId'],
        'referenceNumber': json['ReferenceNumber'] == null ? undefined : json['ReferenceNumber'],
        'tenantId': json['TenantId'],
    };
}

export function JoblogicAPIModelsRequestUpdateSiteReferenceRequestToJSON(json: any): JoblogicAPIModelsRequestUpdateSiteReferenceRequest {
    return JoblogicAPIModelsRequestUpdateSiteReferenceRequestToJSONTyped(json, false);
}

export function JoblogicAPIModelsRequestUpdateSiteReferenceRequestToJSONTyped(value?: JoblogicAPIModelsRequestUpdateSiteReferenceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'UniqueId': value['uniqueId'],
        'ReferenceNumber': value['referenceNumber'],
        'TenantId': value['tenantId'],
    };
}

