/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JoblogicAPIModelsGetCustomerTypeResponse
 */
export interface JoblogicAPIModelsGetCustomerTypeResponse {
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsGetCustomerTypeResponse
     */
    intId?: number;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsGetCustomerTypeResponse
     */
    uniqueId?: string;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsGetCustomerTypeResponse
     */
    description?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof JoblogicAPIModelsGetCustomerTypeResponse
     */
    active?: boolean;
}

/**
 * Check if a given object implements the JoblogicAPIModelsGetCustomerTypeResponse interface.
 */
export function instanceOfJoblogicAPIModelsGetCustomerTypeResponse(value: object): value is JoblogicAPIModelsGetCustomerTypeResponse {
    return true;
}

export function JoblogicAPIModelsGetCustomerTypeResponseFromJSON(json: any): JoblogicAPIModelsGetCustomerTypeResponse {
    return JoblogicAPIModelsGetCustomerTypeResponseFromJSONTyped(json, false);
}

export function JoblogicAPIModelsGetCustomerTypeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsGetCustomerTypeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'intId': json['IntId'] == null ? undefined : json['IntId'],
        'uniqueId': json['UniqueId'] == null ? undefined : json['UniqueId'],
        'description': json['Description'] == null ? undefined : json['Description'],
        'active': json['Active'] == null ? undefined : json['Active'],
    };
}

export function JoblogicAPIModelsGetCustomerTypeResponseToJSON(json: any): JoblogicAPIModelsGetCustomerTypeResponse {
    return JoblogicAPIModelsGetCustomerTypeResponseToJSONTyped(json, false);
}

export function JoblogicAPIModelsGetCustomerTypeResponseToJSONTyped(value?: JoblogicAPIModelsGetCustomerTypeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'IntId': value['intId'],
        'UniqueId': value['uniqueId'],
        'Description': value['description'],
        'Active': value['active'],
    };
}

