/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobLogicMicroserviceCoreContractCustomerTypeOrderBy } from './JobLogicMicroserviceCoreContractCustomerTypeOrderBy';
import {
    JobLogicMicroserviceCoreContractCustomerTypeOrderByFromJSON,
    JobLogicMicroserviceCoreContractCustomerTypeOrderByFromJSONTyped,
    JobLogicMicroserviceCoreContractCustomerTypeOrderByToJSON,
    JobLogicMicroserviceCoreContractCustomerTypeOrderByToJSONTyped,
} from './JobLogicMicroserviceCoreContractCustomerTypeOrderBy';

/**
 * 
 * @export
 * @interface JoblogicAPIModelsSearchCustomerTypeRequest
 */
export interface JoblogicAPIModelsSearchCustomerTypeRequest {
    /**
     * 
     * @type {JobLogicMicroserviceCoreContractCustomerTypeOrderBy}
     * @memberof JoblogicAPIModelsSearchCustomerTypeRequest
     */
    orderBy?: JobLogicMicroserviceCoreContractCustomerTypeOrderBy;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsSearchCustomerTypeRequest
     */
    searchTerm?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof JoblogicAPIModelsSearchCustomerTypeRequest
     */
    includeInactive?: boolean;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsSearchCustomerTypeRequest
     */
    pageIndex?: number;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsSearchCustomerTypeRequest
     */
    pageSize?: number;
    /**
     * Contractor Id in Joblogic
     * @type {string}
     * @memberof JoblogicAPIModelsSearchCustomerTypeRequest
     */
    tenantId: string;
}



/**
 * Check if a given object implements the JoblogicAPIModelsSearchCustomerTypeRequest interface.
 */
export function instanceOfJoblogicAPIModelsSearchCustomerTypeRequest(value: object): value is JoblogicAPIModelsSearchCustomerTypeRequest {
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    return true;
}

export function JoblogicAPIModelsSearchCustomerTypeRequestFromJSON(json: any): JoblogicAPIModelsSearchCustomerTypeRequest {
    return JoblogicAPIModelsSearchCustomerTypeRequestFromJSONTyped(json, false);
}

export function JoblogicAPIModelsSearchCustomerTypeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsSearchCustomerTypeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'orderBy': json['OrderBy'] == null ? undefined : JobLogicMicroserviceCoreContractCustomerTypeOrderByFromJSON(json['OrderBy']),
        'searchTerm': json['SearchTerm'] == null ? undefined : json['SearchTerm'],
        'includeInactive': json['IncludeInactive'] == null ? undefined : json['IncludeInactive'],
        'pageIndex': json['PageIndex'] == null ? undefined : json['PageIndex'],
        'pageSize': json['PageSize'] == null ? undefined : json['PageSize'],
        'tenantId': json['TenantId'],
    };
}

export function JoblogicAPIModelsSearchCustomerTypeRequestToJSON(json: any): JoblogicAPIModelsSearchCustomerTypeRequest {
    return JoblogicAPIModelsSearchCustomerTypeRequestToJSONTyped(json, false);
}

export function JoblogicAPIModelsSearchCustomerTypeRequestToJSONTyped(value?: JoblogicAPIModelsSearchCustomerTypeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'OrderBy': JobLogicMicroserviceCoreContractCustomerTypeOrderByToJSON(value['orderBy']),
        'SearchTerm': value['searchTerm'],
        'IncludeInactive': value['includeInactive'],
        'PageIndex': value['pageIndex'],
        'PageSize': value['pageSize'],
        'TenantId': value['tenantId'],
    };
}

