/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const JobLogicMicroserviceCoreContractPriorityOrderBy = {
    NUMBER_0: 0,
    NUMBER_1: 1
} as const;
export type JobLogicMicroserviceCoreContractPriorityOrderBy = typeof JobLogicMicroserviceCoreContractPriorityOrderBy[keyof typeof JobLogicMicroserviceCoreContractPriorityOrderBy];


export function instanceOfJobLogicMicroserviceCoreContractPriorityOrderBy(value: any): boolean {
    for (const key in JobLogicMicroserviceCoreContractPriorityOrderBy) {
        if (Object.prototype.hasOwnProperty.call(JobLogicMicroserviceCoreContractPriorityOrderBy, key)) {
            if (JobLogicMicroserviceCoreContractPriorityOrderBy[key as keyof typeof JobLogicMicroserviceCoreContractPriorityOrderBy] === value) {
                return true;
            }
        }
    }
    return false;
}

export function JobLogicMicroserviceCoreContractPriorityOrderByFromJSON(json: any): JobLogicMicroserviceCoreContractPriorityOrderBy {
    return JobLogicMicroserviceCoreContractPriorityOrderByFromJSONTyped(json, false);
}

export function JobLogicMicroserviceCoreContractPriorityOrderByFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobLogicMicroserviceCoreContractPriorityOrderBy {
    return json as JobLogicMicroserviceCoreContractPriorityOrderBy;
}

export function JobLogicMicroserviceCoreContractPriorityOrderByToJSON(value?: JobLogicMicroserviceCoreContractPriorityOrderBy | null): any {
    return value as any;
}

export function JobLogicMicroserviceCoreContractPriorityOrderByToJSONTyped(value: any, ignoreDiscriminator: boolean): JobLogicMicroserviceCoreContractPriorityOrderBy {
    return value as JobLogicMicroserviceCoreContractPriorityOrderBy;
}

