/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const JobLogicMicroserviceContractLayerContractRoundingType = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3
} as const;
export type JobLogicMicroserviceContractLayerContractRoundingType = typeof JobLogicMicroserviceContractLayerContractRoundingType[keyof typeof JobLogicMicroserviceContractLayerContractRoundingType];


export function instanceOfJobLogicMicroserviceContractLayerContractRoundingType(value: any): boolean {
    for (const key in JobLogicMicroserviceContractLayerContractRoundingType) {
        if (Object.prototype.hasOwnProperty.call(JobLogicMicroserviceContractLayerContractRoundingType, key)) {
            if (JobLogicMicroserviceContractLayerContractRoundingType[key as keyof typeof JobLogicMicroserviceContractLayerContractRoundingType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function JobLogicMicroserviceContractLayerContractRoundingTypeFromJSON(json: any): JobLogicMicroserviceContractLayerContractRoundingType {
    return JobLogicMicroserviceContractLayerContractRoundingTypeFromJSONTyped(json, false);
}

export function JobLogicMicroserviceContractLayerContractRoundingTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobLogicMicroserviceContractLayerContractRoundingType {
    return json as JobLogicMicroserviceContractLayerContractRoundingType;
}

export function JobLogicMicroserviceContractLayerContractRoundingTypeToJSON(value?: JobLogicMicroserviceContractLayerContractRoundingType | null): any {
    return value as any;
}

export function JobLogicMicroserviceContractLayerContractRoundingTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): JobLogicMicroserviceContractLayerContractRoundingType {
    return value as JobLogicMicroserviceContractLayerContractRoundingType;
}

