/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JoblogicAPIModelsContactItemResponse ContactLevelItemResponse } from './JoblogicAPIModelsContactItemResponse ContactLevelItemResponse';
import {
    JoblogicAPIModelsContactItemResponse ContactLevelItemResponseFromJSON,
    JoblogicAPIModelsContactItemResponse ContactLevelItemResponseFromJSONTyped,
    JoblogicAPIModelsContactItemResponse ContactLevelItemResponseToJSON,
    JoblogicAPIModelsContactItemResponse ContactLevelItemResponseToJSONTyped,
} from './JoblogicAPIModelsContactItemResponse ContactLevelItemResponse';

/**
 * 
 * @export
 * @interface JoblogicAPIModelsContactItemResponse
 */
export interface JoblogicAPIModelsContactItemResponse {
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsContactItemResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsContactItemResponse
     */
    firstName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsContactItemResponse
     */
    lastName?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof JoblogicAPIModelsContactItemResponse
     */
    isVisible?: boolean;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsContactItemResponse
     */
    position?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsContactItemResponse
     */
    telephone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsContactItemResponse
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsContactItemResponse
     */
    version?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsContactItemResponse
     */
    externalId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsContactItemResponse
     */
    eDIAdditionalData?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsContactItemResponse
     */
    secondaryTelephone?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof JoblogicAPIModelsContactItemResponse
     */
    useSecondaryTelephoneForSMS?: boolean;
    /**
     * 
     * @type {Array<JoblogicAPIModelsContactItemResponse ContactLevelItemResponse>}
     * @memberof JoblogicAPIModelsContactItemResponse
     */
    contactLevels?: Array<JoblogicAPIModelsContactItemResponse ContactLevelItemResponse> | null;
}

/**
 * Check if a given object implements the JoblogicAPIModelsContactItemResponse interface.
 */
export function instanceOfJoblogicAPIModelsContactItemResponse(value: object): value is JoblogicAPIModelsContactItemResponse {
    return true;
}

export function JoblogicAPIModelsContactItemResponseFromJSON(json: any): JoblogicAPIModelsContactItemResponse {
    return JoblogicAPIModelsContactItemResponseFromJSONTyped(json, false);
}

export function JoblogicAPIModelsContactItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsContactItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['Id'] == null ? undefined : json['Id'],
        'firstName': json['FirstName'] == null ? undefined : json['FirstName'],
        'lastName': json['LastName'] == null ? undefined : json['LastName'],
        'isVisible': json['IsVisible'] == null ? undefined : json['IsVisible'],
        'position': json['Position'] == null ? undefined : json['Position'],
        'telephone': json['Telephone'] == null ? undefined : json['Telephone'],
        'email': json['Email'] == null ? undefined : json['Email'],
        'version': json['Version'] == null ? undefined : json['Version'],
        'externalId': json['ExternalId'] == null ? undefined : json['ExternalId'],
        'eDIAdditionalData': json['EDIAdditionalData'] == null ? undefined : json['EDIAdditionalData'],
        'secondaryTelephone': json['SecondaryTelephone'] == null ? undefined : json['SecondaryTelephone'],
        'useSecondaryTelephoneForSMS': json['UseSecondaryTelephoneForSMS'] == null ? undefined : json['UseSecondaryTelephoneForSMS'],
        'contactLevels': json['ContactLevels'] == null ? undefined : ((json['ContactLevels'] as Array<any>).map(JoblogicAPIModelsContactItemResponse ContactLevelItemResponseFromJSON)),
    };
}

export function JoblogicAPIModelsContactItemResponseToJSON(json: any): JoblogicAPIModelsContactItemResponse {
    return JoblogicAPIModelsContactItemResponseToJSONTyped(json, false);
}

export function JoblogicAPIModelsContactItemResponseToJSONTyped(value?: JoblogicAPIModelsContactItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Id': value['id'],
        'FirstName': value['firstName'],
        'LastName': value['lastName'],
        'IsVisible': value['isVisible'],
        'Position': value['position'],
        'Telephone': value['telephone'],
        'Email': value['email'],
        'Version': value['version'],
        'ExternalId': value['externalId'],
        'EDIAdditionalData': value['eDIAdditionalData'],
        'SecondaryTelephone': value['secondaryTelephone'],
        'UseSecondaryTelephoneForSMS': value['useSecondaryTelephoneForSMS'],
        'ContactLevels': value['contactLevels'] == null ? undefined : ((value['contactLevels'] as Array<any>).map(JoblogicAPIModelsContactItemResponse ContactLevelItemResponseToJSON)),
    };
}

