/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobLogicMicroserviceCoreContractQuoteAssetRequest } from './JobLogicMicroserviceCoreContractQuoteAssetRequest';
import {
    JobLogicMicroserviceCoreContractQuoteAssetRequestFromJSON,
    JobLogicMicroserviceCoreContractQuoteAssetRequestFromJSONTyped,
    JobLogicMicroserviceCoreContractQuoteAssetRequestToJSON,
    JobLogicMicroserviceCoreContractQuoteAssetRequestToJSONTyped,
} from './JobLogicMicroserviceCoreContractQuoteAssetRequest';
import type { JobLogicMicroserviceCoreContractQuoteNoteRequest } from './JobLogicMicroserviceCoreContractQuoteNoteRequest';
import {
    JobLogicMicroserviceCoreContractQuoteNoteRequestFromJSON,
    JobLogicMicroserviceCoreContractQuoteNoteRequestFromJSONTyped,
    JobLogicMicroserviceCoreContractQuoteNoteRequestToJSON,
    JobLogicMicroserviceCoreContractQuoteNoteRequestToJSONTyped,
} from './JobLogicMicroserviceCoreContractQuoteNoteRequest';

/**
 * 
 * @export
 * @interface JoblogicAPIModelsUpdateQuoteForNGBRequest
 */
export interface JoblogicAPIModelsUpdateQuoteForNGBRequest {
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsUpdateQuoteForNGBRequest
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsUpdateQuoteForNGBRequest
     */
    uniqueId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsUpdateQuoteForNGBRequest
     */
    dateLogged?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsUpdateQuoteForNGBRequest
     */
    jobType?: string | null;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsUpdateQuoteForNGBRequest
     */
    assignedToUserId?: number;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsUpdateQuoteForNGBRequest
     */
    jobCategory?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsUpdateQuoteForNGBRequest
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsUpdateQuoteForNGBRequest
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsUpdateQuoteForNGBRequest
     */
    customReference?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsUpdateQuoteForNGBRequest
     */
    sourceId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsUpdateQuoteForNGBRequest
     */
    priorityLevel?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsUpdateQuoteForNGBRequest
     */
    tradeId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsUpdateQuoteForNGBRequest
     */
    expiryDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsUpdateQuoteForNGBRequest
     */
    saleDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsUpdateQuoteForNGBRequest
     */
    nextContactDate?: string | null;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsUpdateQuoteForNGBRequest
     */
    chanceOfSale?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof JoblogicAPIModelsUpdateQuoteForNGBRequest
     */
    validateChanceOfSale?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof JoblogicAPIModelsUpdateQuoteForNGBRequest
     */
    tags?: Array<string> | null;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsUpdateQuoteForNGBRequest
     */
    customerContractId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsUpdateQuoteForNGBRequest
     */
    comprehensiveAllowance?: number | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsUpdateQuoteForNGBRequest
     */
    comprehensiveNotes?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsUpdateQuoteForNGBRequest
     */
    quoteUserReferenceFieldValue?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsUpdateQuoteForNGBRequest
     */
    quoteUserReferenceDropdownListValue?: string | null;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsUpdateQuoteForNGBRequest
     */
    approvedBy?: number | null;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsUpdateQuoteForNGBRequest
     */
    rejectedBy?: number | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsUpdateQuoteForNGBRequest
     */
    rejectReasonId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsUpdateQuoteForNGBRequest
     */
    orderNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsUpdateQuoteForNGBRequest
     */
    contact?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsUpdateQuoteForNGBRequest
     */
    telephone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsUpdateQuoteForNGBRequest
     */
    emailAddress?: string | null;
    /**
     * 
     * @type {Array<JobLogicMicroserviceCoreContractQuoteNoteRequest>}
     * @memberof JoblogicAPIModelsUpdateQuoteForNGBRequest
     */
    notes?: Array<JobLogicMicroserviceCoreContractQuoteNoteRequest> | null;
    /**
     * 
     * @type {Array<JobLogicMicroserviceCoreContractQuoteAssetRequest>}
     * @memberof JoblogicAPIModelsUpdateQuoteForNGBRequest
     */
    assets?: Array<JobLogicMicroserviceCoreContractQuoteAssetRequest> | null;
    /**
     * Contractor Id in Joblogic
     * @type {string}
     * @memberof JoblogicAPIModelsUpdateQuoteForNGBRequest
     */
    tenantId: string;
}

/**
 * Check if a given object implements the JoblogicAPIModelsUpdateQuoteForNGBRequest interface.
 */
export function instanceOfJoblogicAPIModelsUpdateQuoteForNGBRequest(value: object): value is JoblogicAPIModelsUpdateQuoteForNGBRequest {
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    return true;
}

export function JoblogicAPIModelsUpdateQuoteForNGBRequestFromJSON(json: any): JoblogicAPIModelsUpdateQuoteForNGBRequest {
    return JoblogicAPIModelsUpdateQuoteForNGBRequestFromJSONTyped(json, false);
}

export function JoblogicAPIModelsUpdateQuoteForNGBRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsUpdateQuoteForNGBRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['Id'] == null ? undefined : json['Id'],
        'uniqueId': json['UniqueId'] == null ? undefined : json['UniqueId'],
        'dateLogged': json['DateLogged'] == null ? undefined : json['DateLogged'],
        'jobType': json['JobType'] == null ? undefined : json['JobType'],
        'assignedToUserId': json['AssignedToUserId'] == null ? undefined : json['AssignedToUserId'],
        'jobCategory': json['JobCategory'] == null ? undefined : json['JobCategory'],
        'title': json['Title'] == null ? undefined : json['Title'],
        'description': json['Description'],
        'customReference': json['CustomReference'] == null ? undefined : json['CustomReference'],
        'sourceId': json['SourceId'] == null ? undefined : json['SourceId'],
        'priorityLevel': json['PriorityLevel'] == null ? undefined : json['PriorityLevel'],
        'tradeId': json['TradeId'] == null ? undefined : json['TradeId'],
        'expiryDate': json['ExpiryDate'] == null ? undefined : json['ExpiryDate'],
        'saleDate': json['SaleDate'] == null ? undefined : json['SaleDate'],
        'nextContactDate': json['NextContactDate'] == null ? undefined : json['NextContactDate'],
        'chanceOfSale': json['ChanceOfSale'] == null ? undefined : json['ChanceOfSale'],
        'validateChanceOfSale': json['ValidateChanceOfSale'] == null ? undefined : json['ValidateChanceOfSale'],
        'tags': json['Tags'] == null ? undefined : json['Tags'],
        'customerContractId': json['CustomerContractId'] == null ? undefined : json['CustomerContractId'],
        'comprehensiveAllowance': json['ComprehensiveAllowance'] == null ? undefined : json['ComprehensiveAllowance'],
        'comprehensiveNotes': json['ComprehensiveNotes'] == null ? undefined : json['ComprehensiveNotes'],
        'quoteUserReferenceFieldValue': json['QuoteUserReferenceFieldValue'] == null ? undefined : json['QuoteUserReferenceFieldValue'],
        'quoteUserReferenceDropdownListValue': json['QuoteUserReferenceDropdownListValue'] == null ? undefined : json['QuoteUserReferenceDropdownListValue'],
        'approvedBy': json['ApprovedBy'] == null ? undefined : json['ApprovedBy'],
        'rejectedBy': json['RejectedBy'] == null ? undefined : json['RejectedBy'],
        'rejectReasonId': json['RejectReasonId'] == null ? undefined : json['RejectReasonId'],
        'orderNumber': json['OrderNumber'] == null ? undefined : json['OrderNumber'],
        'contact': json['Contact'] == null ? undefined : json['Contact'],
        'telephone': json['Telephone'] == null ? undefined : json['Telephone'],
        'emailAddress': json['EmailAddress'] == null ? undefined : json['EmailAddress'],
        'notes': json['Notes'] == null ? undefined : ((json['Notes'] as Array<any>).map(JobLogicMicroserviceCoreContractQuoteNoteRequestFromJSON)),
        'assets': json['Assets'] == null ? undefined : ((json['Assets'] as Array<any>).map(JobLogicMicroserviceCoreContractQuoteAssetRequestFromJSON)),
        'tenantId': json['TenantId'],
    };
}

export function JoblogicAPIModelsUpdateQuoteForNGBRequestToJSON(json: any): JoblogicAPIModelsUpdateQuoteForNGBRequest {
    return JoblogicAPIModelsUpdateQuoteForNGBRequestToJSONTyped(json, false);
}

export function JoblogicAPIModelsUpdateQuoteForNGBRequestToJSONTyped(value?: JoblogicAPIModelsUpdateQuoteForNGBRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Id': value['id'],
        'UniqueId': value['uniqueId'],
        'DateLogged': value['dateLogged'],
        'JobType': value['jobType'],
        'AssignedToUserId': value['assignedToUserId'],
        'JobCategory': value['jobCategory'],
        'Title': value['title'],
        'Description': value['description'],
        'CustomReference': value['customReference'],
        'SourceId': value['sourceId'],
        'PriorityLevel': value['priorityLevel'],
        'TradeId': value['tradeId'],
        'ExpiryDate': value['expiryDate'],
        'SaleDate': value['saleDate'],
        'NextContactDate': value['nextContactDate'],
        'ChanceOfSale': value['chanceOfSale'],
        'ValidateChanceOfSale': value['validateChanceOfSale'],
        'Tags': value['tags'],
        'CustomerContractId': value['customerContractId'],
        'ComprehensiveAllowance': value['comprehensiveAllowance'],
        'ComprehensiveNotes': value['comprehensiveNotes'],
        'QuoteUserReferenceFieldValue': value['quoteUserReferenceFieldValue'],
        'QuoteUserReferenceDropdownListValue': value['quoteUserReferenceDropdownListValue'],
        'ApprovedBy': value['approvedBy'],
        'RejectedBy': value['rejectedBy'],
        'RejectReasonId': value['rejectReasonId'],
        'OrderNumber': value['orderNumber'],
        'Contact': value['contact'],
        'Telephone': value['telephone'],
        'EmailAddress': value['emailAddress'],
        'Notes': value['notes'] == null ? undefined : ((value['notes'] as Array<any>).map(JobLogicMicroserviceCoreContractQuoteNoteRequestToJSON)),
        'Assets': value['assets'] == null ? undefined : ((value['assets'] as Array<any>).map(JobLogicMicroserviceCoreContractQuoteAssetRequestToJSON)),
        'TenantId': value['tenantId'],
    };
}

