/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JoblogicAPIModelsUpdateTaxCodeRequest
 */
export interface JoblogicAPIModelsUpdateTaxCodeRequest {
    /**
     * The UniqueId of the Asset Class in Joblogic
     * @type {string}
     * @memberof JoblogicAPIModelsUpdateTaxCodeRequest
     */
    uniqueId: string;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsUpdateTaxCodeRequest
     */
    code: string;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsUpdateTaxCodeRequest
     */
    value?: number | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsUpdateTaxCodeRequest
     */
    description: string;
    /**
     * 
     * @type {boolean}
     * @memberof JoblogicAPIModelsUpdateTaxCodeRequest
     */
    isDefault?: boolean;
    /**
     * Contractor Id in Joblogic
     * @type {string}
     * @memberof JoblogicAPIModelsUpdateTaxCodeRequest
     */
    tenantId: string;
}

/**
 * Check if a given object implements the JoblogicAPIModelsUpdateTaxCodeRequest interface.
 */
export function instanceOfJoblogicAPIModelsUpdateTaxCodeRequest(value: object): value is JoblogicAPIModelsUpdateTaxCodeRequest {
    if (!('uniqueId' in value) || value['uniqueId'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    return true;
}

export function JoblogicAPIModelsUpdateTaxCodeRequestFromJSON(json: any): JoblogicAPIModelsUpdateTaxCodeRequest {
    return JoblogicAPIModelsUpdateTaxCodeRequestFromJSONTyped(json, false);
}

export function JoblogicAPIModelsUpdateTaxCodeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsUpdateTaxCodeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'uniqueId': json['UniqueId'],
        'code': json['Code'],
        'value': json['Value'] == null ? undefined : json['Value'],
        'description': json['Description'],
        'isDefault': json['IsDefault'] == null ? undefined : json['IsDefault'],
        'tenantId': json['TenantId'],
    };
}

export function JoblogicAPIModelsUpdateTaxCodeRequestToJSON(json: any): JoblogicAPIModelsUpdateTaxCodeRequest {
    return JoblogicAPIModelsUpdateTaxCodeRequestToJSONTyped(json, false);
}

export function JoblogicAPIModelsUpdateTaxCodeRequestToJSONTyped(value?: JoblogicAPIModelsUpdateTaxCodeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'UniqueId': value['uniqueId'],
        'Code': value['code'],
        'Value': value['value'],
        'Description': value['description'],
        'IsDefault': value['isDefault'],
        'TenantId': value['tenantId'],
    };
}

