/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const JobLogicMicroserviceLogbookContractCompanyFormEntitySearchOrderBy = {
    NUMBER_1: 1,
    NUMBER_2: 2
} as const;
export type JobLogicMicroserviceLogbookContractCompanyFormEntitySearchOrderBy = typeof JobLogicMicroserviceLogbookContractCompanyFormEntitySearchOrderBy[keyof typeof JobLogicMicroserviceLogbookContractCompanyFormEntitySearchOrderBy];


export function instanceOfJobLogicMicroserviceLogbookContractCompanyFormEntitySearchOrderBy(value: any): boolean {
    for (const key in JobLogicMicroserviceLogbookContractCompanyFormEntitySearchOrderBy) {
        if (Object.prototype.hasOwnProperty.call(JobLogicMicroserviceLogbookContractCompanyFormEntitySearchOrderBy, key)) {
            if (JobLogicMicroserviceLogbookContractCompanyFormEntitySearchOrderBy[key as keyof typeof JobLogicMicroserviceLogbookContractCompanyFormEntitySearchOrderBy] === value) {
                return true;
            }
        }
    }
    return false;
}

export function JobLogicMicroserviceLogbookContractCompanyFormEntitySearchOrderByFromJSON(json: any): JobLogicMicroserviceLogbookContractCompanyFormEntitySearchOrderBy {
    return JobLogicMicroserviceLogbookContractCompanyFormEntitySearchOrderByFromJSONTyped(json, false);
}

export function JobLogicMicroserviceLogbookContractCompanyFormEntitySearchOrderByFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobLogicMicroserviceLogbookContractCompanyFormEntitySearchOrderBy {
    return json as JobLogicMicroserviceLogbookContractCompanyFormEntitySearchOrderBy;
}

export function JobLogicMicroserviceLogbookContractCompanyFormEntitySearchOrderByToJSON(value?: JobLogicMicroserviceLogbookContractCompanyFormEntitySearchOrderBy | null): any {
    return value as any;
}

export function JobLogicMicroserviceLogbookContractCompanyFormEntitySearchOrderByToJSONTyped(value: any, ignoreDiscriminator: boolean): JobLogicMicroserviceLogbookContractCompanyFormEntitySearchOrderBy {
    return value as JobLogicMicroserviceLogbookContractCompanyFormEntitySearchOrderBy;
}

