/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const JobLogicMicroserviceScheduleContractInvoiceAddressScheduleTypeOption = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5
} as const;
export type JobLogicMicroserviceScheduleContractInvoiceAddressScheduleTypeOption = typeof JobLogicMicroserviceScheduleContractInvoiceAddressScheduleTypeOption[keyof typeof JobLogicMicroserviceScheduleContractInvoiceAddressScheduleTypeOption];


export function instanceOfJobLogicMicroserviceScheduleContractInvoiceAddressScheduleTypeOption(value: any): boolean {
    for (const key in JobLogicMicroserviceScheduleContractInvoiceAddressScheduleTypeOption) {
        if (Object.prototype.hasOwnProperty.call(JobLogicMicroserviceScheduleContractInvoiceAddressScheduleTypeOption, key)) {
            if (JobLogicMicroserviceScheduleContractInvoiceAddressScheduleTypeOption[key as keyof typeof JobLogicMicroserviceScheduleContractInvoiceAddressScheduleTypeOption] === value) {
                return true;
            }
        }
    }
    return false;
}

export function JobLogicMicroserviceScheduleContractInvoiceAddressScheduleTypeOptionFromJSON(json: any): JobLogicMicroserviceScheduleContractInvoiceAddressScheduleTypeOption {
    return JobLogicMicroserviceScheduleContractInvoiceAddressScheduleTypeOptionFromJSONTyped(json, false);
}

export function JobLogicMicroserviceScheduleContractInvoiceAddressScheduleTypeOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobLogicMicroserviceScheduleContractInvoiceAddressScheduleTypeOption {
    return json as JobLogicMicroserviceScheduleContractInvoiceAddressScheduleTypeOption;
}

export function JobLogicMicroserviceScheduleContractInvoiceAddressScheduleTypeOptionToJSON(value?: JobLogicMicroserviceScheduleContractInvoiceAddressScheduleTypeOption | null): any {
    return value as any;
}

export function JobLogicMicroserviceScheduleContractInvoiceAddressScheduleTypeOptionToJSONTyped(value: any, ignoreDiscriminator: boolean): JobLogicMicroserviceScheduleContractInvoiceAddressScheduleTypeOption {
    return value as JobLogicMicroserviceScheduleContractInvoiceAddressScheduleTypeOption;
}

