/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAssetServiceTypeTask
 */
export interface JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAssetServiceTypeTask {
    /**
     * 
     * @type {string}
     * @memberof JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAssetServiceTypeTask
     */
    serviceTypeLineId?: string;
    /**
     * 
     * @type {number}
     * @memberof JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAssetServiceTypeTask
     */
    duration?: number;
    /**
     * 
     * @type {boolean}
     * @memberof JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAssetServiceTypeTask
     */
    isComplete?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAssetServiceTypeTask
     */
    isMandatory?: boolean | null;
}

/**
 * Check if a given object implements the JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAssetServiceTypeTask interface.
 */
export function instanceOfJobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAssetServiceTypeTask(value: object): value is JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAssetServiceTypeTask {
    return true;
}

export function JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAssetServiceTypeTaskFromJSON(json: any): JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAssetServiceTypeTask {
    return JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAssetServiceTypeTaskFromJSONTyped(json, false);
}

export function JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAssetServiceTypeTaskFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAssetServiceTypeTask {
    if (json == null) {
        return json;
    }
    return {
        
        'serviceTypeLineId': json['ServiceTypeLineId'] == null ? undefined : json['ServiceTypeLineId'],
        'duration': json['Duration'] == null ? undefined : json['Duration'],
        'isComplete': json['IsComplete'] == null ? undefined : json['IsComplete'],
        'isMandatory': json['IsMandatory'] == null ? undefined : json['IsMandatory'],
    };
}

export function JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAssetServiceTypeTaskToJSON(json: any): JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAssetServiceTypeTask {
    return JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAssetServiceTypeTaskToJSONTyped(json, false);
}

export function JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAssetServiceTypeTaskToJSONTyped(value?: JobLogicMicroserviceCoreContractPPMSaveVisitsRequestJobAssetServiceTypeTask | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ServiceTypeLineId': value['serviceTypeLineId'],
        'Duration': value['duration'],
        'IsComplete': value['isComplete'],
        'IsMandatory': value['isMandatory'],
    };
}

