/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JoblogicAPIModelsAssetAdditionalDetailsModel } from './JoblogicAPIModelsAssetAdditionalDetailsModel';
import {
    JoblogicAPIModelsAssetAdditionalDetailsModelFromJSON,
    JoblogicAPIModelsAssetAdditionalDetailsModelFromJSONTyped,
    JoblogicAPIModelsAssetAdditionalDetailsModelToJSON,
    JoblogicAPIModelsAssetAdditionalDetailsModelToJSONTyped,
} from './JoblogicAPIModelsAssetAdditionalDetailsModel';

/**
 * 
 * @export
 * @interface JoblogicAPIModelsUpdateAssetRequest
 */
export interface JoblogicAPIModelsUpdateAssetRequest {
    /**
     * The Id of the Asset in the Joblogic system (Not the ExternalId)
     * @type {string}
     * @memberof JoblogicAPIModelsUpdateAssetRequest
     */
    id: string;
    /**
     * Will create a new Equipment Class if the requested one does not exist, not case sensitive
     * @type {string}
     * @memberof JoblogicAPIModelsUpdateAssetRequest
     */
    equipmentClass?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsUpdateAssetRequest
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsUpdateAssetRequest
     */
    number?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsUpdateAssetRequest
     */
    notes?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsUpdateAssetRequest
     */
    make?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsUpdateAssetRequest
     */
    model?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsUpdateAssetRequest
     */
    location?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsUpdateAssetRequest
     */
    serialNumber?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof JoblogicAPIModelsUpdateAssetRequest
     */
    installationDate?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof JoblogicAPIModelsUpdateAssetRequest
     */
    labourWarrantyExpiryDate?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof JoblogicAPIModelsUpdateAssetRequest
     */
    assetWarrantyExpiryDate?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsUpdateAssetRequest
     */
    quantity?: number;
    /**
     * A custom reference number which can help to identify the Asset
     * @type {string}
     * @memberof JoblogicAPIModelsUpdateAssetRequest
     */
    referenceNumber?: string | null;
    /**
     * Marks an Asset as suspended in the system
     * @type {boolean}
     * @memberof JoblogicAPIModelsUpdateAssetRequest
     */
    isSuspended?: boolean;
    /**
     * A list of tags, associated to the Asset that can be used for searching/filtering
     * @type {Array<string>}
     * @memberof JoblogicAPIModelsUpdateAssetRequest
     */
    tags?: Array<string> | null;
    /**
     * 
     * @type {JoblogicAPIModelsAssetAdditionalDetailsModel}
     * @memberof JoblogicAPIModelsUpdateAssetRequest
     */
    additionalDetails?: JoblogicAPIModelsAssetAdditionalDetailsModel;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsUpdateAssetRequest
     */
    height?: number | null;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsUpdateAssetRequest
     */
    width?: number | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsUpdateAssetRequest
     */
    panelNumber?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof JoblogicAPIModelsUpdateAssetRequest
     */
    panelInformationEnabled?: boolean;
    /**
     * 
     * @type {Array<number>}
     * @memberof JoblogicAPIModelsUpdateAssetRequest
     */
    relatedAssetIds?: Array<number> | null;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsUpdateAssetRequest
     */
    assetConditionId?: number | null;
    /**
     * Contractor Id in Joblogic
     * @type {string}
     * @memberof JoblogicAPIModelsUpdateAssetRequest
     */
    tenantId: string;
}

/**
 * Check if a given object implements the JoblogicAPIModelsUpdateAssetRequest interface.
 */
export function instanceOfJoblogicAPIModelsUpdateAssetRequest(value: object): value is JoblogicAPIModelsUpdateAssetRequest {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    return true;
}

export function JoblogicAPIModelsUpdateAssetRequestFromJSON(json: any): JoblogicAPIModelsUpdateAssetRequest {
    return JoblogicAPIModelsUpdateAssetRequestFromJSONTyped(json, false);
}

export function JoblogicAPIModelsUpdateAssetRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsUpdateAssetRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['Id'],
        'equipmentClass': json['EquipmentClass'] == null ? undefined : json['EquipmentClass'],
        'description': json['Description'],
        'number': json['Number'] == null ? undefined : json['Number'],
        'notes': json['Notes'] == null ? undefined : json['Notes'],
        'make': json['Make'] == null ? undefined : json['Make'],
        'model': json['Model'] == null ? undefined : json['Model'],
        'location': json['Location'] == null ? undefined : json['Location'],
        'serialNumber': json['SerialNumber'] == null ? undefined : json['SerialNumber'],
        'installationDate': json['InstallationDate'] == null ? undefined : (new Date(json['InstallationDate'])),
        'labourWarrantyExpiryDate': json['LabourWarrantyExpiryDate'] == null ? undefined : (new Date(json['LabourWarrantyExpiryDate'])),
        'assetWarrantyExpiryDate': json['AssetWarrantyExpiryDate'] == null ? undefined : (new Date(json['AssetWarrantyExpiryDate'])),
        'quantity': json['Quantity'] == null ? undefined : json['Quantity'],
        'referenceNumber': json['ReferenceNumber'] == null ? undefined : json['ReferenceNumber'],
        'isSuspended': json['IsSuspended'] == null ? undefined : json['IsSuspended'],
        'tags': json['Tags'] == null ? undefined : json['Tags'],
        'additionalDetails': json['AdditionalDetails'] == null ? undefined : JoblogicAPIModelsAssetAdditionalDetailsModelFromJSON(json['AdditionalDetails']),
        'height': json['Height'] == null ? undefined : json['Height'],
        'width': json['Width'] == null ? undefined : json['Width'],
        'panelNumber': json['PanelNumber'] == null ? undefined : json['PanelNumber'],
        'panelInformationEnabled': json['PanelInformationEnabled'] == null ? undefined : json['PanelInformationEnabled'],
        'relatedAssetIds': json['RelatedAssetIds'] == null ? undefined : json['RelatedAssetIds'],
        'assetConditionId': json['AssetConditionId'] == null ? undefined : json['AssetConditionId'],
        'tenantId': json['TenantId'],
    };
}

export function JoblogicAPIModelsUpdateAssetRequestToJSON(json: any): JoblogicAPIModelsUpdateAssetRequest {
    return JoblogicAPIModelsUpdateAssetRequestToJSONTyped(json, false);
}

export function JoblogicAPIModelsUpdateAssetRequestToJSONTyped(value?: JoblogicAPIModelsUpdateAssetRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Id': value['id'],
        'EquipmentClass': value['equipmentClass'],
        'Description': value['description'],
        'Number': value['number'],
        'Notes': value['notes'],
        'Make': value['make'],
        'Model': value['model'],
        'Location': value['location'],
        'SerialNumber': value['serialNumber'],
        'InstallationDate': value['installationDate'] == null ? value['installationDate'] : value['installationDate'].toISOString(),
        'LabourWarrantyExpiryDate': value['labourWarrantyExpiryDate'] == null ? value['labourWarrantyExpiryDate'] : value['labourWarrantyExpiryDate'].toISOString(),
        'AssetWarrantyExpiryDate': value['assetWarrantyExpiryDate'] == null ? value['assetWarrantyExpiryDate'] : value['assetWarrantyExpiryDate'].toISOString(),
        'Quantity': value['quantity'],
        'ReferenceNumber': value['referenceNumber'],
        'IsSuspended': value['isSuspended'],
        'Tags': value['tags'],
        'AdditionalDetails': JoblogicAPIModelsAssetAdditionalDetailsModelToJSON(value['additionalDetails']),
        'Height': value['height'],
        'Width': value['width'],
        'PanelNumber': value['panelNumber'],
        'PanelInformationEnabled': value['panelInformationEnabled'],
        'RelatedAssetIds': value['relatedAssetIds'],
        'AssetConditionId': value['assetConditionId'],
        'TenantId': value['tenantId'],
    };
}

