/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JoblogicAPIModelsNonProductiveTimeTypeResponse
 */
export interface JoblogicAPIModelsNonProductiveTimeTypeResponse {
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsNonProductiveTimeTypeResponse
     */
    id?: string;
    /**
     * 
     * @type {boolean}
     * @memberof JoblogicAPIModelsNonProductiveTimeTypeResponse
     */
    isDeductible?: boolean;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsNonProductiveTimeTypeResponse
     */
    description?: string | null;
}

/**
 * Check if a given object implements the JoblogicAPIModelsNonProductiveTimeTypeResponse interface.
 */
export function instanceOfJoblogicAPIModelsNonProductiveTimeTypeResponse(value: object): value is JoblogicAPIModelsNonProductiveTimeTypeResponse {
    return true;
}

export function JoblogicAPIModelsNonProductiveTimeTypeResponseFromJSON(json: any): JoblogicAPIModelsNonProductiveTimeTypeResponse {
    return JoblogicAPIModelsNonProductiveTimeTypeResponseFromJSONTyped(json, false);
}

export function JoblogicAPIModelsNonProductiveTimeTypeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsNonProductiveTimeTypeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['Id'] == null ? undefined : json['Id'],
        'isDeductible': json['IsDeductible'] == null ? undefined : json['IsDeductible'],
        'description': json['Description'] == null ? undefined : json['Description'],
    };
}

export function JoblogicAPIModelsNonProductiveTimeTypeResponseToJSON(json: any): JoblogicAPIModelsNonProductiveTimeTypeResponse {
    return JoblogicAPIModelsNonProductiveTimeTypeResponseToJSONTyped(json, false);
}

export function JoblogicAPIModelsNonProductiveTimeTypeResponseToJSONTyped(value?: JoblogicAPIModelsNonProductiveTimeTypeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Id': value['id'],
        'IsDeductible': value['isDeductible'],
        'Description': value['description'],
    };
}

