/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const JobLogicMicroserviceCoreContractStockVehicleOrderBy = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5,
    NUMBER_6: 6,
    NUMBER_7: 7,
    NUMBER_8: 8,
    NUMBER_9: 9,
    NUMBER_10: 10,
    NUMBER_11: 11,
    NUMBER_12: 12,
    NUMBER_13: 13,
    NUMBER_14: 14,
    NUMBER_15: 15,
    NUMBER_16: 16,
    NUMBER_17: 17
} as const;
export type JobLogicMicroserviceCoreContractStockVehicleOrderBy = typeof JobLogicMicroserviceCoreContractStockVehicleOrderBy[keyof typeof JobLogicMicroserviceCoreContractStockVehicleOrderBy];


export function instanceOfJobLogicMicroserviceCoreContractStockVehicleOrderBy(value: any): boolean {
    for (const key in JobLogicMicroserviceCoreContractStockVehicleOrderBy) {
        if (Object.prototype.hasOwnProperty.call(JobLogicMicroserviceCoreContractStockVehicleOrderBy, key)) {
            if (JobLogicMicroserviceCoreContractStockVehicleOrderBy[key as keyof typeof JobLogicMicroserviceCoreContractStockVehicleOrderBy] === value) {
                return true;
            }
        }
    }
    return false;
}

export function JobLogicMicroserviceCoreContractStockVehicleOrderByFromJSON(json: any): JobLogicMicroserviceCoreContractStockVehicleOrderBy {
    return JobLogicMicroserviceCoreContractStockVehicleOrderByFromJSONTyped(json, false);
}

export function JobLogicMicroserviceCoreContractStockVehicleOrderByFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobLogicMicroserviceCoreContractStockVehicleOrderBy {
    return json as JobLogicMicroserviceCoreContractStockVehicleOrderBy;
}

export function JobLogicMicroserviceCoreContractStockVehicleOrderByToJSON(value?: JobLogicMicroserviceCoreContractStockVehicleOrderBy | null): any {
    return value as any;
}

export function JobLogicMicroserviceCoreContractStockVehicleOrderByToJSONTyped(value: any, ignoreDiscriminator: boolean): JobLogicMicroserviceCoreContractStockVehicleOrderBy {
    return value as JobLogicMicroserviceCoreContractStockVehicleOrderBy;
}

