/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JobLogicMicroserviceContractLayerContractComprehensiveContractViewModel
 */
export interface JobLogicMicroserviceContractLayerContractComprehensiveContractViewModel {
    /**
     * 
     * @type {boolean}
     * @memberof JobLogicMicroserviceContractLayerContractComprehensiveContractViewModel
     */
    isComprehensiveContract?: boolean;
    /**
     * 
     * @type {number}
     * @memberof JobLogicMicroserviceContractLayerContractComprehensiveContractViewModel
     */
    totalBudget?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof JobLogicMicroserviceContractLayerContractComprehensiveContractViewModel
     */
    budgetEffectiveDateUTC?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof JobLogicMicroserviceContractLayerContractComprehensiveContractViewModel
     */
    consumableBudget?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof JobLogicMicroserviceContractLayerContractComprehensiveContractViewModel
     */
    consumableBudgetEffectiveDateUTC?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof JobLogicMicroserviceContractLayerContractComprehensiveContractViewModel
     */
    description?: string | null;
}

/**
 * Check if a given object implements the JobLogicMicroserviceContractLayerContractComprehensiveContractViewModel interface.
 */
export function instanceOfJobLogicMicroserviceContractLayerContractComprehensiveContractViewModel(value: object): value is JobLogicMicroserviceContractLayerContractComprehensiveContractViewModel {
    return true;
}

export function JobLogicMicroserviceContractLayerContractComprehensiveContractViewModelFromJSON(json: any): JobLogicMicroserviceContractLayerContractComprehensiveContractViewModel {
    return JobLogicMicroserviceContractLayerContractComprehensiveContractViewModelFromJSONTyped(json, false);
}

export function JobLogicMicroserviceContractLayerContractComprehensiveContractViewModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobLogicMicroserviceContractLayerContractComprehensiveContractViewModel {
    if (json == null) {
        return json;
    }
    return {
        
        'isComprehensiveContract': json['IsComprehensiveContract'] == null ? undefined : json['IsComprehensiveContract'],
        'totalBudget': json['TotalBudget'] == null ? undefined : json['TotalBudget'],
        'budgetEffectiveDateUTC': json['BudgetEffectiveDateUTC'] == null ? undefined : (new Date(json['BudgetEffectiveDateUTC'])),
        'consumableBudget': json['ConsumableBudget'] == null ? undefined : json['ConsumableBudget'],
        'consumableBudgetEffectiveDateUTC': json['ConsumableBudgetEffectiveDateUTC'] == null ? undefined : (new Date(json['ConsumableBudgetEffectiveDateUTC'])),
        'description': json['Description'] == null ? undefined : json['Description'],
    };
}

export function JobLogicMicroserviceContractLayerContractComprehensiveContractViewModelToJSON(json: any): JobLogicMicroserviceContractLayerContractComprehensiveContractViewModel {
    return JobLogicMicroserviceContractLayerContractComprehensiveContractViewModelToJSONTyped(json, false);
}

export function JobLogicMicroserviceContractLayerContractComprehensiveContractViewModelToJSONTyped(value?: JobLogicMicroserviceContractLayerContractComprehensiveContractViewModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'IsComprehensiveContract': value['isComprehensiveContract'],
        'TotalBudget': value['totalBudget'],
        'BudgetEffectiveDateUTC': value['budgetEffectiveDateUTC'] == null ? value['budgetEffectiveDateUTC'] : value['budgetEffectiveDateUTC'].toISOString(),
        'ConsumableBudget': value['consumableBudget'],
        'ConsumableBudgetEffectiveDateUTC': value['consumableBudgetEffectiveDateUTC'] == null ? value['consumableBudgetEffectiveDateUTC'] : value['consumableBudgetEffectiveDateUTC'].toISOString(),
        'Description': value['description'],
    };
}

