/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JoblogicAPIModelsSupplierItemResponse AdditionalDetailsResponse } from './JoblogicAPIModelsSupplierItemResponse AdditionalDetailsResponse';
import {
    JoblogicAPIModelsSupplierItemResponse AdditionalDetailsResponseFromJSON,
    JoblogicAPIModelsSupplierItemResponse AdditionalDetailsResponseFromJSONTyped,
    JoblogicAPIModelsSupplierItemResponse AdditionalDetailsResponseToJSON,
    JoblogicAPIModelsSupplierItemResponse AdditionalDetailsResponseToJSONTyped,
} from './JoblogicAPIModelsSupplierItemResponse AdditionalDetailsResponse';

/**
 * 
 * @export
 * @interface JoblogicAPIModelsSupplierItemResponse
 */
export interface JoblogicAPIModelsSupplierItemResponse {
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsSupplierItemResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsSupplierItemResponse
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsSupplierItemResponse
     */
    address?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsSupplierItemResponse
     */
    postcode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsSupplierItemResponse
     */
    telephone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsSupplierItemResponse
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsSupplierItemResponse
     */
    accountNumber?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof JoblogicAPIModelsSupplierItemResponse
     */
    active?: boolean;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsSupplierItemResponse
     */
    customReference?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsSupplierItemResponse
     */
    externalId?: string | null;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsSupplierItemResponse
     */
    partLibraryId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsSupplierItemResponse
     */
    libraryName?: string | null;
    /**
     * 
     * @type {JoblogicAPIModelsSupplierItemResponse AdditionalDetailsResponse}
     * @memberof JoblogicAPIModelsSupplierItemResponse
     */
    additionalDetails?: JoblogicAPIModelsSupplierItemResponse AdditionalDetailsResponse;
}

/**
 * Check if a given object implements the JoblogicAPIModelsSupplierItemResponse interface.
 */
export function instanceOfJoblogicAPIModelsSupplierItemResponse(value: object): value is JoblogicAPIModelsSupplierItemResponse {
    return true;
}

export function JoblogicAPIModelsSupplierItemResponseFromJSON(json: any): JoblogicAPIModelsSupplierItemResponse {
    return JoblogicAPIModelsSupplierItemResponseFromJSONTyped(json, false);
}

export function JoblogicAPIModelsSupplierItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsSupplierItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['Id'] == null ? undefined : json['Id'],
        'name': json['Name'] == null ? undefined : json['Name'],
        'address': json['Address'] == null ? undefined : json['Address'],
        'postcode': json['Postcode'] == null ? undefined : json['Postcode'],
        'telephone': json['Telephone'] == null ? undefined : json['Telephone'],
        'email': json['Email'] == null ? undefined : json['Email'],
        'accountNumber': json['AccountNumber'] == null ? undefined : json['AccountNumber'],
        'active': json['Active'] == null ? undefined : json['Active'],
        'customReference': json['CustomReference'] == null ? undefined : json['CustomReference'],
        'externalId': json['ExternalId'] == null ? undefined : json['ExternalId'],
        'partLibraryId': json['PartLibraryId'] == null ? undefined : json['PartLibraryId'],
        'libraryName': json['LibraryName'] == null ? undefined : json['LibraryName'],
        'additionalDetails': json['AdditionalDetails'] == null ? undefined : JoblogicAPIModelsSupplierItemResponse AdditionalDetailsResponseFromJSON(json['AdditionalDetails']),
    };
}

export function JoblogicAPIModelsSupplierItemResponseToJSON(json: any): JoblogicAPIModelsSupplierItemResponse {
    return JoblogicAPIModelsSupplierItemResponseToJSONTyped(json, false);
}

export function JoblogicAPIModelsSupplierItemResponseToJSONTyped(value?: JoblogicAPIModelsSupplierItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Id': value['id'],
        'Name': value['name'],
        'Address': value['address'],
        'Postcode': value['postcode'],
        'Telephone': value['telephone'],
        'Email': value['email'],
        'AccountNumber': value['accountNumber'],
        'Active': value['active'],
        'CustomReference': value['customReference'],
        'ExternalId': value['externalId'],
        'PartLibraryId': value['partLibraryId'],
        'LibraryName': value['libraryName'],
        'AdditionalDetails': JoblogicAPIModelsSupplierItemResponse AdditionalDetailsResponseToJSON(value['additionalDetails']),
    };
}

