/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JoblogicAPIModelsUpdateAssetClassResponse
 */
export interface JoblogicAPIModelsUpdateAssetClassResponse {
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsUpdateAssetClassResponse
     */
    uniqueId?: string;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsUpdateAssetClassResponse
     */
    description?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof JoblogicAPIModelsUpdateAssetClassResponse
     */
    active?: boolean;
}

/**
 * Check if a given object implements the JoblogicAPIModelsUpdateAssetClassResponse interface.
 */
export function instanceOfJoblogicAPIModelsUpdateAssetClassResponse(value: object): value is JoblogicAPIModelsUpdateAssetClassResponse {
    return true;
}

export function JoblogicAPIModelsUpdateAssetClassResponseFromJSON(json: any): JoblogicAPIModelsUpdateAssetClassResponse {
    return JoblogicAPIModelsUpdateAssetClassResponseFromJSONTyped(json, false);
}

export function JoblogicAPIModelsUpdateAssetClassResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsUpdateAssetClassResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'uniqueId': json['UniqueId'] == null ? undefined : json['UniqueId'],
        'description': json['Description'] == null ? undefined : json['Description'],
        'active': json['Active'] == null ? undefined : json['Active'],
    };
}

export function JoblogicAPIModelsUpdateAssetClassResponseToJSON(json: any): JoblogicAPIModelsUpdateAssetClassResponse {
    return JoblogicAPIModelsUpdateAssetClassResponseToJSONTyped(json, false);
}

export function JoblogicAPIModelsUpdateAssetClassResponseToJSONTyped(value?: JoblogicAPIModelsUpdateAssetClassResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'UniqueId': value['uniqueId'],
        'Description': value['description'],
        'Active': value['active'],
    };
}

