/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JoblogicAPIModelsSearchTradeRequest
 */
export interface JoblogicAPIModelsSearchTradeRequest {
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsSearchTradeRequest
     */
    searchTerm?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof JoblogicAPIModelsSearchTradeRequest
     */
    includeInactive?: boolean;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsSearchTradeRequest
     */
    pageIndex?: number;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsSearchTradeRequest
     */
    pageSize?: number;
    /**
     * Contractor Id in Joblogic
     * @type {string}
     * @memberof JoblogicAPIModelsSearchTradeRequest
     */
    tenantId: string;
}

/**
 * Check if a given object implements the JoblogicAPIModelsSearchTradeRequest interface.
 */
export function instanceOfJoblogicAPIModelsSearchTradeRequest(value: object): value is JoblogicAPIModelsSearchTradeRequest {
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    return true;
}

export function JoblogicAPIModelsSearchTradeRequestFromJSON(json: any): JoblogicAPIModelsSearchTradeRequest {
    return JoblogicAPIModelsSearchTradeRequestFromJSONTyped(json, false);
}

export function JoblogicAPIModelsSearchTradeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsSearchTradeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'searchTerm': json['SearchTerm'] == null ? undefined : json['SearchTerm'],
        'includeInactive': json['IncludeInactive'] == null ? undefined : json['IncludeInactive'],
        'pageIndex': json['PageIndex'] == null ? undefined : json['PageIndex'],
        'pageSize': json['PageSize'] == null ? undefined : json['PageSize'],
        'tenantId': json['TenantId'],
    };
}

export function JoblogicAPIModelsSearchTradeRequestToJSON(json: any): JoblogicAPIModelsSearchTradeRequest {
    return JoblogicAPIModelsSearchTradeRequestToJSONTyped(json, false);
}

export function JoblogicAPIModelsSearchTradeRequestToJSONTyped(value?: JoblogicAPIModelsSearchTradeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'SearchTerm': value['searchTerm'],
        'IncludeInactive': value['includeInactive'],
        'PageIndex': value['pageIndex'],
        'PageSize': value['pageSize'],
        'TenantId': value['tenantId'],
    };
}

