/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JoblogicAPIModelsCreditCGroupInvoiceDetailApiResponse Line } from './JoblogicAPIModelsCreditCGroupInvoiceDetailApiResponse Line';
import {
    JoblogicAPIModelsCreditCGroupInvoiceDetailApiResponse LineFromJSON,
    JoblogicAPIModelsCreditCGroupInvoiceDetailApiResponse LineFromJSONTyped,
    JoblogicAPIModelsCreditCGroupInvoiceDetailApiResponse LineToJSON,
    JoblogicAPIModelsCreditCGroupInvoiceDetailApiResponse LineToJSONTyped,
} from './JoblogicAPIModelsCreditCGroupInvoiceDetailApiResponse Line';
import type { JobLogicMicroserviceCoreContractInvoiceAddressTypeOption } from './JobLogicMicroserviceCoreContractInvoiceAddressTypeOption';
import {
    JobLogicMicroserviceCoreContractInvoiceAddressTypeOptionFromJSON,
    JobLogicMicroserviceCoreContractInvoiceAddressTypeOptionFromJSONTyped,
    JobLogicMicroserviceCoreContractInvoiceAddressTypeOptionToJSON,
    JobLogicMicroserviceCoreContractInvoiceAddressTypeOptionToJSONTyped,
} from './JobLogicMicroserviceCoreContractInvoiceAddressTypeOption';

/**
 * 
 * @export
 * @interface JoblogicAPIModelsCreditCGroupInvoiceDetailApiResponse
 */
export interface JoblogicAPIModelsCreditCGroupInvoiceDetailApiResponse {
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsCreditCGroupInvoiceDetailApiResponse
     */
    intId?: number;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCreditCGroupInvoiceDetailApiResponse
     */
    uniqueId?: string;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCreditCGroupInvoiceDetailApiResponse
     */
    creditNumber?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof JoblogicAPIModelsCreditCGroupInvoiceDetailApiResponse
     */
    dateRaised?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof JoblogicAPIModelsCreditCGroupInvoiceDetailApiResponse
     */
    isDraft?: boolean;
    /**
     * 
     * @type {JobLogicMicroserviceCoreContractInvoiceAddressTypeOption}
     * @memberof JoblogicAPIModelsCreditCGroupInvoiceDetailApiResponse
     */
    addressType?: JobLogicMicroserviceCoreContractInvoiceAddressTypeOption;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCreditCGroupInvoiceDetailApiResponse
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCreditCGroupInvoiceDetailApiResponse
     */
    address?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCreditCGroupInvoiceDetailApiResponse
     */
    postcode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCreditCGroupInvoiceDetailApiResponse
     */
    orderNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCreditCGroupInvoiceDetailApiResponse
     */
    accountNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCreditCGroupInvoiceDetailApiResponse
     */
    creditReason?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCreditCGroupInvoiceDetailApiResponse
     */
    notes?: string | null;
    /**
     * 
     * @type {Array<JoblogicAPIModelsCreditCGroupInvoiceDetailApiResponse Line>}
     * @memberof JoblogicAPIModelsCreditCGroupInvoiceDetailApiResponse
     */
    lines?: Array<JoblogicAPIModelsCreditCGroupInvoiceDetailApiResponse Line> | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCreditCGroupInvoiceDetailApiResponse
     */
    raisedByUniqueId?: string;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCreditCGroupInvoiceDetailApiResponse
     */
    raisedByName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCreditCGroupInvoiceDetailApiResponse
     */
    originalInvoiceNumber?: string | null;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsCreditCGroupInvoiceDetailApiResponse
     */
    customerId?: number;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCreditCGroupInvoiceDetailApiResponse
     */
    customerName?: string | null;
}



/**
 * Check if a given object implements the JoblogicAPIModelsCreditCGroupInvoiceDetailApiResponse interface.
 */
export function instanceOfJoblogicAPIModelsCreditCGroupInvoiceDetailApiResponse(value: object): value is JoblogicAPIModelsCreditCGroupInvoiceDetailApiResponse {
    return true;
}

export function JoblogicAPIModelsCreditCGroupInvoiceDetailApiResponseFromJSON(json: any): JoblogicAPIModelsCreditCGroupInvoiceDetailApiResponse {
    return JoblogicAPIModelsCreditCGroupInvoiceDetailApiResponseFromJSONTyped(json, false);
}

export function JoblogicAPIModelsCreditCGroupInvoiceDetailApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsCreditCGroupInvoiceDetailApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'intId': json['IntId'] == null ? undefined : json['IntId'],
        'uniqueId': json['UniqueId'] == null ? undefined : json['UniqueId'],
        'creditNumber': json['CreditNumber'] == null ? undefined : json['CreditNumber'],
        'dateRaised': json['DateRaised'] == null ? undefined : (new Date(json['DateRaised'])),
        'isDraft': json['IsDraft'] == null ? undefined : json['IsDraft'],
        'addressType': json['AddressType'] == null ? undefined : JobLogicMicroserviceCoreContractInvoiceAddressTypeOptionFromJSON(json['AddressType']),
        'name': json['Name'] == null ? undefined : json['Name'],
        'address': json['Address'] == null ? undefined : json['Address'],
        'postcode': json['Postcode'] == null ? undefined : json['Postcode'],
        'orderNumber': json['OrderNumber'] == null ? undefined : json['OrderNumber'],
        'accountNumber': json['AccountNumber'] == null ? undefined : json['AccountNumber'],
        'creditReason': json['CreditReason'] == null ? undefined : json['CreditReason'],
        'notes': json['Notes'] == null ? undefined : json['Notes'],
        'lines': json['Lines'] == null ? undefined : ((json['Lines'] as Array<any>).map(JoblogicAPIModelsCreditCGroupInvoiceDetailApiResponse LineFromJSON)),
        'raisedByUniqueId': json['RaisedByUniqueId'] == null ? undefined : json['RaisedByUniqueId'],
        'raisedByName': json['RaisedByName'] == null ? undefined : json['RaisedByName'],
        'originalInvoiceNumber': json['OriginalInvoiceNumber'] == null ? undefined : json['OriginalInvoiceNumber'],
        'customerId': json['CustomerId'] == null ? undefined : json['CustomerId'],
        'customerName': json['CustomerName'] == null ? undefined : json['CustomerName'],
    };
}

export function JoblogicAPIModelsCreditCGroupInvoiceDetailApiResponseToJSON(json: any): JoblogicAPIModelsCreditCGroupInvoiceDetailApiResponse {
    return JoblogicAPIModelsCreditCGroupInvoiceDetailApiResponseToJSONTyped(json, false);
}

export function JoblogicAPIModelsCreditCGroupInvoiceDetailApiResponseToJSONTyped(value?: JoblogicAPIModelsCreditCGroupInvoiceDetailApiResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'IntId': value['intId'],
        'UniqueId': value['uniqueId'],
        'CreditNumber': value['creditNumber'],
        'DateRaised': value['dateRaised'] == null ? value['dateRaised'] : value['dateRaised'].toISOString(),
        'IsDraft': value['isDraft'],
        'AddressType': JobLogicMicroserviceCoreContractInvoiceAddressTypeOptionToJSON(value['addressType']),
        'Name': value['name'],
        'Address': value['address'],
        'Postcode': value['postcode'],
        'OrderNumber': value['orderNumber'],
        'AccountNumber': value['accountNumber'],
        'CreditReason': value['creditReason'],
        'Notes': value['notes'],
        'Lines': value['lines'] == null ? undefined : ((value['lines'] as Array<any>).map(JoblogicAPIModelsCreditCGroupInvoiceDetailApiResponse LineToJSON)),
        'RaisedByUniqueId': value['raisedByUniqueId'],
        'RaisedByName': value['raisedByName'],
        'OriginalInvoiceNumber': value['originalInvoiceNumber'],
        'CustomerId': value['customerId'],
        'CustomerName': value['customerName'],
    };
}

