/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobLogicMicroserviceCoreContractPriceCalculationType } from './JobLogicMicroserviceCoreContractPriceCalculationType';
import {
    JobLogicMicroserviceCoreContractPriceCalculationTypeFromJSON,
    JobLogicMicroserviceCoreContractPriceCalculationTypeFromJSONTyped,
    JobLogicMicroserviceCoreContractPriceCalculationTypeToJSON,
    JobLogicMicroserviceCoreContractPriceCalculationTypeToJSONTyped,
} from './JobLogicMicroserviceCoreContractPriceCalculationType';

/**
 * 
 * @export
 * @interface JoblogicAPIModelsCreateSORItemsJobCostRequest
 */
export interface JoblogicAPIModelsCreateSORItemsJobCostRequest {
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsCreateSORItemsJobCostRequest
     */
    quantity?: number;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsCreateSORItemsJobCostRequest
     */
    scheduleOfRateLibraryId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsCreateSORItemsJobCostRequest
     */
    scheduleOfRateItemId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsCreateSORItemsJobCostRequest
     */
    tradeCategoryId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsCreateSORItemsJobCostRequest
     */
    itemSellValue?: number;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCreateSORItemsJobCostRequest
     */
    longDescription?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCreateSORItemsJobCostRequest
     */
    comments?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCreateSORItemsJobCostRequest
     */
    status?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof JoblogicAPIModelsCreateSORItemsJobCostRequest
     */
    comeFromMobile?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof JoblogicAPIModelsCreateSORItemsJobCostRequest
     */
    variations?: boolean;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsCreateSORItemsJobCostRequest
     */
    createdBy?: number;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsCreateSORItemsJobCostRequest
     */
    discount?: number;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsCreateSORItemsJobCostRequest
     */
    uplift?: number;
    /**
     * 
     * @type {boolean}
     * @memberof JoblogicAPIModelsCreateSORItemsJobCostRequest
     */
    limitedSORAccess?: boolean;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCreateSORItemsJobCostRequest
     */
    uniqueId?: string;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsCreateSORItemsJobCostRequest
     */
    itemId?: number;
    /**
     * 
     * @type {boolean}
     * @memberof JoblogicAPIModelsCreateSORItemsJobCostRequest
     */
    hasQuote?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof JoblogicAPIModelsCreateSORItemsJobCostRequest
     */
    readonly isQuotedValue?: boolean;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCreateSORItemsJobCostRequest
     */
    quotedValueTaxCodeId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCreateSORItemsJobCostRequest
     */
    quotedValueTaxCodeValue?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCreateSORItemsJobCostRequest
     */
    quotedValueTaxCodeDescription?: string | null;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsCreateSORItemsJobCostRequest
     */
    jobId?: number;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCreateSORItemsJobCostRequest
     */
    description?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof JoblogicAPIModelsCreateSORItemsJobCostRequest
     */
    dateIncurred?: Date;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsCreateSORItemsJobCostRequest
     */
    costPerUnit?: number;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsCreateSORItemsJobCostRequest
     */
    sellPerUnit?: number;
    /**
     * 
     * @type {boolean}
     * @memberof JoblogicAPIModelsCreateSORItemsJobCostRequest
     */
    isChargeable?: boolean;
    /**
     * 
     * @type {JobLogicMicroserviceCoreContractPriceCalculationType}
     * @memberof JoblogicAPIModelsCreateSORItemsJobCostRequest
     */
    priceCalculationType?: JobLogicMicroserviceCoreContractPriceCalculationType;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCreateSORItemsJobCostRequest
     */
    taxCodeId?: string;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCreateSORItemsJobCostRequest
     */
    userId?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof JoblogicAPIModelsCreateSORItemsJobCostRequest
     */
    tagIds?: Array<string> | null;
    /**
     * Contractor Id in Joblogic
     * @type {string}
     * @memberof JoblogicAPIModelsCreateSORItemsJobCostRequest
     */
    tenantId: string;
}



/**
 * Check if a given object implements the JoblogicAPIModelsCreateSORItemsJobCostRequest interface.
 */
export function instanceOfJoblogicAPIModelsCreateSORItemsJobCostRequest(value: object): value is JoblogicAPIModelsCreateSORItemsJobCostRequest {
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    return true;
}

export function JoblogicAPIModelsCreateSORItemsJobCostRequestFromJSON(json: any): JoblogicAPIModelsCreateSORItemsJobCostRequest {
    return JoblogicAPIModelsCreateSORItemsJobCostRequestFromJSONTyped(json, false);
}

export function JoblogicAPIModelsCreateSORItemsJobCostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsCreateSORItemsJobCostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'quantity': json['Quantity'] == null ? undefined : json['Quantity'],
        'scheduleOfRateLibraryId': json['ScheduleOfRateLibraryId'] == null ? undefined : json['ScheduleOfRateLibraryId'],
        'scheduleOfRateItemId': json['ScheduleOfRateItemId'] == null ? undefined : json['ScheduleOfRateItemId'],
        'tradeCategoryId': json['TradeCategoryId'] == null ? undefined : json['TradeCategoryId'],
        'itemSellValue': json['ItemSellValue'] == null ? undefined : json['ItemSellValue'],
        'longDescription': json['LongDescription'] == null ? undefined : json['LongDescription'],
        'comments': json['Comments'] == null ? undefined : json['Comments'],
        'status': json['Status'] == null ? undefined : json['Status'],
        'comeFromMobile': json['ComeFromMobile'] == null ? undefined : json['ComeFromMobile'],
        'variations': json['Variations'] == null ? undefined : json['Variations'],
        'createdBy': json['CreatedBy'] == null ? undefined : json['CreatedBy'],
        'discount': json['Discount'] == null ? undefined : json['Discount'],
        'uplift': json['Uplift'] == null ? undefined : json['Uplift'],
        'limitedSORAccess': json['LimitedSORAccess'] == null ? undefined : json['LimitedSORAccess'],
        'uniqueId': json['UniqueId'] == null ? undefined : json['UniqueId'],
        'itemId': json['ItemId'] == null ? undefined : json['ItemId'],
        'hasQuote': json['HasQuote'] == null ? undefined : json['HasQuote'],
        'isQuotedValue': json['IsQuotedValue'] == null ? undefined : json['IsQuotedValue'],
        'quotedValueTaxCodeId': json['QuotedValueTaxCodeId'] == null ? undefined : json['QuotedValueTaxCodeId'],
        'quotedValueTaxCodeValue': json['QuotedValueTaxCodeValue'] == null ? undefined : json['QuotedValueTaxCodeValue'],
        'quotedValueTaxCodeDescription': json['QuotedValueTaxCodeDescription'] == null ? undefined : json['QuotedValueTaxCodeDescription'],
        'jobId': json['JobId'] == null ? undefined : json['JobId'],
        'description': json['Description'] == null ? undefined : json['Description'],
        'dateIncurred': json['DateIncurred'] == null ? undefined : (new Date(json['DateIncurred'])),
        'costPerUnit': json['CostPerUnit'] == null ? undefined : json['CostPerUnit'],
        'sellPerUnit': json['SellPerUnit'] == null ? undefined : json['SellPerUnit'],
        'isChargeable': json['IsChargeable'] == null ? undefined : json['IsChargeable'],
        'priceCalculationType': json['PriceCalculationType'] == null ? undefined : JobLogicMicroserviceCoreContractPriceCalculationTypeFromJSON(json['PriceCalculationType']),
        'taxCodeId': json['TaxCodeId'] == null ? undefined : json['TaxCodeId'],
        'userId': json['UserId'] == null ? undefined : json['UserId'],
        'tagIds': json['TagIds'] == null ? undefined : json['TagIds'],
        'tenantId': json['TenantId'],
    };
}

export function JoblogicAPIModelsCreateSORItemsJobCostRequestToJSON(json: any): JoblogicAPIModelsCreateSORItemsJobCostRequest {
    return JoblogicAPIModelsCreateSORItemsJobCostRequestToJSONTyped(json, false);
}

export function JoblogicAPIModelsCreateSORItemsJobCostRequestToJSONTyped(value?: Omit<JoblogicAPIModelsCreateSORItemsJobCostRequest, 'IsQuotedValue'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Quantity': value['quantity'],
        'ScheduleOfRateLibraryId': value['scheduleOfRateLibraryId'],
        'ScheduleOfRateItemId': value['scheduleOfRateItemId'],
        'TradeCategoryId': value['tradeCategoryId'],
        'ItemSellValue': value['itemSellValue'],
        'LongDescription': value['longDescription'],
        'Comments': value['comments'],
        'Status': value['status'],
        'ComeFromMobile': value['comeFromMobile'],
        'Variations': value['variations'],
        'CreatedBy': value['createdBy'],
        'Discount': value['discount'],
        'Uplift': value['uplift'],
        'LimitedSORAccess': value['limitedSORAccess'],
        'UniqueId': value['uniqueId'],
        'ItemId': value['itemId'],
        'HasQuote': value['hasQuote'],
        'QuotedValueTaxCodeId': value['quotedValueTaxCodeId'],
        'QuotedValueTaxCodeValue': value['quotedValueTaxCodeValue'],
        'QuotedValueTaxCodeDescription': value['quotedValueTaxCodeDescription'],
        'JobId': value['jobId'],
        'Description': value['description'],
        'DateIncurred': value['dateIncurred'] == null ? value['dateIncurred'] : value['dateIncurred'].toISOString(),
        'CostPerUnit': value['costPerUnit'],
        'SellPerUnit': value['sellPerUnit'],
        'IsChargeable': value['isChargeable'],
        'PriceCalculationType': JobLogicMicroserviceCoreContractPriceCalculationTypeToJSON(value['priceCalculationType']),
        'TaxCodeId': value['taxCodeId'],
        'UserId': value['userId'],
        'TagIds': value['tagIds'],
        'TenantId': value['tenantId'],
    };
}

