/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JoblogicAPIModelsPriorityItemResponse } from './JoblogicAPIModelsPriorityItemResponse';
import {
    JoblogicAPIModelsPriorityItemResponseFromJSON,
    JoblogicAPIModelsPriorityItemResponseFromJSONTyped,
    JoblogicAPIModelsPriorityItemResponseToJSON,
    JoblogicAPIModelsPriorityItemResponseToJSONTyped,
} from './JoblogicAPIModelsPriorityItemResponse';

/**
 * 
 * @export
 * @interface JoblogicAPIModelsSearchPriorityResponse
 */
export interface JoblogicAPIModelsSearchPriorityResponse {
    /**
     * 
     * @type {Array<JoblogicAPIModelsPriorityItemResponse>}
     * @memberof JoblogicAPIModelsSearchPriorityResponse
     */
    items?: Array<JoblogicAPIModelsPriorityItemResponse> | null;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsSearchPriorityResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsSearchPriorityResponse
     */
    pageIndex?: number;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsSearchPriorityResponse
     */
    pageSize?: number;
}

/**
 * Check if a given object implements the JoblogicAPIModelsSearchPriorityResponse interface.
 */
export function instanceOfJoblogicAPIModelsSearchPriorityResponse(value: object): value is JoblogicAPIModelsSearchPriorityResponse {
    return true;
}

export function JoblogicAPIModelsSearchPriorityResponseFromJSON(json: any): JoblogicAPIModelsSearchPriorityResponse {
    return JoblogicAPIModelsSearchPriorityResponseFromJSONTyped(json, false);
}

export function JoblogicAPIModelsSearchPriorityResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsSearchPriorityResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['Items'] == null ? undefined : ((json['Items'] as Array<any>).map(JoblogicAPIModelsPriorityItemResponseFromJSON)),
        'totalCount': json['TotalCount'] == null ? undefined : json['TotalCount'],
        'pageIndex': json['PageIndex'] == null ? undefined : json['PageIndex'],
        'pageSize': json['PageSize'] == null ? undefined : json['PageSize'],
    };
}

export function JoblogicAPIModelsSearchPriorityResponseToJSON(json: any): JoblogicAPIModelsSearchPriorityResponse {
    return JoblogicAPIModelsSearchPriorityResponseToJSONTyped(json, false);
}

export function JoblogicAPIModelsSearchPriorityResponseToJSONTyped(value?: JoblogicAPIModelsSearchPriorityResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(JoblogicAPIModelsPriorityItemResponseToJSON)),
        'TotalCount': value['totalCount'],
        'PageIndex': value['pageIndex'],
        'PageSize': value['pageSize'],
    };
}

