/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobLogicMicroserviceCoreContractPriceCalculationType } from './JobLogicMicroserviceCoreContractPriceCalculationType';
import {
    JobLogicMicroserviceCoreContractPriceCalculationTypeFromJSON,
    JobLogicMicroserviceCoreContractPriceCalculationTypeFromJSONTyped,
    JobLogicMicroserviceCoreContractPriceCalculationTypeToJSON,
    JobLogicMicroserviceCoreContractPriceCalculationTypeToJSONTyped,
} from './JobLogicMicroserviceCoreContractPriceCalculationType';

/**
 * 
 * @export
 * @interface JoblogicAPIModelsCreateMaterialJobCostRequest
 */
export interface JoblogicAPIModelsCreateMaterialJobCostRequest {
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsCreateMaterialJobCostRequest
     */
    engineerId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsCreateMaterialJobCostRequest
     */
    partId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCreateMaterialJobCostRequest
     */
    partNumber?: string | null;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsCreateMaterialJobCostRequest
     */
    jobPartId?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof JoblogicAPIModelsCreateMaterialJobCostRequest
     */
    forEquipmentUse?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof JoblogicAPIModelsCreateMaterialJobCostRequest
     */
    isIssueFromStock?: boolean;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsCreateMaterialJobCostRequest
     */
    locationRackShelfId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsCreateMaterialJobCostRequest
     */
    locationId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsCreateMaterialJobCostRequest
     */
    lineId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsCreateMaterialJobCostRequest
     */
    quantity?: number;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsCreateMaterialJobCostRequest
     */
    jobLogicUserId?: number;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsCreateMaterialJobCostRequest
     */
    jobId?: number;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCreateMaterialJobCostRequest
     */
    description?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof JoblogicAPIModelsCreateMaterialJobCostRequest
     */
    dateIncurred?: Date;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsCreateMaterialJobCostRequest
     */
    costPerUnit?: number;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsCreateMaterialJobCostRequest
     */
    sellPerUnit?: number;
    /**
     * 
     * @type {boolean}
     * @memberof JoblogicAPIModelsCreateMaterialJobCostRequest
     */
    isChargeable?: boolean;
    /**
     * 
     * @type {JobLogicMicroserviceCoreContractPriceCalculationType}
     * @memberof JoblogicAPIModelsCreateMaterialJobCostRequest
     */
    priceCalculationType?: JobLogicMicroserviceCoreContractPriceCalculationType;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCreateMaterialJobCostRequest
     */
    taxCodeId?: string;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCreateMaterialJobCostRequest
     */
    userId?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof JoblogicAPIModelsCreateMaterialJobCostRequest
     */
    tagIds?: Array<string> | null;
    /**
     * Contractor Id in Joblogic
     * @type {string}
     * @memberof JoblogicAPIModelsCreateMaterialJobCostRequest
     */
    tenantId: string;
}



/**
 * Check if a given object implements the JoblogicAPIModelsCreateMaterialJobCostRequest interface.
 */
export function instanceOfJoblogicAPIModelsCreateMaterialJobCostRequest(value: object): value is JoblogicAPIModelsCreateMaterialJobCostRequest {
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    return true;
}

export function JoblogicAPIModelsCreateMaterialJobCostRequestFromJSON(json: any): JoblogicAPIModelsCreateMaterialJobCostRequest {
    return JoblogicAPIModelsCreateMaterialJobCostRequestFromJSONTyped(json, false);
}

export function JoblogicAPIModelsCreateMaterialJobCostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsCreateMaterialJobCostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'engineerId': json['EngineerId'] == null ? undefined : json['EngineerId'],
        'partId': json['PartId'] == null ? undefined : json['PartId'],
        'partNumber': json['PartNumber'] == null ? undefined : json['PartNumber'],
        'jobPartId': json['JobPartId'] == null ? undefined : json['JobPartId'],
        'forEquipmentUse': json['ForEquipmentUse'] == null ? undefined : json['ForEquipmentUse'],
        'isIssueFromStock': json['IsIssueFromStock'] == null ? undefined : json['IsIssueFromStock'],
        'locationRackShelfId': json['LocationRackShelfId'] == null ? undefined : json['LocationRackShelfId'],
        'locationId': json['LocationId'] == null ? undefined : json['LocationId'],
        'lineId': json['LineId'] == null ? undefined : json['LineId'],
        'quantity': json['Quantity'] == null ? undefined : json['Quantity'],
        'jobLogicUserId': json['JobLogicUserId'] == null ? undefined : json['JobLogicUserId'],
        'jobId': json['JobId'] == null ? undefined : json['JobId'],
        'description': json['Description'] == null ? undefined : json['Description'],
        'dateIncurred': json['DateIncurred'] == null ? undefined : (new Date(json['DateIncurred'])),
        'costPerUnit': json['CostPerUnit'] == null ? undefined : json['CostPerUnit'],
        'sellPerUnit': json['SellPerUnit'] == null ? undefined : json['SellPerUnit'],
        'isChargeable': json['IsChargeable'] == null ? undefined : json['IsChargeable'],
        'priceCalculationType': json['PriceCalculationType'] == null ? undefined : JobLogicMicroserviceCoreContractPriceCalculationTypeFromJSON(json['PriceCalculationType']),
        'taxCodeId': json['TaxCodeId'] == null ? undefined : json['TaxCodeId'],
        'userId': json['UserId'] == null ? undefined : json['UserId'],
        'tagIds': json['TagIds'] == null ? undefined : json['TagIds'],
        'tenantId': json['TenantId'],
    };
}

export function JoblogicAPIModelsCreateMaterialJobCostRequestToJSON(json: any): JoblogicAPIModelsCreateMaterialJobCostRequest {
    return JoblogicAPIModelsCreateMaterialJobCostRequestToJSONTyped(json, false);
}

export function JoblogicAPIModelsCreateMaterialJobCostRequestToJSONTyped(value?: JoblogicAPIModelsCreateMaterialJobCostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'EngineerId': value['engineerId'],
        'PartId': value['partId'],
        'PartNumber': value['partNumber'],
        'JobPartId': value['jobPartId'],
        'ForEquipmentUse': value['forEquipmentUse'],
        'IsIssueFromStock': value['isIssueFromStock'],
        'LocationRackShelfId': value['locationRackShelfId'],
        'LocationId': value['locationId'],
        'LineId': value['lineId'],
        'Quantity': value['quantity'],
        'JobLogicUserId': value['jobLogicUserId'],
        'JobId': value['jobId'],
        'Description': value['description'],
        'DateIncurred': value['dateIncurred'] == null ? value['dateIncurred'] : value['dateIncurred'].toISOString(),
        'CostPerUnit': value['costPerUnit'],
        'SellPerUnit': value['sellPerUnit'],
        'IsChargeable': value['isChargeable'],
        'PriceCalculationType': JobLogicMicroserviceCoreContractPriceCalculationTypeToJSON(value['priceCalculationType']),
        'TaxCodeId': value['taxCodeId'],
        'UserId': value['userId'],
        'TagIds': value['tagIds'],
        'TenantId': value['tenantId'],
    };
}

