/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobLogicMicroserviceCoreContractSubContractorInvoiceType } from './JobLogicMicroserviceCoreContractSubContractorInvoiceType';
import {
    JobLogicMicroserviceCoreContractSubContractorInvoiceTypeFromJSON,
    JobLogicMicroserviceCoreContractSubContractorInvoiceTypeFromJSONTyped,
    JobLogicMicroserviceCoreContractSubContractorInvoiceTypeToJSON,
    JobLogicMicroserviceCoreContractSubContractorInvoiceTypeToJSONTyped,
} from './JobLogicMicroserviceCoreContractSubContractorInvoiceType';

/**
 * 
 * @export
 * @interface JoblogicAPIModelsCreateSubcontractorPOInvoiceRequest
 */
export interface JoblogicAPIModelsCreateSubcontractorPOInvoiceRequest {
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCreateSubcontractorPOInvoiceRequest
     */
    purchaseOrderUniqueId: string;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCreateSubcontractorPOInvoiceRequest
     */
    base64File?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCreateSubcontractorPOInvoiceRequest
     */
    fileName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCreateSubcontractorPOInvoiceRequest
     */
    invoiceNumber: string;
    /**
     * 
     * @type {Date}
     * @memberof JoblogicAPIModelsCreateSubcontractorPOInvoiceRequest
     */
    invoiceDate: Date;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCreateSubcontractorPOInvoiceRequest
     */
    referenceNumber?: string | null;
    /**
     * 
     * @type {JobLogicMicroserviceCoreContractSubContractorInvoiceType}
     * @memberof JoblogicAPIModelsCreateSubcontractorPOInvoiceRequest
     */
    type?: JobLogicMicroserviceCoreContractSubContractorInvoiceType;
    /**
     * Contractor Id in Joblogic
     * @type {string}
     * @memberof JoblogicAPIModelsCreateSubcontractorPOInvoiceRequest
     */
    tenantId: string;
}



/**
 * Check if a given object implements the JoblogicAPIModelsCreateSubcontractorPOInvoiceRequest interface.
 */
export function instanceOfJoblogicAPIModelsCreateSubcontractorPOInvoiceRequest(value: object): value is JoblogicAPIModelsCreateSubcontractorPOInvoiceRequest {
    if (!('purchaseOrderUniqueId' in value) || value['purchaseOrderUniqueId'] === undefined) return false;
    if (!('invoiceNumber' in value) || value['invoiceNumber'] === undefined) return false;
    if (!('invoiceDate' in value) || value['invoiceDate'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    return true;
}

export function JoblogicAPIModelsCreateSubcontractorPOInvoiceRequestFromJSON(json: any): JoblogicAPIModelsCreateSubcontractorPOInvoiceRequest {
    return JoblogicAPIModelsCreateSubcontractorPOInvoiceRequestFromJSONTyped(json, false);
}

export function JoblogicAPIModelsCreateSubcontractorPOInvoiceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsCreateSubcontractorPOInvoiceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'purchaseOrderUniqueId': json['PurchaseOrderUniqueId'],
        'base64File': json['Base64File'] == null ? undefined : json['Base64File'],
        'fileName': json['FileName'] == null ? undefined : json['FileName'],
        'invoiceNumber': json['InvoiceNumber'],
        'invoiceDate': (new Date(json['InvoiceDate'])),
        'referenceNumber': json['ReferenceNumber'] == null ? undefined : json['ReferenceNumber'],
        'type': json['Type'] == null ? undefined : JobLogicMicroserviceCoreContractSubContractorInvoiceTypeFromJSON(json['Type']),
        'tenantId': json['TenantId'],
    };
}

export function JoblogicAPIModelsCreateSubcontractorPOInvoiceRequestToJSON(json: any): JoblogicAPIModelsCreateSubcontractorPOInvoiceRequest {
    return JoblogicAPIModelsCreateSubcontractorPOInvoiceRequestToJSONTyped(json, false);
}

export function JoblogicAPIModelsCreateSubcontractorPOInvoiceRequestToJSONTyped(value?: JoblogicAPIModelsCreateSubcontractorPOInvoiceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'PurchaseOrderUniqueId': value['purchaseOrderUniqueId'],
        'Base64File': value['base64File'],
        'FileName': value['fileName'],
        'InvoiceNumber': value['invoiceNumber'],
        'InvoiceDate': value['invoiceDate'].toISOString(),
        'ReferenceNumber': value['referenceNumber'],
        'Type': JobLogicMicroserviceCoreContractSubContractorInvoiceTypeToJSON(value['type']),
        'TenantId': value['tenantId'],
    };
}

