/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobLogicMicroserviceCoreContractEnumsSearchCondtionOption } from './JobLogicMicroserviceCoreContractEnumsSearchCondtionOption';
import {
    JobLogicMicroserviceCoreContractEnumsSearchCondtionOptionFromJSON,
    JobLogicMicroserviceCoreContractEnumsSearchCondtionOptionFromJSONTyped,
    JobLogicMicroserviceCoreContractEnumsSearchCondtionOptionToJSON,
    JobLogicMicroserviceCoreContractEnumsSearchCondtionOptionToJSONTyped,
} from './JobLogicMicroserviceCoreContractEnumsSearchCondtionOption';
import type { JobLogicMicroserviceCoreContractSubContractorPOOrderBy } from './JobLogicMicroserviceCoreContractSubContractorPOOrderBy';
import {
    JobLogicMicroserviceCoreContractSubContractorPOOrderByFromJSON,
    JobLogicMicroserviceCoreContractSubContractorPOOrderByFromJSONTyped,
    JobLogicMicroserviceCoreContractSubContractorPOOrderByToJSON,
    JobLogicMicroserviceCoreContractSubContractorPOOrderByToJSONTyped,
} from './JobLogicMicroserviceCoreContractSubContractorPOOrderBy';

/**
 * 
 * @export
 * @interface JoblogicAPIModelsSubcontractorPurchaseOrderRequest
 */
export interface JoblogicAPIModelsSubcontractorPurchaseOrderRequest {
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsSubcontractorPurchaseOrderRequest
     */
    statuses?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsSubcontractorPurchaseOrderRequest
     */
    completionStatuses?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsSubcontractorPurchaseOrderRequest
     */
    startDateRaised: string;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsSubcontractorPurchaseOrderRequest
     */
    endDateRaised?: string | null;
    /**
     * 
     * @type {JobLogicMicroserviceCoreContractSubContractorPOOrderBy}
     * @memberof JoblogicAPIModelsSubcontractorPurchaseOrderRequest
     */
    orderBy?: JobLogicMicroserviceCoreContractSubContractorPOOrderBy;
    /**
     * 
     * @type {Array<number>}
     * @memberof JoblogicAPIModelsSubcontractorPurchaseOrderRequest
     */
    customerContractIds?: Array<number> | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsSubcontractorPurchaseOrderRequest
     */
    searchTerm?: string | null;
    /**
     * 
     * @type {JobLogicMicroserviceCoreContractEnumsSearchCondtionOption}
     * @memberof JoblogicAPIModelsSubcontractorPurchaseOrderRequest
     */
    searchCondition?: JobLogicMicroserviceCoreContractEnumsSearchCondtionOption;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsSubcontractorPurchaseOrderRequest
     */
    tagIds?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof JoblogicAPIModelsSubcontractorPurchaseOrderRequest
     */
    includeInactive?: boolean;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsSubcontractorPurchaseOrderRequest
     */
    pageIndex?: number;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsSubcontractorPurchaseOrderRequest
     */
    pageSize?: number;
    /**
     * Contractor Id in Joblogic
     * @type {string}
     * @memberof JoblogicAPIModelsSubcontractorPurchaseOrderRequest
     */
    tenantId: string;
}



/**
 * Check if a given object implements the JoblogicAPIModelsSubcontractorPurchaseOrderRequest interface.
 */
export function instanceOfJoblogicAPIModelsSubcontractorPurchaseOrderRequest(value: object): value is JoblogicAPIModelsSubcontractorPurchaseOrderRequest {
    if (!('startDateRaised' in value) || value['startDateRaised'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    return true;
}

export function JoblogicAPIModelsSubcontractorPurchaseOrderRequestFromJSON(json: any): JoblogicAPIModelsSubcontractorPurchaseOrderRequest {
    return JoblogicAPIModelsSubcontractorPurchaseOrderRequestFromJSONTyped(json, false);
}

export function JoblogicAPIModelsSubcontractorPurchaseOrderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsSubcontractorPurchaseOrderRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'statuses': json['Statuses'] == null ? undefined : json['Statuses'],
        'completionStatuses': json['CompletionStatuses'] == null ? undefined : json['CompletionStatuses'],
        'startDateRaised': json['StartDateRaised'],
        'endDateRaised': json['EndDateRaised'] == null ? undefined : json['EndDateRaised'],
        'orderBy': json['OrderBy'] == null ? undefined : JobLogicMicroserviceCoreContractSubContractorPOOrderByFromJSON(json['OrderBy']),
        'customerContractIds': json['CustomerContractIds'] == null ? undefined : json['CustomerContractIds'],
        'searchTerm': json['SearchTerm'] == null ? undefined : json['SearchTerm'],
        'searchCondition': json['SearchCondition'] == null ? undefined : JobLogicMicroserviceCoreContractEnumsSearchCondtionOptionFromJSON(json['SearchCondition']),
        'tagIds': json['TagIds'] == null ? undefined : json['TagIds'],
        'includeInactive': json['IncludeInactive'] == null ? undefined : json['IncludeInactive'],
        'pageIndex': json['PageIndex'] == null ? undefined : json['PageIndex'],
        'pageSize': json['PageSize'] == null ? undefined : json['PageSize'],
        'tenantId': json['TenantId'],
    };
}

export function JoblogicAPIModelsSubcontractorPurchaseOrderRequestToJSON(json: any): JoblogicAPIModelsSubcontractorPurchaseOrderRequest {
    return JoblogicAPIModelsSubcontractorPurchaseOrderRequestToJSONTyped(json, false);
}

export function JoblogicAPIModelsSubcontractorPurchaseOrderRequestToJSONTyped(value?: JoblogicAPIModelsSubcontractorPurchaseOrderRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Statuses': value['statuses'],
        'CompletionStatuses': value['completionStatuses'],
        'StartDateRaised': value['startDateRaised'],
        'EndDateRaised': value['endDateRaised'],
        'OrderBy': JobLogicMicroserviceCoreContractSubContractorPOOrderByToJSON(value['orderBy']),
        'CustomerContractIds': value['customerContractIds'],
        'SearchTerm': value['searchTerm'],
        'SearchCondition': JobLogicMicroserviceCoreContractEnumsSearchCondtionOptionToJSON(value['searchCondition']),
        'TagIds': value['tagIds'],
        'IncludeInactive': value['includeInactive'],
        'PageIndex': value['pageIndex'],
        'PageSize': value['pageSize'],
        'TenantId': value['tenantId'],
    };
}

