/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobLogicMicroserviceCoreContractAssignAssetsToJobAPIMsg AssetToAssign } from './JobLogicMicroserviceCoreContractAssignAssetsToJobAPIMsg AssetToAssign';
import {
    JobLogicMicroserviceCoreContractAssignAssetsToJobAPIMsg AssetToAssignFromJSON,
    JobLogicMicroserviceCoreContractAssignAssetsToJobAPIMsg AssetToAssignFromJSONTyped,
    JobLogicMicroserviceCoreContractAssignAssetsToJobAPIMsg AssetToAssignToJSON,
    JobLogicMicroserviceCoreContractAssignAssetsToJobAPIMsg AssetToAssignToJSONTyped,
} from './JobLogicMicroserviceCoreContractAssignAssetsToJobAPIMsg AssetToAssign';

/**
 * 
 * @export
 * @interface JoblogicAPIModelsRequestAssignJobAssetRequest
 */
export interface JoblogicAPIModelsRequestAssignJobAssetRequest {
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsRequestAssignJobAssetRequest
     */
    jobUniqueId: string;
    /**
     * 
     * @type {Array<JobLogicMicroserviceCoreContractAssignAssetsToJobAPIMsg AssetToAssign>}
     * @memberof JoblogicAPIModelsRequestAssignJobAssetRequest
     */
    assetsToAssign?: Array<JobLogicMicroserviceCoreContractAssignAssetsToJobAPIMsg AssetToAssign> | null;
    /**
     * Contractor Id in Joblogic
     * @type {string}
     * @memberof JoblogicAPIModelsRequestAssignJobAssetRequest
     */
    tenantId: string;
}

/**
 * Check if a given object implements the JoblogicAPIModelsRequestAssignJobAssetRequest interface.
 */
export function instanceOfJoblogicAPIModelsRequestAssignJobAssetRequest(value: object): value is JoblogicAPIModelsRequestAssignJobAssetRequest {
    if (!('jobUniqueId' in value) || value['jobUniqueId'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    return true;
}

export function JoblogicAPIModelsRequestAssignJobAssetRequestFromJSON(json: any): JoblogicAPIModelsRequestAssignJobAssetRequest {
    return JoblogicAPIModelsRequestAssignJobAssetRequestFromJSONTyped(json, false);
}

export function JoblogicAPIModelsRequestAssignJobAssetRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsRequestAssignJobAssetRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'jobUniqueId': json['JobUniqueId'],
        'assetsToAssign': json['AssetsToAssign'] == null ? undefined : ((json['AssetsToAssign'] as Array<any>).map(JobLogicMicroserviceCoreContractAssignAssetsToJobAPIMsg AssetToAssignFromJSON)),
        'tenantId': json['TenantId'],
    };
}

export function JoblogicAPIModelsRequestAssignJobAssetRequestToJSON(json: any): JoblogicAPIModelsRequestAssignJobAssetRequest {
    return JoblogicAPIModelsRequestAssignJobAssetRequestToJSONTyped(json, false);
}

export function JoblogicAPIModelsRequestAssignJobAssetRequestToJSONTyped(value?: JoblogicAPIModelsRequestAssignJobAssetRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'JobUniqueId': value['jobUniqueId'],
        'AssetsToAssign': value['assetsToAssign'] == null ? undefined : ((value['assetsToAssign'] as Array<any>).map(JobLogicMicroserviceCoreContractAssignAssetsToJobAPIMsg AssetToAssignToJSON)),
        'TenantId': value['tenantId'],
    };
}

