/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JoblogicAPIModelsAuditItemResponse
 */
export interface JoblogicAPIModelsAuditItemResponse {
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsAuditItemResponse
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsAuditItemResponse
     */
    type?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsAuditItemResponse
     */
    entityId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsAuditItemResponse
     */
    entityStringId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsAuditItemResponse
     */
    action?: string | null;
    /**
     * 
     * @type {any}
     * @memberof JoblogicAPIModelsAuditItemResponse
     */
    detail?: any | null;
    /**
     * 
     * @type {Date}
     * @memberof JoblogicAPIModelsAuditItemResponse
     */
    operationTime?: Date;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsAuditItemResponse
     */
    userId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsAuditItemResponse
     */
    userName?: string | null;
}

/**
 * Check if a given object implements the JoblogicAPIModelsAuditItemResponse interface.
 */
export function instanceOfJoblogicAPIModelsAuditItemResponse(value: object): value is JoblogicAPIModelsAuditItemResponse {
    return true;
}

export function JoblogicAPIModelsAuditItemResponseFromJSON(json: any): JoblogicAPIModelsAuditItemResponse {
    return JoblogicAPIModelsAuditItemResponseFromJSONTyped(json, false);
}

export function JoblogicAPIModelsAuditItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsAuditItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['Id'] == null ? undefined : json['Id'],
        'type': json['Type'] == null ? undefined : json['Type'],
        'entityId': json['EntityId'] == null ? undefined : json['EntityId'],
        'entityStringId': json['EntityStringId'] == null ? undefined : json['EntityStringId'],
        'action': json['Action'] == null ? undefined : json['Action'],
        'detail': json['Detail'] == null ? undefined : json['Detail'],
        'operationTime': json['OperationTime'] == null ? undefined : (new Date(json['OperationTime'])),
        'userId': json['UserId'] == null ? undefined : json['UserId'],
        'userName': json['UserName'] == null ? undefined : json['UserName'],
    };
}

export function JoblogicAPIModelsAuditItemResponseToJSON(json: any): JoblogicAPIModelsAuditItemResponse {
    return JoblogicAPIModelsAuditItemResponseToJSONTyped(json, false);
}

export function JoblogicAPIModelsAuditItemResponseToJSONTyped(value?: JoblogicAPIModelsAuditItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Id': value['id'],
        'Type': value['type'],
        'EntityId': value['entityId'],
        'EntityStringId': value['entityStringId'],
        'Action': value['action'],
        'Detail': value['detail'],
        'OperationTime': value['operationTime'] == null ? value['operationTime'] : value['operationTime'].toISOString(),
        'UserId': value['userId'],
        'UserName': value['userName'],
    };
}

