/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JoblogicAPIModelsSupplierContactResponse } from './JoblogicAPIModelsSupplierContactResponse';
import {
    JoblogicAPIModelsSupplierContactResponseFromJSON,
    JoblogicAPIModelsSupplierContactResponseFromJSONTyped,
    JoblogicAPIModelsSupplierContactResponseToJSON,
    JoblogicAPIModelsSupplierContactResponseToJSONTyped,
} from './JoblogicAPIModelsSupplierContactResponse';

/**
 * 
 * @export
 * @interface JoblogicAPIModelsGetSupplierResponseAdditionalDetailsResponse
 */
export interface JoblogicAPIModelsGetSupplierResponseAdditionalDetailsResponse {
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsGetSupplierResponseAdditionalDetailsResponse
     */
    partLibraryId?: number | null;
    /**
     * 
     * @type {JoblogicAPIModelsSupplierContactResponse}
     * @memberof JoblogicAPIModelsGetSupplierResponseAdditionalDetailsResponse
     */
    primaryContact?: JoblogicAPIModelsSupplierContactResponse;
}

/**
 * Check if a given object implements the JoblogicAPIModelsGetSupplierResponseAdditionalDetailsResponse interface.
 */
export function instanceOfJoblogicAPIModelsGetSupplierResponseAdditionalDetailsResponse(value: object): value is JoblogicAPIModelsGetSupplierResponseAdditionalDetailsResponse {
    return true;
}

export function JoblogicAPIModelsGetSupplierResponseAdditionalDetailsResponseFromJSON(json: any): JoblogicAPIModelsGetSupplierResponseAdditionalDetailsResponse {
    return JoblogicAPIModelsGetSupplierResponseAdditionalDetailsResponseFromJSONTyped(json, false);
}

export function JoblogicAPIModelsGetSupplierResponseAdditionalDetailsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsGetSupplierResponseAdditionalDetailsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'partLibraryId': json['PartLibraryId'] == null ? undefined : json['PartLibraryId'],
        'primaryContact': json['PrimaryContact'] == null ? undefined : JoblogicAPIModelsSupplierContactResponseFromJSON(json['PrimaryContact']),
    };
}

export function JoblogicAPIModelsGetSupplierResponseAdditionalDetailsResponseToJSON(json: any): JoblogicAPIModelsGetSupplierResponseAdditionalDetailsResponse {
    return JoblogicAPIModelsGetSupplierResponseAdditionalDetailsResponseToJSONTyped(json, false);
}

export function JoblogicAPIModelsGetSupplierResponseAdditionalDetailsResponseToJSONTyped(value?: JoblogicAPIModelsGetSupplierResponseAdditionalDetailsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'PartLibraryId': value['partLibraryId'],
        'PrimaryContact': JoblogicAPIModelsSupplierContactResponseToJSON(value['primaryContact']),
    };
}

