/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobLogicMicroserviceCoreContractInvoicePaymentType } from './JobLogicMicroserviceCoreContractInvoicePaymentType';
import {
    JobLogicMicroserviceCoreContractInvoicePaymentTypeFromJSON,
    JobLogicMicroserviceCoreContractInvoicePaymentTypeFromJSONTyped,
    JobLogicMicroserviceCoreContractInvoicePaymentTypeToJSON,
    JobLogicMicroserviceCoreContractInvoicePaymentTypeToJSONTyped,
} from './JobLogicMicroserviceCoreContractInvoicePaymentType';
import type { JoblogicAPIModelsNominalCodeSearchItem } from './JoblogicAPIModelsNominalCodeSearchItem';
import {
    JoblogicAPIModelsNominalCodeSearchItemFromJSON,
    JoblogicAPIModelsNominalCodeSearchItemFromJSONTyped,
    JoblogicAPIModelsNominalCodeSearchItemToJSON,
    JoblogicAPIModelsNominalCodeSearchItemToJSONTyped,
} from './JoblogicAPIModelsNominalCodeSearchItem';

/**
 * 
 * @export
 * @interface JoblogicAPIModelsPPMInvoicePayment
 */
export interface JoblogicAPIModelsPPMInvoicePayment {
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsPPMInvoicePayment
     */
    pPMInvoiceId?: string;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsPPMInvoicePayment
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsPPMInvoicePayment
     */
    amount?: number;
    /**
     * 
     * @type {Date}
     * @memberof JoblogicAPIModelsPPMInvoicePayment
     */
    date?: Date;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsPPMInvoicePayment
     */
    notes?: string | null;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsPPMInvoicePayment
     */
    addedByUserId?: number;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsPPMInvoicePayment
     */
    addedByUser?: string | null;
    /**
     * 
     * @type {JoblogicAPIModelsNominalCodeSearchItem}
     * @memberof JoblogicAPIModelsPPMInvoicePayment
     */
    nominalCode?: JoblogicAPIModelsNominalCodeSearchItem;
    /**
     * 
     * @type {JobLogicMicroserviceCoreContractInvoicePaymentType}
     * @memberof JoblogicAPIModelsPPMInvoicePayment
     */
    paymentType?: JobLogicMicroserviceCoreContractInvoicePaymentType;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsPPMInvoicePayment
     */
    paymentTypeOtherDescription?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsPPMInvoicePayment
     */
    externalReference?: string | null;
}



/**
 * Check if a given object implements the JoblogicAPIModelsPPMInvoicePayment interface.
 */
export function instanceOfJoblogicAPIModelsPPMInvoicePayment(value: object): value is JoblogicAPIModelsPPMInvoicePayment {
    return true;
}

export function JoblogicAPIModelsPPMInvoicePaymentFromJSON(json: any): JoblogicAPIModelsPPMInvoicePayment {
    return JoblogicAPIModelsPPMInvoicePaymentFromJSONTyped(json, false);
}

export function JoblogicAPIModelsPPMInvoicePaymentFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsPPMInvoicePayment {
    if (json == null) {
        return json;
    }
    return {
        
        'pPMInvoiceId': json['PPMInvoiceId'] == null ? undefined : json['PPMInvoiceId'],
        'id': json['Id'] == null ? undefined : json['Id'],
        'amount': json['Amount'] == null ? undefined : json['Amount'],
        'date': json['Date'] == null ? undefined : (new Date(json['Date'])),
        'notes': json['Notes'] == null ? undefined : json['Notes'],
        'addedByUserId': json['AddedByUserId'] == null ? undefined : json['AddedByUserId'],
        'addedByUser': json['AddedByUser'] == null ? undefined : json['AddedByUser'],
        'nominalCode': json['NominalCode'] == null ? undefined : JoblogicAPIModelsNominalCodeSearchItemFromJSON(json['NominalCode']),
        'paymentType': json['PaymentType'] == null ? undefined : JobLogicMicroserviceCoreContractInvoicePaymentTypeFromJSON(json['PaymentType']),
        'paymentTypeOtherDescription': json['PaymentType_Other_Description'] == null ? undefined : json['PaymentType_Other_Description'],
        'externalReference': json['ExternalReference'] == null ? undefined : json['ExternalReference'],
    };
}

export function JoblogicAPIModelsPPMInvoicePaymentToJSON(json: any): JoblogicAPIModelsPPMInvoicePayment {
    return JoblogicAPIModelsPPMInvoicePaymentToJSONTyped(json, false);
}

export function JoblogicAPIModelsPPMInvoicePaymentToJSONTyped(value?: JoblogicAPIModelsPPMInvoicePayment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'PPMInvoiceId': value['pPMInvoiceId'],
        'Id': value['id'],
        'Amount': value['amount'],
        'Date': value['date'] == null ? value['date'] : value['date'].toISOString(),
        'Notes': value['notes'],
        'AddedByUserId': value['addedByUserId'],
        'AddedByUser': value['addedByUser'],
        'NominalCode': JoblogicAPIModelsNominalCodeSearchItemToJSON(value['nominalCode']),
        'PaymentType': JobLogicMicroserviceCoreContractInvoicePaymentTypeToJSON(value['paymentType']),
        'PaymentType_Other_Description': value['paymentTypeOtherDescription'],
        'ExternalReference': value['externalReference'],
    };
}

