/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JoblogicAPIModelsAssignedPermissionRequest } from './JoblogicAPIModelsAssignedPermissionRequest';
import {
    JoblogicAPIModelsAssignedPermissionRequestFromJSON,
    JoblogicAPIModelsAssignedPermissionRequestFromJSONTyped,
    JoblogicAPIModelsAssignedPermissionRequestToJSON,
    JoblogicAPIModelsAssignedPermissionRequestToJSONTyped,
} from './JoblogicAPIModelsAssignedPermissionRequest';
import type { JobLogicMicroserviceRoleContractPortalUserType } from './JobLogicMicroserviceRoleContractPortalUserType';
import {
    JobLogicMicroserviceRoleContractPortalUserTypeFromJSON,
    JobLogicMicroserviceRoleContractPortalUserTypeFromJSONTyped,
    JobLogicMicroserviceRoleContractPortalUserTypeToJSON,
    JobLogicMicroserviceRoleContractPortalUserTypeToJSONTyped,
} from './JobLogicMicroserviceRoleContractPortalUserType';

/**
 * 
 * @export
 * @interface JoblogicAPIModelsCreatePortalUserRequest
 */
export interface JoblogicAPIModelsCreatePortalUserRequest {
    /**
     * 
     * @type {JobLogicMicroserviceRoleContractPortalUserType}
     * @memberof JoblogicAPIModelsCreatePortalUserRequest
     */
    type: JobLogicMicroserviceRoleContractPortalUserType;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCreatePortalUserRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCreatePortalUserRequest
     */
    emailAddress: string;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCreatePortalUserRequest
     */
    address1?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCreatePortalUserRequest
     */
    address2?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCreatePortalUserRequest
     */
    address3?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCreatePortalUserRequest
     */
    address4?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCreatePortalUserRequest
     */
    postcode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCreatePortalUserRequest
     */
    countryCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCreatePortalUserRequest
     */
    telephone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCreatePortalUserRequest
     */
    mobile?: string | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof JoblogicAPIModelsCreatePortalUserRequest
     */
    assignedEntityIds: Array<number>;
    /**
     * 
     * @type {JoblogicAPIModelsAssignedPermissionRequest}
     * @memberof JoblogicAPIModelsCreatePortalUserRequest
     */
    assignedPermission: JoblogicAPIModelsAssignedPermissionRequest;
    /**
     * Contractor Id in Joblogic
     * @type {string}
     * @memberof JoblogicAPIModelsCreatePortalUserRequest
     */
    tenantId: string;
}



/**
 * Check if a given object implements the JoblogicAPIModelsCreatePortalUserRequest interface.
 */
export function instanceOfJoblogicAPIModelsCreatePortalUserRequest(value: object): value is JoblogicAPIModelsCreatePortalUserRequest {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('emailAddress' in value) || value['emailAddress'] === undefined) return false;
    if (!('assignedEntityIds' in value) || value['assignedEntityIds'] === undefined) return false;
    if (!('assignedPermission' in value) || value['assignedPermission'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    return true;
}

export function JoblogicAPIModelsCreatePortalUserRequestFromJSON(json: any): JoblogicAPIModelsCreatePortalUserRequest {
    return JoblogicAPIModelsCreatePortalUserRequestFromJSONTyped(json, false);
}

export function JoblogicAPIModelsCreatePortalUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsCreatePortalUserRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'type': JobLogicMicroserviceRoleContractPortalUserTypeFromJSON(json['Type']),
        'name': json['Name'],
        'emailAddress': json['EmailAddress'],
        'address1': json['Address1'] == null ? undefined : json['Address1'],
        'address2': json['Address2'] == null ? undefined : json['Address2'],
        'address3': json['Address3'] == null ? undefined : json['Address3'],
        'address4': json['Address4'] == null ? undefined : json['Address4'],
        'postcode': json['Postcode'] == null ? undefined : json['Postcode'],
        'countryCode': json['CountryCode'] == null ? undefined : json['CountryCode'],
        'telephone': json['Telephone'] == null ? undefined : json['Telephone'],
        'mobile': json['Mobile'] == null ? undefined : json['Mobile'],
        'assignedEntityIds': json['AssignedEntityIds'],
        'assignedPermission': JoblogicAPIModelsAssignedPermissionRequestFromJSON(json['AssignedPermission']),
        'tenantId': json['TenantId'],
    };
}

export function JoblogicAPIModelsCreatePortalUserRequestToJSON(json: any): JoblogicAPIModelsCreatePortalUserRequest {
    return JoblogicAPIModelsCreatePortalUserRequestToJSONTyped(json, false);
}

export function JoblogicAPIModelsCreatePortalUserRequestToJSONTyped(value?: JoblogicAPIModelsCreatePortalUserRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Type': JobLogicMicroserviceRoleContractPortalUserTypeToJSON(value['type']),
        'Name': value['name'],
        'EmailAddress': value['emailAddress'],
        'Address1': value['address1'],
        'Address2': value['address2'],
        'Address3': value['address3'],
        'Address4': value['address4'],
        'Postcode': value['postcode'],
        'CountryCode': value['countryCode'],
        'Telephone': value['telephone'],
        'Mobile': value['mobile'],
        'AssignedEntityIds': value['assignedEntityIds'],
        'AssignedPermission': JoblogicAPIModelsAssignedPermissionRequestToJSON(value['assignedPermission']),
        'TenantId': value['tenantId'],
    };
}

