/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JoblogicAPIModelsCreditLineRequestModel } from './JoblogicAPIModelsCreditLineRequestModel';
import {
    JoblogicAPIModelsCreditLineRequestModelFromJSON,
    JoblogicAPIModelsCreditLineRequestModelFromJSONTyped,
    JoblogicAPIModelsCreditLineRequestModelToJSON,
    JoblogicAPIModelsCreditLineRequestModelToJSONTyped,
} from './JoblogicAPIModelsCreditLineRequestModel';

/**
 * 
 * @export
 * @interface JoblogicAPIModelsCreateCreditRequest
 */
export interface JoblogicAPIModelsCreateCreditRequest {
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsCreateCreditRequest
     */
    invoiceId?: number;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsCreateCreditRequest
     */
    raisedByUserId?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof JoblogicAPIModelsCreateCreditRequest
     */
    creditOutstandingInvoiceLines?: boolean;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCreateCreditRequest
     */
    creditReason: string;
    /**
     * 
     * @type {Array<JoblogicAPIModelsCreditLineRequestModel>}
     * @memberof JoblogicAPIModelsCreateCreditRequest
     */
    lines?: Array<JoblogicAPIModelsCreditLineRequestModel> | null;
    /**
     * Contractor Id in Joblogic
     * @type {string}
     * @memberof JoblogicAPIModelsCreateCreditRequest
     */
    tenantId: string;
}

/**
 * Check if a given object implements the JoblogicAPIModelsCreateCreditRequest interface.
 */
export function instanceOfJoblogicAPIModelsCreateCreditRequest(value: object): value is JoblogicAPIModelsCreateCreditRequest {
    if (!('creditReason' in value) || value['creditReason'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    return true;
}

export function JoblogicAPIModelsCreateCreditRequestFromJSON(json: any): JoblogicAPIModelsCreateCreditRequest {
    return JoblogicAPIModelsCreateCreditRequestFromJSONTyped(json, false);
}

export function JoblogicAPIModelsCreateCreditRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsCreateCreditRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'invoiceId': json['InvoiceId'] == null ? undefined : json['InvoiceId'],
        'raisedByUserId': json['RaisedByUserId'] == null ? undefined : json['RaisedByUserId'],
        'creditOutstandingInvoiceLines': json['CreditOutstandingInvoiceLines'] == null ? undefined : json['CreditOutstandingInvoiceLines'],
        'creditReason': json['CreditReason'],
        'lines': json['Lines'] == null ? undefined : ((json['Lines'] as Array<any>).map(JoblogicAPIModelsCreditLineRequestModelFromJSON)),
        'tenantId': json['TenantId'],
    };
}

export function JoblogicAPIModelsCreateCreditRequestToJSON(json: any): JoblogicAPIModelsCreateCreditRequest {
    return JoblogicAPIModelsCreateCreditRequestToJSONTyped(json, false);
}

export function JoblogicAPIModelsCreateCreditRequestToJSONTyped(value?: JoblogicAPIModelsCreateCreditRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'InvoiceId': value['invoiceId'],
        'RaisedByUserId': value['raisedByUserId'],
        'CreditOutstandingInvoiceLines': value['creditOutstandingInvoiceLines'],
        'CreditReason': value['creditReason'],
        'Lines': value['lines'] == null ? undefined : ((value['lines'] as Array<any>).map(JoblogicAPIModelsCreditLineRequestModelToJSON)),
        'TenantId': value['tenantId'],
    };
}

