/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JoblogicAPIModelsResponseGetLinkPPMContractResponsePPMContractModel
 */
export interface JoblogicAPIModelsResponseGetLinkPPMContractResponsePPMContractModel {
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsResponseGetLinkPPMContractResponsePPMContractModel
     */
    pPMContractUniqueId?: string;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsResponseGetLinkPPMContractResponsePPMContractModel
     */
    pPMContractNumber?: string | null;
}

/**
 * Check if a given object implements the JoblogicAPIModelsResponseGetLinkPPMContractResponsePPMContractModel interface.
 */
export function instanceOfJoblogicAPIModelsResponseGetLinkPPMContractResponsePPMContractModel(value: object): value is JoblogicAPIModelsResponseGetLinkPPMContractResponsePPMContractModel {
    return true;
}

export function JoblogicAPIModelsResponseGetLinkPPMContractResponsePPMContractModelFromJSON(json: any): JoblogicAPIModelsResponseGetLinkPPMContractResponsePPMContractModel {
    return JoblogicAPIModelsResponseGetLinkPPMContractResponsePPMContractModelFromJSONTyped(json, false);
}

export function JoblogicAPIModelsResponseGetLinkPPMContractResponsePPMContractModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsResponseGetLinkPPMContractResponsePPMContractModel {
    if (json == null) {
        return json;
    }
    return {
        
        'pPMContractUniqueId': json['PPMContractUniqueId'] == null ? undefined : json['PPMContractUniqueId'],
        'pPMContractNumber': json['PPMContractNumber'] == null ? undefined : json['PPMContractNumber'],
    };
}

export function JoblogicAPIModelsResponseGetLinkPPMContractResponsePPMContractModelToJSON(json: any): JoblogicAPIModelsResponseGetLinkPPMContractResponsePPMContractModel {
    return JoblogicAPIModelsResponseGetLinkPPMContractResponsePPMContractModelToJSONTyped(json, false);
}

export function JoblogicAPIModelsResponseGetLinkPPMContractResponsePPMContractModelToJSONTyped(value?: JoblogicAPIModelsResponseGetLinkPPMContractResponsePPMContractModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'PPMContractUniqueId': value['pPMContractUniqueId'],
        'PPMContractNumber': value['pPMContractNumber'],
    };
}

