/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JoblogicAPIModelsUpdatePartResponse
 */
export interface JoblogicAPIModelsUpdatePartResponse {
    /**
     * The Id of the Part in the Joblogic system (Not the ExternalId)
     * @type {string}
     * @memberof JoblogicAPIModelsUpdatePartResponse
     */
    id?: string;
    /**
     * Part Number used to identify the part inside Joblogic
     * @type {string}
     * @memberof JoblogicAPIModelsUpdatePartResponse
     */
    number?: string | null;
    /**
     * e.g. Screw, Nail, Pipe Length etc
     * @type {string}
     * @memberof JoblogicAPIModelsUpdatePartResponse
     */
    description?: string | null;
    /**
     * The amount of Parts per unit of measure e.g. 100 screws per bag
     * @type {number}
     * @memberof JoblogicAPIModelsUpdatePartResponse
     */
    quantity?: number;
    /**
     * How a unit of the part is to be measured, i.e. Individually, Bag, Carton etc
     * @type {string}
     * @memberof JoblogicAPIModelsUpdatePartResponse
     */
    unitOfMeasure?: string | null;
    /**
     * The cost price per the unit of measurement
     * @type {number}
     * @memberof JoblogicAPIModelsUpdatePartResponse
     */
    pricePerUnit?: number;
    /**
     * The sell price per the unit of measurement
     * @type {number}
     * @memberof JoblogicAPIModelsUpdatePartResponse
     */
    sellPerUnit?: number | null;
}

/**
 * Check if a given object implements the JoblogicAPIModelsUpdatePartResponse interface.
 */
export function instanceOfJoblogicAPIModelsUpdatePartResponse(value: object): value is JoblogicAPIModelsUpdatePartResponse {
    return true;
}

export function JoblogicAPIModelsUpdatePartResponseFromJSON(json: any): JoblogicAPIModelsUpdatePartResponse {
    return JoblogicAPIModelsUpdatePartResponseFromJSONTyped(json, false);
}

export function JoblogicAPIModelsUpdatePartResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsUpdatePartResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['Id'] == null ? undefined : json['Id'],
        'number': json['Number'] == null ? undefined : json['Number'],
        'description': json['Description'] == null ? undefined : json['Description'],
        'quantity': json['Quantity'] == null ? undefined : json['Quantity'],
        'unitOfMeasure': json['UnitOfMeasure'] == null ? undefined : json['UnitOfMeasure'],
        'pricePerUnit': json['PricePerUnit'] == null ? undefined : json['PricePerUnit'],
        'sellPerUnit': json['SellPerUnit'] == null ? undefined : json['SellPerUnit'],
    };
}

export function JoblogicAPIModelsUpdatePartResponseToJSON(json: any): JoblogicAPIModelsUpdatePartResponse {
    return JoblogicAPIModelsUpdatePartResponseToJSONTyped(json, false);
}

export function JoblogicAPIModelsUpdatePartResponseToJSONTyped(value?: JoblogicAPIModelsUpdatePartResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Id': value['id'],
        'Number': value['number'],
        'Description': value['description'],
        'Quantity': value['quantity'],
        'UnitOfMeasure': value['unitOfMeasure'],
        'PricePerUnit': value['pricePerUnit'],
        'SellPerUnit': value['sellPerUnit'],
    };
}

