/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JoblogicAPIModelsUpdateAssetConditionRequest
 */
export interface JoblogicAPIModelsUpdateAssetConditionRequest {
    /**
     * The UniqueId of the Asset Condition in Joblogic
     * @type {string}
     * @memberof JoblogicAPIModelsUpdateAssetConditionRequest
     */
    uniqueId: string;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsUpdateAssetConditionRequest
     */
    condition?: string | null;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsUpdateAssetConditionRequest
     */
    order?: number | null;
    /**
     * Contractor Id in Joblogic
     * @type {string}
     * @memberof JoblogicAPIModelsUpdateAssetConditionRequest
     */
    tenantId: string;
}

/**
 * Check if a given object implements the JoblogicAPIModelsUpdateAssetConditionRequest interface.
 */
export function instanceOfJoblogicAPIModelsUpdateAssetConditionRequest(value: object): value is JoblogicAPIModelsUpdateAssetConditionRequest {
    if (!('uniqueId' in value) || value['uniqueId'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    return true;
}

export function JoblogicAPIModelsUpdateAssetConditionRequestFromJSON(json: any): JoblogicAPIModelsUpdateAssetConditionRequest {
    return JoblogicAPIModelsUpdateAssetConditionRequestFromJSONTyped(json, false);
}

export function JoblogicAPIModelsUpdateAssetConditionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsUpdateAssetConditionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'uniqueId': json['UniqueId'],
        'condition': json['Condition'] == null ? undefined : json['Condition'],
        'order': json['Order'] == null ? undefined : json['Order'],
        'tenantId': json['TenantId'],
    };
}

export function JoblogicAPIModelsUpdateAssetConditionRequestToJSON(json: any): JoblogicAPIModelsUpdateAssetConditionRequest {
    return JoblogicAPIModelsUpdateAssetConditionRequestToJSONTyped(json, false);
}

export function JoblogicAPIModelsUpdateAssetConditionRequestToJSONTyped(value?: JoblogicAPIModelsUpdateAssetConditionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'UniqueId': value['uniqueId'],
        'Condition': value['condition'],
        'Order': value['order'],
        'TenantId': value['tenantId'],
    };
}

