/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobLogicMicroserviceFileContractAttachmentQualityOption } from './JobLogicMicroserviceFileContractAttachmentQualityOption';
import {
    JobLogicMicroserviceFileContractAttachmentQualityOptionFromJSON,
    JobLogicMicroserviceFileContractAttachmentQualityOptionFromJSONTyped,
    JobLogicMicroserviceFileContractAttachmentQualityOptionToJSON,
    JobLogicMicroserviceFileContractAttachmentQualityOptionToJSONTyped,
} from './JobLogicMicroserviceFileContractAttachmentQualityOption';

/**
 * 
 * @export
 * @interface JoblogicAPIModelsGenerateAttachmentUriRequest
 */
export interface JoblogicAPIModelsGenerateAttachmentUriRequest {
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsGenerateAttachmentUriRequest
     */
    attachmentUniqueId?: string;
    /**
     * 
     * @type {JobLogicMicroserviceFileContractAttachmentQualityOption}
     * @memberof JoblogicAPIModelsGenerateAttachmentUriRequest
     */
    attachmentQuality?: JobLogicMicroserviceFileContractAttachmentQualityOption;
    /**
     * 
     * @type {Date}
     * @memberof JoblogicAPIModelsGenerateAttachmentUriRequest
     */
    expiryDate?: Date | null;
    /**
     * Contractor Id in Joblogic
     * @type {string}
     * @memberof JoblogicAPIModelsGenerateAttachmentUriRequest
     */
    tenantId: string;
}



/**
 * Check if a given object implements the JoblogicAPIModelsGenerateAttachmentUriRequest interface.
 */
export function instanceOfJoblogicAPIModelsGenerateAttachmentUriRequest(value: object): value is JoblogicAPIModelsGenerateAttachmentUriRequest {
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    return true;
}

export function JoblogicAPIModelsGenerateAttachmentUriRequestFromJSON(json: any): JoblogicAPIModelsGenerateAttachmentUriRequest {
    return JoblogicAPIModelsGenerateAttachmentUriRequestFromJSONTyped(json, false);
}

export function JoblogicAPIModelsGenerateAttachmentUriRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsGenerateAttachmentUriRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'attachmentUniqueId': json['AttachmentUniqueId'] == null ? undefined : json['AttachmentUniqueId'],
        'attachmentQuality': json['AttachmentQuality'] == null ? undefined : JobLogicMicroserviceFileContractAttachmentQualityOptionFromJSON(json['AttachmentQuality']),
        'expiryDate': json['ExpiryDate'] == null ? undefined : (new Date(json['ExpiryDate'])),
        'tenantId': json['TenantId'],
    };
}

export function JoblogicAPIModelsGenerateAttachmentUriRequestToJSON(json: any): JoblogicAPIModelsGenerateAttachmentUriRequest {
    return JoblogicAPIModelsGenerateAttachmentUriRequestToJSONTyped(json, false);
}

export function JoblogicAPIModelsGenerateAttachmentUriRequestToJSONTyped(value?: JoblogicAPIModelsGenerateAttachmentUriRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'AttachmentUniqueId': value['attachmentUniqueId'],
        'AttachmentQuality': JobLogicMicroserviceFileContractAttachmentQualityOptionToJSON(value['attachmentQuality']),
        'ExpiryDate': value['expiryDate'] == null ? value['expiryDate'] : value['expiryDate'].toISOString(),
        'TenantId': value['tenantId'],
    };
}

