/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JoblogicAPIModelsExportReportToFileJobResponse
 */
export interface JoblogicAPIModelsExportReportToFileJobResponse {
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsExportReportToFileJobResponse
     */
    exportId?: string;
}

/**
 * Check if a given object implements the JoblogicAPIModelsExportReportToFileJobResponse interface.
 */
export function instanceOfJoblogicAPIModelsExportReportToFileJobResponse(value: object): value is JoblogicAPIModelsExportReportToFileJobResponse {
    return true;
}

export function JoblogicAPIModelsExportReportToFileJobResponseFromJSON(json: any): JoblogicAPIModelsExportReportToFileJobResponse {
    return JoblogicAPIModelsExportReportToFileJobResponseFromJSONTyped(json, false);
}

export function JoblogicAPIModelsExportReportToFileJobResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsExportReportToFileJobResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'exportId': json['ExportId'] == null ? undefined : json['ExportId'],
    };
}

export function JoblogicAPIModelsExportReportToFileJobResponseToJSON(json: any): JoblogicAPIModelsExportReportToFileJobResponse {
    return JoblogicAPIModelsExportReportToFileJobResponseToJSONTyped(json, false);
}

export function JoblogicAPIModelsExportReportToFileJobResponseToJSONTyped(value?: JoblogicAPIModelsExportReportToFileJobResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ExportId': value['exportId'],
    };
}

