/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JoblogicAPIModelsPurchaseOrderItemResponse } from './JoblogicAPIModelsPurchaseOrderItemResponse';
import {
    JoblogicAPIModelsPurchaseOrderItemResponseFromJSON,
    JoblogicAPIModelsPurchaseOrderItemResponseFromJSONTyped,
    JoblogicAPIModelsPurchaseOrderItemResponseToJSON,
    JoblogicAPIModelsPurchaseOrderItemResponseToJSONTyped,
} from './JoblogicAPIModelsPurchaseOrderItemResponse';

/**
 * 
 * @export
 * @interface JoblogicAPIModelsSearchPurchaseOrderResponse
 */
export interface JoblogicAPIModelsSearchPurchaseOrderResponse {
    /**
     * 
     * @type {Array<JoblogicAPIModelsPurchaseOrderItemResponse>}
     * @memberof JoblogicAPIModelsSearchPurchaseOrderResponse
     */
    items?: Array<JoblogicAPIModelsPurchaseOrderItemResponse> | null;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsSearchPurchaseOrderResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsSearchPurchaseOrderResponse
     */
    pageIndex?: number;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsSearchPurchaseOrderResponse
     */
    pageSize?: number;
}

/**
 * Check if a given object implements the JoblogicAPIModelsSearchPurchaseOrderResponse interface.
 */
export function instanceOfJoblogicAPIModelsSearchPurchaseOrderResponse(value: object): value is JoblogicAPIModelsSearchPurchaseOrderResponse {
    return true;
}

export function JoblogicAPIModelsSearchPurchaseOrderResponseFromJSON(json: any): JoblogicAPIModelsSearchPurchaseOrderResponse {
    return JoblogicAPIModelsSearchPurchaseOrderResponseFromJSONTyped(json, false);
}

export function JoblogicAPIModelsSearchPurchaseOrderResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsSearchPurchaseOrderResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['Items'] == null ? undefined : ((json['Items'] as Array<any>).map(JoblogicAPIModelsPurchaseOrderItemResponseFromJSON)),
        'totalCount': json['TotalCount'] == null ? undefined : json['TotalCount'],
        'pageIndex': json['PageIndex'] == null ? undefined : json['PageIndex'],
        'pageSize': json['PageSize'] == null ? undefined : json['PageSize'],
    };
}

export function JoblogicAPIModelsSearchPurchaseOrderResponseToJSON(json: any): JoblogicAPIModelsSearchPurchaseOrderResponse {
    return JoblogicAPIModelsSearchPurchaseOrderResponseToJSONTyped(json, false);
}

export function JoblogicAPIModelsSearchPurchaseOrderResponseToJSONTyped(value?: JoblogicAPIModelsSearchPurchaseOrderResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(JoblogicAPIModelsPurchaseOrderItemResponseToJSON)),
        'TotalCount': value['totalCount'],
        'PageIndex': value['pageIndex'],
        'PageSize': value['pageSize'],
    };
}

