/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JoblogicAPIModelsSearchPlannerRequest
 */
export interface JoblogicAPIModelsSearchPlannerRequest {
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsSearchPlannerRequest
     */
    startDate: string;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsSearchPlannerRequest
     */
    endDate: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof JoblogicAPIModelsSearchPlannerRequest
     */
    engineerIds?: Array<number> | null;
    /**
     * 
     * @type {boolean}
     * @memberof JoblogicAPIModelsSearchPlannerRequest
     */
    includeCancelledVisits?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof JoblogicAPIModelsSearchPlannerRequest
     */
    includeCompletedVisits?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof JoblogicAPIModelsSearchPlannerRequest
     */
    includeRejectedVisits?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof JoblogicAPIModelsSearchPlannerRequest
     */
    includeReactiveVisits?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof JoblogicAPIModelsSearchPlannerRequest
     */
    includePPMVisits?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof JoblogicAPIModelsSearchPlannerRequest
     */
    includeNonProductiveTime?: boolean;
    /**
     * Contractor Id in Joblogic
     * @type {string}
     * @memberof JoblogicAPIModelsSearchPlannerRequest
     */
    tenantId: string;
}

/**
 * Check if a given object implements the JoblogicAPIModelsSearchPlannerRequest interface.
 */
export function instanceOfJoblogicAPIModelsSearchPlannerRequest(value: object): value is JoblogicAPIModelsSearchPlannerRequest {
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    if (!('endDate' in value) || value['endDate'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    return true;
}

export function JoblogicAPIModelsSearchPlannerRequestFromJSON(json: any): JoblogicAPIModelsSearchPlannerRequest {
    return JoblogicAPIModelsSearchPlannerRequestFromJSONTyped(json, false);
}

export function JoblogicAPIModelsSearchPlannerRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsSearchPlannerRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'startDate': json['StartDate'],
        'endDate': json['EndDate'],
        'engineerIds': json['EngineerIds'] == null ? undefined : json['EngineerIds'],
        'includeCancelledVisits': json['IncludeCancelledVisits'] == null ? undefined : json['IncludeCancelledVisits'],
        'includeCompletedVisits': json['IncludeCompletedVisits'] == null ? undefined : json['IncludeCompletedVisits'],
        'includeRejectedVisits': json['IncludeRejectedVisits'] == null ? undefined : json['IncludeRejectedVisits'],
        'includeReactiveVisits': json['IncludeReactiveVisits'] == null ? undefined : json['IncludeReactiveVisits'],
        'includePPMVisits': json['IncludePPMVisits'] == null ? undefined : json['IncludePPMVisits'],
        'includeNonProductiveTime': json['IncludeNonProductiveTime'] == null ? undefined : json['IncludeNonProductiveTime'],
        'tenantId': json['TenantId'],
    };
}

export function JoblogicAPIModelsSearchPlannerRequestToJSON(json: any): JoblogicAPIModelsSearchPlannerRequest {
    return JoblogicAPIModelsSearchPlannerRequestToJSONTyped(json, false);
}

export function JoblogicAPIModelsSearchPlannerRequestToJSONTyped(value?: JoblogicAPIModelsSearchPlannerRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'StartDate': value['startDate'],
        'EndDate': value['endDate'],
        'EngineerIds': value['engineerIds'],
        'IncludeCancelledVisits': value['includeCancelledVisits'],
        'IncludeCompletedVisits': value['includeCompletedVisits'],
        'IncludeRejectedVisits': value['includeRejectedVisits'],
        'IncludeReactiveVisits': value['includeReactiveVisits'],
        'IncludePPMVisits': value['includePPMVisits'],
        'IncludeNonProductiveTime': value['includeNonProductiveTime'],
        'TenantId': value['tenantId'],
    };
}

