/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobLogicMicroserviceCoreContractEnumsSearchCondtionOption } from './JobLogicMicroserviceCoreContractEnumsSearchCondtionOption';
import {
    JobLogicMicroserviceCoreContractEnumsSearchCondtionOptionFromJSON,
    JobLogicMicroserviceCoreContractEnumsSearchCondtionOptionFromJSONTyped,
    JobLogicMicroserviceCoreContractEnumsSearchCondtionOptionToJSON,
    JobLogicMicroserviceCoreContractEnumsSearchCondtionOptionToJSONTyped,
} from './JobLogicMicroserviceCoreContractEnumsSearchCondtionOption';
import type { JobLogicMicroserviceCoreContractJobOrderBy } from './JobLogicMicroserviceCoreContractJobOrderBy';
import {
    JobLogicMicroserviceCoreContractJobOrderByFromJSON,
    JobLogicMicroserviceCoreContractJobOrderByFromJSONTyped,
    JobLogicMicroserviceCoreContractJobOrderByToJSON,
    JobLogicMicroserviceCoreContractJobOrderByToJSONTyped,
} from './JobLogicMicroserviceCoreContractJobOrderBy';

/**
 * 
 * @export
 * @interface JoblogicAPIModelsSearchJobRequest
 */
export interface JoblogicAPIModelsSearchJobRequest {
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsSearchJobRequest
     */
    customerId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsSearchJobRequest
     */
    siteId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsSearchJobRequest
     */
    customerUniqueId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsSearchJobRequest
     */
    siteUniqueId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsSearchJobRequest
     */
    startDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsSearchJobRequest
     */
    endDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsSearchJobRequest
     */
    startLoggedDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsSearchJobRequest
     */
    endLoggedDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsSearchJobRequest
     */
    startCompleteDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsSearchJobRequest
     */
    endCompleteDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsSearchJobRequest
     */
    statusIds?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsSearchJobRequest
     */
    categoryIds?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsSearchJobRequest
     */
    typeIds?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsSearchJobRequest
     */
    priorityIds?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsSearchJobRequest
     */
    ownerIds?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsSearchJobRequest
     */
    areaIds?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsSearchJobRequest
     */
    tradeIds?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsSearchJobRequest
     */
    excludeTagIds?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof JoblogicAPIModelsSearchJobRequest
     */
    onlyIncludePrimaryJobTrade?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof JoblogicAPIModelsSearchJobRequest
     */
    includeReactiveJobs?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof JoblogicAPIModelsSearchJobRequest
     */
    includePPMJobs?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof JoblogicAPIModelsSearchJobRequest
     */
    includePortalLink?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof JoblogicAPIModelsSearchJobRequest
     */
    includeTags?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof JoblogicAPIModelsSearchJobRequest
     */
    includeContacts?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof JoblogicAPIModelsSearchJobRequest
     */
    includeNotes?: boolean;
    /**
     * 
     * @type {Array<number>}
     * @memberof JoblogicAPIModelsSearchJobRequest
     */
    customerContractIds?: Array<number> | null;
    /**
     * 
     * @type {JobLogicMicroserviceCoreContractJobOrderBy}
     * @memberof JoblogicAPIModelsSearchJobRequest
     */
    orderBy?: JobLogicMicroserviceCoreContractJobOrderBy;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsSearchJobRequest
     */
    searchTerm?: string | null;
    /**
     * 
     * @type {JobLogicMicroserviceCoreContractEnumsSearchCondtionOption}
     * @memberof JoblogicAPIModelsSearchJobRequest
     */
    searchCondition?: JobLogicMicroserviceCoreContractEnumsSearchCondtionOption;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsSearchJobRequest
     */
    tagIds?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof JoblogicAPIModelsSearchJobRequest
     */
    includeInactive?: boolean;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsSearchJobRequest
     */
    pageIndex?: number;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsSearchJobRequest
     */
    pageSize?: number;
    /**
     * Contractor Id in Joblogic
     * @type {string}
     * @memberof JoblogicAPIModelsSearchJobRequest
     */
    tenantId: string;
}



/**
 * Check if a given object implements the JoblogicAPIModelsSearchJobRequest interface.
 */
export function instanceOfJoblogicAPIModelsSearchJobRequest(value: object): value is JoblogicAPIModelsSearchJobRequest {
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    return true;
}

export function JoblogicAPIModelsSearchJobRequestFromJSON(json: any): JoblogicAPIModelsSearchJobRequest {
    return JoblogicAPIModelsSearchJobRequestFromJSONTyped(json, false);
}

export function JoblogicAPIModelsSearchJobRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsSearchJobRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'customerId': json['CustomerId'] == null ? undefined : json['CustomerId'],
        'siteId': json['SiteId'] == null ? undefined : json['SiteId'],
        'customerUniqueId': json['CustomerUniqueId'] == null ? undefined : json['CustomerUniqueId'],
        'siteUniqueId': json['SiteUniqueId'] == null ? undefined : json['SiteUniqueId'],
        'startDate': json['StartDate'] == null ? undefined : json['StartDate'],
        'endDate': json['EndDate'] == null ? undefined : json['EndDate'],
        'startLoggedDate': json['StartLoggedDate'] == null ? undefined : json['StartLoggedDate'],
        'endLoggedDate': json['EndLoggedDate'] == null ? undefined : json['EndLoggedDate'],
        'startCompleteDate': json['StartCompleteDate'] == null ? undefined : json['StartCompleteDate'],
        'endCompleteDate': json['EndCompleteDate'] == null ? undefined : json['EndCompleteDate'],
        'statusIds': json['StatusIds'] == null ? undefined : json['StatusIds'],
        'categoryIds': json['CategoryIds'] == null ? undefined : json['CategoryIds'],
        'typeIds': json['TypeIds'] == null ? undefined : json['TypeIds'],
        'priorityIds': json['PriorityIds'] == null ? undefined : json['PriorityIds'],
        'ownerIds': json['OwnerIds'] == null ? undefined : json['OwnerIds'],
        'areaIds': json['AreaIds'] == null ? undefined : json['AreaIds'],
        'tradeIds': json['TradeIds'] == null ? undefined : json['TradeIds'],
        'excludeTagIds': json['ExcludeTagIds'] == null ? undefined : json['ExcludeTagIds'],
        'onlyIncludePrimaryJobTrade': json['OnlyIncludePrimaryJobTrade'] == null ? undefined : json['OnlyIncludePrimaryJobTrade'],
        'includeReactiveJobs': json['IncludeReactiveJobs'] == null ? undefined : json['IncludeReactiveJobs'],
        'includePPMJobs': json['IncludePPMJobs'] == null ? undefined : json['IncludePPMJobs'],
        'includePortalLink': json['IncludePortalLink'] == null ? undefined : json['IncludePortalLink'],
        'includeTags': json['IncludeTags'] == null ? undefined : json['IncludeTags'],
        'includeContacts': json['IncludeContacts'] == null ? undefined : json['IncludeContacts'],
        'includeNotes': json['IncludeNotes'] == null ? undefined : json['IncludeNotes'],
        'customerContractIds': json['CustomerContractIds'] == null ? undefined : json['CustomerContractIds'],
        'orderBy': json['OrderBy'] == null ? undefined : JobLogicMicroserviceCoreContractJobOrderByFromJSON(json['OrderBy']),
        'searchTerm': json['SearchTerm'] == null ? undefined : json['SearchTerm'],
        'searchCondition': json['SearchCondition'] == null ? undefined : JobLogicMicroserviceCoreContractEnumsSearchCondtionOptionFromJSON(json['SearchCondition']),
        'tagIds': json['TagIds'] == null ? undefined : json['TagIds'],
        'includeInactive': json['IncludeInactive'] == null ? undefined : json['IncludeInactive'],
        'pageIndex': json['PageIndex'] == null ? undefined : json['PageIndex'],
        'pageSize': json['PageSize'] == null ? undefined : json['PageSize'],
        'tenantId': json['TenantId'],
    };
}

export function JoblogicAPIModelsSearchJobRequestToJSON(json: any): JoblogicAPIModelsSearchJobRequest {
    return JoblogicAPIModelsSearchJobRequestToJSONTyped(json, false);
}

export function JoblogicAPIModelsSearchJobRequestToJSONTyped(value?: JoblogicAPIModelsSearchJobRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'CustomerId': value['customerId'],
        'SiteId': value['siteId'],
        'CustomerUniqueId': value['customerUniqueId'],
        'SiteUniqueId': value['siteUniqueId'],
        'StartDate': value['startDate'],
        'EndDate': value['endDate'],
        'StartLoggedDate': value['startLoggedDate'],
        'EndLoggedDate': value['endLoggedDate'],
        'StartCompleteDate': value['startCompleteDate'],
        'EndCompleteDate': value['endCompleteDate'],
        'StatusIds': value['statusIds'],
        'CategoryIds': value['categoryIds'],
        'TypeIds': value['typeIds'],
        'PriorityIds': value['priorityIds'],
        'OwnerIds': value['ownerIds'],
        'AreaIds': value['areaIds'],
        'TradeIds': value['tradeIds'],
        'ExcludeTagIds': value['excludeTagIds'],
        'OnlyIncludePrimaryJobTrade': value['onlyIncludePrimaryJobTrade'],
        'IncludeReactiveJobs': value['includeReactiveJobs'],
        'IncludePPMJobs': value['includePPMJobs'],
        'IncludePortalLink': value['includePortalLink'],
        'IncludeTags': value['includeTags'],
        'IncludeContacts': value['includeContacts'],
        'IncludeNotes': value['includeNotes'],
        'CustomerContractIds': value['customerContractIds'],
        'OrderBy': JobLogicMicroserviceCoreContractJobOrderByToJSON(value['orderBy']),
        'SearchTerm': value['searchTerm'],
        'SearchCondition': JobLogicMicroserviceCoreContractEnumsSearchCondtionOptionToJSON(value['searchCondition']),
        'TagIds': value['tagIds'],
        'IncludeInactive': value['includeInactive'],
        'PageIndex': value['pageIndex'],
        'PageSize': value['pageSize'],
        'TenantId': value['tenantId'],
    };
}

