/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JoblogicAPIModelsResponseGenerateFormsLogbookResponse
 */
export interface JoblogicAPIModelsResponseGenerateFormsLogbookResponse {
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsResponseGenerateFormsLogbookResponse
     */
    url?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsResponseGenerateFormsLogbookResponse
     */
    fileName?: string | null;
}

/**
 * Check if a given object implements the JoblogicAPIModelsResponseGenerateFormsLogbookResponse interface.
 */
export function instanceOfJoblogicAPIModelsResponseGenerateFormsLogbookResponse(value: object): value is JoblogicAPIModelsResponseGenerateFormsLogbookResponse {
    return true;
}

export function JoblogicAPIModelsResponseGenerateFormsLogbookResponseFromJSON(json: any): JoblogicAPIModelsResponseGenerateFormsLogbookResponse {
    return JoblogicAPIModelsResponseGenerateFormsLogbookResponseFromJSONTyped(json, false);
}

export function JoblogicAPIModelsResponseGenerateFormsLogbookResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsResponseGenerateFormsLogbookResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['Url'] == null ? undefined : json['Url'],
        'fileName': json['FileName'] == null ? undefined : json['FileName'],
    };
}

export function JoblogicAPIModelsResponseGenerateFormsLogbookResponseToJSON(json: any): JoblogicAPIModelsResponseGenerateFormsLogbookResponse {
    return JoblogicAPIModelsResponseGenerateFormsLogbookResponseToJSONTyped(json, false);
}

export function JoblogicAPIModelsResponseGenerateFormsLogbookResponseToJSONTyped(value?: JoblogicAPIModelsResponseGenerateFormsLogbookResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Url': value['url'],
        'FileName': value['fileName'],
    };
}

