/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobLogicMicroserviceCoreContractNoteVisibilityOption } from './JobLogicMicroserviceCoreContractNoteVisibilityOption';
import {
    JobLogicMicroserviceCoreContractNoteVisibilityOptionFromJSON,
    JobLogicMicroserviceCoreContractNoteVisibilityOptionFromJSONTyped,
    JobLogicMicroserviceCoreContractNoteVisibilityOptionToJSON,
    JobLogicMicroserviceCoreContractNoteVisibilityOptionToJSONTyped,
} from './JobLogicMicroserviceCoreContractNoteVisibilityOption';

/**
 * 
 * @export
 * @interface JoblogicAPIModelsNGBNGBJobResponseNGBNotes
 */
export interface JoblogicAPIModelsNGBNGBJobResponseNGBNotes {
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsNGBNGBJobResponseNGBNotes
     */
    notesDescription?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof JoblogicAPIModelsNGBNGBJobResponseNGBNotes
     */
    isPrivate?: boolean;
    /**
     * 
     * @type {JobLogicMicroserviceCoreContractNoteVisibilityOption}
     * @memberof JoblogicAPIModelsNGBNGBJobResponseNGBNotes
     */
    noteVisibility?: JobLogicMicroserviceCoreContractNoteVisibilityOption;
}



/**
 * Check if a given object implements the JoblogicAPIModelsNGBNGBJobResponseNGBNotes interface.
 */
export function instanceOfJoblogicAPIModelsNGBNGBJobResponseNGBNotes(value: object): value is JoblogicAPIModelsNGBNGBJobResponseNGBNotes {
    return true;
}

export function JoblogicAPIModelsNGBNGBJobResponseNGBNotesFromJSON(json: any): JoblogicAPIModelsNGBNGBJobResponseNGBNotes {
    return JoblogicAPIModelsNGBNGBJobResponseNGBNotesFromJSONTyped(json, false);
}

export function JoblogicAPIModelsNGBNGBJobResponseNGBNotesFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsNGBNGBJobResponseNGBNotes {
    if (json == null) {
        return json;
    }
    return {
        
        'notesDescription': json['NotesDescription'] == null ? undefined : json['NotesDescription'],
        'isPrivate': json['IsPrivate'] == null ? undefined : json['IsPrivate'],
        'noteVisibility': json['NoteVisibility'] == null ? undefined : JobLogicMicroserviceCoreContractNoteVisibilityOptionFromJSON(json['NoteVisibility']),
    };
}

export function JoblogicAPIModelsNGBNGBJobResponseNGBNotesToJSON(json: any): JoblogicAPIModelsNGBNGBJobResponseNGBNotes {
    return JoblogicAPIModelsNGBNGBJobResponseNGBNotesToJSONTyped(json, false);
}

export function JoblogicAPIModelsNGBNGBJobResponseNGBNotesToJSONTyped(value?: JoblogicAPIModelsNGBNGBJobResponseNGBNotes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'NotesDescription': value['notesDescription'],
        'IsPrivate': value['isPrivate'],
        'NoteVisibility': JobLogicMicroserviceCoreContractNoteVisibilityOptionToJSON(value['noteVisibility']),
    };
}

