/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JoblogicAPIModelsCancelQuoteRequest
 */
export interface JoblogicAPIModelsCancelQuoteRequest {
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCancelQuoteRequest
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsCancelQuoteRequest
     */
    reason?: string | null;
    /**
     * Contractor Id in Joblogic
     * @type {string}
     * @memberof JoblogicAPIModelsCancelQuoteRequest
     */
    tenantId: string;
}

/**
 * Check if a given object implements the JoblogicAPIModelsCancelQuoteRequest interface.
 */
export function instanceOfJoblogicAPIModelsCancelQuoteRequest(value: object): value is JoblogicAPIModelsCancelQuoteRequest {
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    return true;
}

export function JoblogicAPIModelsCancelQuoteRequestFromJSON(json: any): JoblogicAPIModelsCancelQuoteRequest {
    return JoblogicAPIModelsCancelQuoteRequestFromJSONTyped(json, false);
}

export function JoblogicAPIModelsCancelQuoteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsCancelQuoteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['Id'] == null ? undefined : json['Id'],
        'reason': json['Reason'] == null ? undefined : json['Reason'],
        'tenantId': json['TenantId'],
    };
}

export function JoblogicAPIModelsCancelQuoteRequestToJSON(json: any): JoblogicAPIModelsCancelQuoteRequest {
    return JoblogicAPIModelsCancelQuoteRequestToJSONTyped(json, false);
}

export function JoblogicAPIModelsCancelQuoteRequestToJSONTyped(value?: JoblogicAPIModelsCancelQuoteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Id': value['id'],
        'Reason': value['reason'],
        'TenantId': value['tenantId'],
    };
}

