/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JoblogicAPIModelsGetInvoiceByPurchaseOrderIdResponse Invoice Line } from './JoblogicAPIModelsGetInvoiceByPurchaseOrderIdResponse Invoice Line';
import {
    JoblogicAPIModelsGetInvoiceByPurchaseOrderIdResponse Invoice LineFromJSON,
    JoblogicAPIModelsGetInvoiceByPurchaseOrderIdResponse Invoice LineFromJSONTyped,
    JoblogicAPIModelsGetInvoiceByPurchaseOrderIdResponse Invoice LineToJSON,
    JoblogicAPIModelsGetInvoiceByPurchaseOrderIdResponse Invoice LineToJSONTyped,
} from './JoblogicAPIModelsGetInvoiceByPurchaseOrderIdResponse Invoice Line';
import type { JobLogicMicroserviceCoreContractSubContractorInvoiceType } from './JobLogicMicroserviceCoreContractSubContractorInvoiceType';
import {
    JobLogicMicroserviceCoreContractSubContractorInvoiceTypeFromJSON,
    JobLogicMicroserviceCoreContractSubContractorInvoiceTypeFromJSONTyped,
    JobLogicMicroserviceCoreContractSubContractorInvoiceTypeToJSON,
    JobLogicMicroserviceCoreContractSubContractorInvoiceTypeToJSONTyped,
} from './JobLogicMicroserviceCoreContractSubContractorInvoiceType';

/**
 * 
 * @export
 * @interface JoblogicAPIModelsGetInvoiceByPurchaseOrderIdResponseInvoice
 */
export interface JoblogicAPIModelsGetInvoiceByPurchaseOrderIdResponseInvoice {
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsGetInvoiceByPurchaseOrderIdResponseInvoice
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsGetInvoiceByPurchaseOrderIdResponseInvoice
     */
    purchaseOrderId?: string;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsGetInvoiceByPurchaseOrderIdResponseInvoice
     */
    invoiceNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsGetInvoiceByPurchaseOrderIdResponseInvoice
     */
    referenceNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsGetInvoiceByPurchaseOrderIdResponseInvoice
     */
    invoiceDate?: string | null;
    /**
     * 
     * @type {JobLogicMicroserviceCoreContractSubContractorInvoiceType}
     * @memberof JoblogicAPIModelsGetInvoiceByPurchaseOrderIdResponseInvoice
     */
    type?: JobLogicMicroserviceCoreContractSubContractorInvoiceType;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsGetInvoiceByPurchaseOrderIdResponseInvoice
     */
    typeDescription?: string | null;
    /**
     * 
     * @type {Array<JoblogicAPIModelsGetInvoiceByPurchaseOrderIdResponse Invoice Line>}
     * @memberof JoblogicAPIModelsGetInvoiceByPurchaseOrderIdResponseInvoice
     */
    lines?: Array<JoblogicAPIModelsGetInvoiceByPurchaseOrderIdResponse Invoice Line> | null;
}



/**
 * Check if a given object implements the JoblogicAPIModelsGetInvoiceByPurchaseOrderIdResponseInvoice interface.
 */
export function instanceOfJoblogicAPIModelsGetInvoiceByPurchaseOrderIdResponseInvoice(value: object): value is JoblogicAPIModelsGetInvoiceByPurchaseOrderIdResponseInvoice {
    return true;
}

export function JoblogicAPIModelsGetInvoiceByPurchaseOrderIdResponseInvoiceFromJSON(json: any): JoblogicAPIModelsGetInvoiceByPurchaseOrderIdResponseInvoice {
    return JoblogicAPIModelsGetInvoiceByPurchaseOrderIdResponseInvoiceFromJSONTyped(json, false);
}

export function JoblogicAPIModelsGetInvoiceByPurchaseOrderIdResponseInvoiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsGetInvoiceByPurchaseOrderIdResponseInvoice {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['Id'] == null ? undefined : json['Id'],
        'purchaseOrderId': json['PurchaseOrderId'] == null ? undefined : json['PurchaseOrderId'],
        'invoiceNumber': json['InvoiceNumber'] == null ? undefined : json['InvoiceNumber'],
        'referenceNumber': json['ReferenceNumber'] == null ? undefined : json['ReferenceNumber'],
        'invoiceDate': json['InvoiceDate'] == null ? undefined : json['InvoiceDate'],
        'type': json['Type'] == null ? undefined : JobLogicMicroserviceCoreContractSubContractorInvoiceTypeFromJSON(json['Type']),
        'typeDescription': json['TypeDescription'] == null ? undefined : json['TypeDescription'],
        'lines': json['Lines'] == null ? undefined : ((json['Lines'] as Array<any>).map(JoblogicAPIModelsGetInvoiceByPurchaseOrderIdResponse Invoice LineFromJSON)),
    };
}

export function JoblogicAPIModelsGetInvoiceByPurchaseOrderIdResponseInvoiceToJSON(json: any): JoblogicAPIModelsGetInvoiceByPurchaseOrderIdResponseInvoice {
    return JoblogicAPIModelsGetInvoiceByPurchaseOrderIdResponseInvoiceToJSONTyped(json, false);
}

export function JoblogicAPIModelsGetInvoiceByPurchaseOrderIdResponseInvoiceToJSONTyped(value?: JoblogicAPIModelsGetInvoiceByPurchaseOrderIdResponseInvoice | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Id': value['id'],
        'PurchaseOrderId': value['purchaseOrderId'],
        'InvoiceNumber': value['invoiceNumber'],
        'ReferenceNumber': value['referenceNumber'],
        'InvoiceDate': value['invoiceDate'],
        'Type': JobLogicMicroserviceCoreContractSubContractorInvoiceTypeToJSON(value['type']),
        'TypeDescription': value['typeDescription'],
        'Lines': value['lines'] == null ? undefined : ((value['lines'] as Array<any>).map(JoblogicAPIModelsGetInvoiceByPurchaseOrderIdResponse Invoice LineToJSON)),
    };
}

