/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JoblogicAPIModelsGetAllCGroupInvoicePaymentsItem } from './JoblogicAPIModelsGetAllCGroupInvoicePaymentsItem';
import {
    JoblogicAPIModelsGetAllCGroupInvoicePaymentsItemFromJSON,
    JoblogicAPIModelsGetAllCGroupInvoicePaymentsItemFromJSONTyped,
    JoblogicAPIModelsGetAllCGroupInvoicePaymentsItemToJSON,
    JoblogicAPIModelsGetAllCGroupInvoicePaymentsItemToJSONTyped,
} from './JoblogicAPIModelsGetAllCGroupInvoicePaymentsItem';

/**
 * 
 * @export
 * @interface JoblogicAPIModelsGetAllCGroupInvoicePayments
 */
export interface JoblogicAPIModelsGetAllCGroupInvoicePayments {
    /**
     * 
     * @type {Array<JoblogicAPIModelsGetAllCGroupInvoicePaymentsItem>}
     * @memberof JoblogicAPIModelsGetAllCGroupInvoicePayments
     */
    items?: Array<JoblogicAPIModelsGetAllCGroupInvoicePaymentsItem> | null;
}

/**
 * Check if a given object implements the JoblogicAPIModelsGetAllCGroupInvoicePayments interface.
 */
export function instanceOfJoblogicAPIModelsGetAllCGroupInvoicePayments(value: object): value is JoblogicAPIModelsGetAllCGroupInvoicePayments {
    return true;
}

export function JoblogicAPIModelsGetAllCGroupInvoicePaymentsFromJSON(json: any): JoblogicAPIModelsGetAllCGroupInvoicePayments {
    return JoblogicAPIModelsGetAllCGroupInvoicePaymentsFromJSONTyped(json, false);
}

export function JoblogicAPIModelsGetAllCGroupInvoicePaymentsFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsGetAllCGroupInvoicePayments {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['Items'] == null ? undefined : ((json['Items'] as Array<any>).map(JoblogicAPIModelsGetAllCGroupInvoicePaymentsItemFromJSON)),
    };
}

export function JoblogicAPIModelsGetAllCGroupInvoicePaymentsToJSON(json: any): JoblogicAPIModelsGetAllCGroupInvoicePayments {
    return JoblogicAPIModelsGetAllCGroupInvoicePaymentsToJSONTyped(json, false);
}

export function JoblogicAPIModelsGetAllCGroupInvoicePaymentsToJSONTyped(value?: JoblogicAPIModelsGetAllCGroupInvoicePayments | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(JoblogicAPIModelsGetAllCGroupInvoicePaymentsItemToJSON)),
    };
}

