/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JoblogicAPIModelsAbodeJobUpdateRequest
 */
export interface JoblogicAPIModelsAbodeJobUpdateRequest {
    /**
     * Joblogic Job Reference Guid
     * @type {string}
     * @memberof JoblogicAPIModelsAbodeJobUpdateRequest
     */
    missionOrderId: string;
    /**
     * Customer Appoiment Status
     * accept or decline
     * @type {string}
     * @memberof JoblogicAPIModelsAbodeJobUpdateRequest
     */
    status: string;
    /**
     * Additional Notes
     * @type {string}
     * @memberof JoblogicAPIModelsAbodeJobUpdateRequest
     */
    notes?: string | null;
}

/**
 * Check if a given object implements the JoblogicAPIModelsAbodeJobUpdateRequest interface.
 */
export function instanceOfJoblogicAPIModelsAbodeJobUpdateRequest(value: object): value is JoblogicAPIModelsAbodeJobUpdateRequest {
    if (!('missionOrderId' in value) || value['missionOrderId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function JoblogicAPIModelsAbodeJobUpdateRequestFromJSON(json: any): JoblogicAPIModelsAbodeJobUpdateRequest {
    return JoblogicAPIModelsAbodeJobUpdateRequestFromJSONTyped(json, false);
}

export function JoblogicAPIModelsAbodeJobUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsAbodeJobUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'missionOrderId': json['mission_order_id'],
        'status': json['status'],
        'notes': json['notes'] == null ? undefined : json['notes'],
    };
}

export function JoblogicAPIModelsAbodeJobUpdateRequestToJSON(json: any): JoblogicAPIModelsAbodeJobUpdateRequest {
    return JoblogicAPIModelsAbodeJobUpdateRequestToJSONTyped(json, false);
}

export function JoblogicAPIModelsAbodeJobUpdateRequestToJSONTyped(value?: JoblogicAPIModelsAbodeJobUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mission_order_id': value['missionOrderId'],
        'status': value['status'],
        'notes': value['notes'],
    };
}

