/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const JoblogicAPINoteEntityType = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_24: 24,
    NUMBER_63: 63,
    NUMBER_65: 65
} as const;
export type JoblogicAPINoteEntityType = typeof JoblogicAPINoteEntityType[keyof typeof JoblogicAPINoteEntityType];


export function instanceOfJoblogicAPINoteEntityType(value: any): boolean {
    for (const key in JoblogicAPINoteEntityType) {
        if (Object.prototype.hasOwnProperty.call(JoblogicAPINoteEntityType, key)) {
            if (JoblogicAPINoteEntityType[key as keyof typeof JoblogicAPINoteEntityType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function JoblogicAPINoteEntityTypeFromJSON(json: any): JoblogicAPINoteEntityType {
    return JoblogicAPINoteEntityTypeFromJSONTyped(json, false);
}

export function JoblogicAPINoteEntityTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPINoteEntityType {
    return json as JoblogicAPINoteEntityType;
}

export function JoblogicAPINoteEntityTypeToJSON(value?: JoblogicAPINoteEntityType | null): any {
    return value as any;
}

export function JoblogicAPINoteEntityTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): JoblogicAPINoteEntityType {
    return value as JoblogicAPINoteEntityType;
}

