/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JoblogicAPIModelsTagModel } from './JoblogicAPIModelsTagModel';
import {
    JoblogicAPIModelsTagModelFromJSON,
    JoblogicAPIModelsTagModelFromJSONTyped,
    JoblogicAPIModelsTagModelToJSON,
    JoblogicAPIModelsTagModelToJSONTyped,
} from './JoblogicAPIModelsTagModel';
import type { JoblogicAPIModelsStaffRoleModel } from './JoblogicAPIModelsStaffRoleModel';
import {
    JoblogicAPIModelsStaffRoleModelFromJSON,
    JoblogicAPIModelsStaffRoleModelFromJSONTyped,
    JoblogicAPIModelsStaffRoleModelToJSON,
    JoblogicAPIModelsStaffRoleModelToJSONTyped,
} from './JoblogicAPIModelsStaffRoleModel';

/**
 * 
 * @export
 * @interface JoblogicAPIModelsStaffGetDetailResponse
 */
export interface JoblogicAPIModelsStaffGetDetailResponse {
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsStaffGetDetailResponse
     */
    uniqueId?: string;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsStaffGetDetailResponse
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsStaffGetDetailResponse
     */
    address1?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsStaffGetDetailResponse
     */
    address2?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsStaffGetDetailResponse
     */
    address3?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsStaffGetDetailResponse
     */
    address4?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsStaffGetDetailResponse
     */
    postcode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsStaffGetDetailResponse
     */
    emailAddress?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsStaffGetDetailResponse
     */
    telephone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsStaffGetDetailResponse
     */
    mobile?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof JoblogicAPIModelsStaffGetDetailResponse
     */
    active?: boolean;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsStaffGetDetailResponse
     */
    staffType?: number;
    /**
     * 
     * @type {Array<JoblogicAPIModelsStaffRoleModel>}
     * @memberof JoblogicAPIModelsStaffGetDetailResponse
     */
    roles?: Array<JoblogicAPIModelsStaffRoleModel> | null;
    /**
     * 
     * @type {Array<JoblogicAPIModelsTagModel>}
     * @memberof JoblogicAPIModelsStaffGetDetailResponse
     */
    tags?: Array<JoblogicAPIModelsTagModel> | null;
}

/**
 * Check if a given object implements the JoblogicAPIModelsStaffGetDetailResponse interface.
 */
export function instanceOfJoblogicAPIModelsStaffGetDetailResponse(value: object): value is JoblogicAPIModelsStaffGetDetailResponse {
    return true;
}

export function JoblogicAPIModelsStaffGetDetailResponseFromJSON(json: any): JoblogicAPIModelsStaffGetDetailResponse {
    return JoblogicAPIModelsStaffGetDetailResponseFromJSONTyped(json, false);
}

export function JoblogicAPIModelsStaffGetDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsStaffGetDetailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'uniqueId': json['UniqueId'] == null ? undefined : json['UniqueId'],
        'name': json['Name'] == null ? undefined : json['Name'],
        'address1': json['Address1'] == null ? undefined : json['Address1'],
        'address2': json['Address2'] == null ? undefined : json['Address2'],
        'address3': json['Address3'] == null ? undefined : json['Address3'],
        'address4': json['Address4'] == null ? undefined : json['Address4'],
        'postcode': json['Postcode'] == null ? undefined : json['Postcode'],
        'emailAddress': json['EmailAddress'] == null ? undefined : json['EmailAddress'],
        'telephone': json['Telephone'] == null ? undefined : json['Telephone'],
        'mobile': json['Mobile'] == null ? undefined : json['Mobile'],
        'active': json['Active'] == null ? undefined : json['Active'],
        'staffType': json['StaffType'] == null ? undefined : json['StaffType'],
        'roles': json['Roles'] == null ? undefined : ((json['Roles'] as Array<any>).map(JoblogicAPIModelsStaffRoleModelFromJSON)),
        'tags': json['Tags'] == null ? undefined : ((json['Tags'] as Array<any>).map(JoblogicAPIModelsTagModelFromJSON)),
    };
}

export function JoblogicAPIModelsStaffGetDetailResponseToJSON(json: any): JoblogicAPIModelsStaffGetDetailResponse {
    return JoblogicAPIModelsStaffGetDetailResponseToJSONTyped(json, false);
}

export function JoblogicAPIModelsStaffGetDetailResponseToJSONTyped(value?: JoblogicAPIModelsStaffGetDetailResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'UniqueId': value['uniqueId'],
        'Name': value['name'],
        'Address1': value['address1'],
        'Address2': value['address2'],
        'Address3': value['address3'],
        'Address4': value['address4'],
        'Postcode': value['postcode'],
        'EmailAddress': value['emailAddress'],
        'Telephone': value['telephone'],
        'Mobile': value['mobile'],
        'Active': value['active'],
        'StaffType': value['staffType'],
        'Roles': value['roles'] == null ? undefined : ((value['roles'] as Array<any>).map(JoblogicAPIModelsStaffRoleModelToJSON)),
        'Tags': value['tags'] == null ? undefined : ((value['tags'] as Array<any>).map(JoblogicAPIModelsTagModelToJSON)),
    };
}

