/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JoblogicAPIModelsPurchaseOrderLineItemResponse
 */
export interface JoblogicAPIModelsPurchaseOrderLineItemResponse {
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsPurchaseOrderLineItemResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsPurchaseOrderLineItemResponse
     */
    purchaseOrderId?: string;
    /**
     * 
     * @type {Date}
     * @memberof JoblogicAPIModelsPurchaseOrderLineItemResponse
     */
    date?: Date;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsPurchaseOrderLineItemResponse
     */
    quantity?: number;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsPurchaseOrderLineItemResponse
     */
    discount?: number;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsPurchaseOrderLineItemResponse
     */
    description?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof JoblogicAPIModelsPurchaseOrderLineItemResponse
     */
    isDelivered?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof JoblogicAPIModelsPurchaseOrderLineItemResponse
     */
    dateDelivered?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsPurchaseOrderLineItemResponse
     */
    number?: string | null;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsPurchaseOrderLineItemResponse
     */
    totalVatAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsPurchaseOrderLineItemResponse
     */
    totalDiscountAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsPurchaseOrderLineItemResponse
     */
    totalExcludingVat?: number;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsPurchaseOrderLineItemResponse
     */
    totalExcludingVatIncludingDiscount?: number;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsPurchaseOrderLineItemResponse
     */
    taxRateValue?: number | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsPurchaseOrderLineItemResponse
     */
    nominalCode?: string | null;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsPurchaseOrderLineItemResponse
     */
    pricePerUnit?: number;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsPurchaseOrderLineItemResponse
     */
    partId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsPurchaseOrderLineItemResponse
     */
    groupLineItemId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsPurchaseOrderLineItemResponse
     */
    taxCodeUniqueId?: string | null;
}

/**
 * Check if a given object implements the JoblogicAPIModelsPurchaseOrderLineItemResponse interface.
 */
export function instanceOfJoblogicAPIModelsPurchaseOrderLineItemResponse(value: object): value is JoblogicAPIModelsPurchaseOrderLineItemResponse {
    return true;
}

export function JoblogicAPIModelsPurchaseOrderLineItemResponseFromJSON(json: any): JoblogicAPIModelsPurchaseOrderLineItemResponse {
    return JoblogicAPIModelsPurchaseOrderLineItemResponseFromJSONTyped(json, false);
}

export function JoblogicAPIModelsPurchaseOrderLineItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsPurchaseOrderLineItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['Id'] == null ? undefined : json['Id'],
        'purchaseOrderId': json['PurchaseOrderId'] == null ? undefined : json['PurchaseOrderId'],
        'date': json['Date'] == null ? undefined : (new Date(json['Date'])),
        'quantity': json['Quantity'] == null ? undefined : json['Quantity'],
        'discount': json['Discount'] == null ? undefined : json['Discount'],
        'description': json['Description'] == null ? undefined : json['Description'],
        'isDelivered': json['IsDelivered'] == null ? undefined : json['IsDelivered'],
        'dateDelivered': json['DateDelivered'] == null ? undefined : (new Date(json['DateDelivered'])),
        'number': json['Number'] == null ? undefined : json['Number'],
        'totalVatAmount': json['TotalVatAmount'] == null ? undefined : json['TotalVatAmount'],
        'totalDiscountAmount': json['TotalDiscountAmount'] == null ? undefined : json['TotalDiscountAmount'],
        'totalExcludingVat': json['TotalExcludingVat'] == null ? undefined : json['TotalExcludingVat'],
        'totalExcludingVatIncludingDiscount': json['TotalExcludingVatIncludingDiscount'] == null ? undefined : json['TotalExcludingVatIncludingDiscount'],
        'taxRateValue': json['TaxRateValue'] == null ? undefined : json['TaxRateValue'],
        'nominalCode': json['NominalCode'] == null ? undefined : json['NominalCode'],
        'pricePerUnit': json['PricePerUnit'] == null ? undefined : json['PricePerUnit'],
        'partId': json['PartId'] == null ? undefined : json['PartId'],
        'groupLineItemId': json['GroupLineItemId'] == null ? undefined : json['GroupLineItemId'],
        'taxCodeUniqueId': json['TaxCodeUniqueId'] == null ? undefined : json['TaxCodeUniqueId'],
    };
}

export function JoblogicAPIModelsPurchaseOrderLineItemResponseToJSON(json: any): JoblogicAPIModelsPurchaseOrderLineItemResponse {
    return JoblogicAPIModelsPurchaseOrderLineItemResponseToJSONTyped(json, false);
}

export function JoblogicAPIModelsPurchaseOrderLineItemResponseToJSONTyped(value?: JoblogicAPIModelsPurchaseOrderLineItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Id': value['id'],
        'PurchaseOrderId': value['purchaseOrderId'],
        'Date': value['date'] == null ? value['date'] : value['date'].toISOString(),
        'Quantity': value['quantity'],
        'Discount': value['discount'],
        'Description': value['description'],
        'IsDelivered': value['isDelivered'],
        'DateDelivered': value['dateDelivered'] == null ? value['dateDelivered'] : value['dateDelivered'].toISOString(),
        'Number': value['number'],
        'TotalVatAmount': value['totalVatAmount'],
        'TotalDiscountAmount': value['totalDiscountAmount'],
        'TotalExcludingVat': value['totalExcludingVat'],
        'TotalExcludingVatIncludingDiscount': value['totalExcludingVatIncludingDiscount'],
        'TaxRateValue': value['taxRateValue'],
        'NominalCode': value['nominalCode'],
        'PricePerUnit': value['pricePerUnit'],
        'PartId': value['partId'],
        'GroupLineItemId': value['groupLineItemId'],
        'TaxCodeUniqueId': value['taxCodeUniqueId'],
    };
}

