/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JoblogicAPIModelsSearchAssetItemResponse } from './JoblogicAPIModelsSearchAssetItemResponse';
import {
    JoblogicAPIModelsSearchAssetItemResponseFromJSON,
    JoblogicAPIModelsSearchAssetItemResponseFromJSONTyped,
    JoblogicAPIModelsSearchAssetItemResponseToJSON,
    JoblogicAPIModelsSearchAssetItemResponseToJSONTyped,
} from './JoblogicAPIModelsSearchAssetItemResponse';

/**
 * 
 * @export
 * @interface JoblogicAPIModelsSearchAssetResponse
 */
export interface JoblogicAPIModelsSearchAssetResponse {
    /**
     * 
     * @type {Array<JoblogicAPIModelsSearchAssetItemResponse>}
     * @memberof JoblogicAPIModelsSearchAssetResponse
     */
    items?: Array<JoblogicAPIModelsSearchAssetItemResponse> | null;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsSearchAssetResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsSearchAssetResponse
     */
    pageIndex?: number;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsSearchAssetResponse
     */
    pageSize?: number;
}

/**
 * Check if a given object implements the JoblogicAPIModelsSearchAssetResponse interface.
 */
export function instanceOfJoblogicAPIModelsSearchAssetResponse(value: object): value is JoblogicAPIModelsSearchAssetResponse {
    return true;
}

export function JoblogicAPIModelsSearchAssetResponseFromJSON(json: any): JoblogicAPIModelsSearchAssetResponse {
    return JoblogicAPIModelsSearchAssetResponseFromJSONTyped(json, false);
}

export function JoblogicAPIModelsSearchAssetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsSearchAssetResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['Items'] == null ? undefined : ((json['Items'] as Array<any>).map(JoblogicAPIModelsSearchAssetItemResponseFromJSON)),
        'totalCount': json['TotalCount'] == null ? undefined : json['TotalCount'],
        'pageIndex': json['PageIndex'] == null ? undefined : json['PageIndex'],
        'pageSize': json['PageSize'] == null ? undefined : json['PageSize'],
    };
}

export function JoblogicAPIModelsSearchAssetResponseToJSON(json: any): JoblogicAPIModelsSearchAssetResponse {
    return JoblogicAPIModelsSearchAssetResponseToJSONTyped(json, false);
}

export function JoblogicAPIModelsSearchAssetResponseToJSONTyped(value?: JoblogicAPIModelsSearchAssetResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(JoblogicAPIModelsSearchAssetItemResponseToJSON)),
        'TotalCount': value['totalCount'],
        'PageIndex': value['pageIndex'],
        'PageSize': value['pageSize'],
    };
}

