/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JoblogicAPIPaybandTimeType } from './JoblogicAPIPaybandTimeType';
import {
    JoblogicAPIPaybandTimeTypeFromJSON,
    JoblogicAPIPaybandTimeTypeFromJSONTyped,
    JoblogicAPIPaybandTimeTypeToJSON,
    JoblogicAPIPaybandTimeTypeToJSONTyped,
} from './JoblogicAPIPaybandTimeType';

/**
 * 
 * @export
 * @interface JoblogicAPIModelsRequestUpdatePaybandRateRequest
 */
export interface JoblogicAPIModelsRequestUpdatePaybandRateRequest {
    /**
     * 
     * @type {string}
     * @memberof JoblogicAPIModelsRequestUpdatePaybandRateRequest
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsRequestUpdatePaybandRateRequest
     */
    siteId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsRequestUpdatePaybandRateRequest
     */
    contractSiteId?: number | null;
    /**
     * 
     * @type {JoblogicAPIPaybandTimeType}
     * @memberof JoblogicAPIModelsRequestUpdatePaybandRateRequest
     */
    type: JoblogicAPIPaybandTimeType;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsRequestUpdatePaybandRateRequest
     */
    labourCostRate: number;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsRequestUpdatePaybandRateRequest
     */
    travelCostRate: number;
    /**
     * 
     * @type {number}
     * @memberof JoblogicAPIModelsRequestUpdatePaybandRateRequest
     */
    mileageCostRate: number;
    /**
     * Contractor Id in Joblogic
     * @type {string}
     * @memberof JoblogicAPIModelsRequestUpdatePaybandRateRequest
     */
    tenantId: string;
}



/**
 * Check if a given object implements the JoblogicAPIModelsRequestUpdatePaybandRateRequest interface.
 */
export function instanceOfJoblogicAPIModelsRequestUpdatePaybandRateRequest(value: object): value is JoblogicAPIModelsRequestUpdatePaybandRateRequest {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('labourCostRate' in value) || value['labourCostRate'] === undefined) return false;
    if (!('travelCostRate' in value) || value['travelCostRate'] === undefined) return false;
    if (!('mileageCostRate' in value) || value['mileageCostRate'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    return true;
}

export function JoblogicAPIModelsRequestUpdatePaybandRateRequestFromJSON(json: any): JoblogicAPIModelsRequestUpdatePaybandRateRequest {
    return JoblogicAPIModelsRequestUpdatePaybandRateRequestFromJSONTyped(json, false);
}

export function JoblogicAPIModelsRequestUpdatePaybandRateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoblogicAPIModelsRequestUpdatePaybandRateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['Id'],
        'siteId': json['SiteId'] == null ? undefined : json['SiteId'],
        'contractSiteId': json['ContractSiteId'] == null ? undefined : json['ContractSiteId'],
        'type': JoblogicAPIPaybandTimeTypeFromJSON(json['Type']),
        'labourCostRate': json['LabourCostRate'],
        'travelCostRate': json['TravelCostRate'],
        'mileageCostRate': json['MileageCostRate'],
        'tenantId': json['TenantId'],
    };
}

export function JoblogicAPIModelsRequestUpdatePaybandRateRequestToJSON(json: any): JoblogicAPIModelsRequestUpdatePaybandRateRequest {
    return JoblogicAPIModelsRequestUpdatePaybandRateRequestToJSONTyped(json, false);
}

export function JoblogicAPIModelsRequestUpdatePaybandRateRequestToJSONTyped(value?: JoblogicAPIModelsRequestUpdatePaybandRateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Id': value['id'],
        'SiteId': value['siteId'],
        'ContractSiteId': value['contractSiteId'],
        'Type': JoblogicAPIPaybandTimeTypeToJSON(value['type']),
        'LabourCostRate': value['labourCostRate'],
        'TravelCostRate': value['travelCostRate'],
        'MileageCostRate': value['mileageCostRate'],
        'TenantId': value['tenantId'],
    };
}

