/* tslint:disable */
/* eslint-disable */
/**
 * Joblogic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MicrosoftAspNetCoreJsonPatchOperationsOperation
 */
export interface MicrosoftAspNetCoreJsonPatchOperationsOperation {
    /**
     * 
     * @type {any}
     * @memberof MicrosoftAspNetCoreJsonPatchOperationsOperation
     */
    value?: any | null;
    /**
     * 
     * @type {string}
     * @memberof MicrosoftAspNetCoreJsonPatchOperationsOperation
     */
    path?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MicrosoftAspNetCoreJsonPatchOperationsOperation
     */
    op?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MicrosoftAspNetCoreJsonPatchOperationsOperation
     */
    from?: string | null;
}

/**
 * Check if a given object implements the MicrosoftAspNetCoreJsonPatchOperationsOperation interface.
 */
export function instanceOfMicrosoftAspNetCoreJsonPatchOperationsOperation(value: object): value is MicrosoftAspNetCoreJsonPatchOperationsOperation {
    return true;
}

export function MicrosoftAspNetCoreJsonPatchOperationsOperationFromJSON(json: any): MicrosoftAspNetCoreJsonPatchOperationsOperation {
    return MicrosoftAspNetCoreJsonPatchOperationsOperationFromJSONTyped(json, false);
}

export function MicrosoftAspNetCoreJsonPatchOperationsOperationFromJSONTyped(json: any, ignoreDiscriminator: boolean): MicrosoftAspNetCoreJsonPatchOperationsOperation {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'] == null ? undefined : json['value'],
        'path': json['path'] == null ? undefined : json['path'],
        'op': json['op'] == null ? undefined : json['op'],
        'from': json['from'] == null ? undefined : json['from'],
    };
}

export function MicrosoftAspNetCoreJsonPatchOperationsOperationToJSON(json: any): MicrosoftAspNetCoreJsonPatchOperationsOperation {
    return MicrosoftAspNetCoreJsonPatchOperationsOperationToJSONTyped(json, false);
}

export function MicrosoftAspNetCoreJsonPatchOperationsOperationToJSONTyped(value?: MicrosoftAspNetCoreJsonPatchOperationsOperation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'],
        'path': value['path'],
        'op': value['op'],
        'from': value['from'],
    };
}

