export const INVOICE_ENDPOINTS = {
  SAVE_SUPPLIER: '/api/PurchaseOrderSupplierInvoice/SaveSupplierInvoice',
  SAVE_SUBCONTRACTOR: '/SubContractorPO/SaveSubContractorInvoice',
  SAVE_SUBCONTRACTOR_LINE: '/SubContractorPO/SaveSubContractorInvoiceLine',
  GET_PO_LINE_ITEMS: '/api/PurchaseOrder/GetLineItemsJson',
  CREATE_CUSTOMER_INVOICE: '/Invoice/Create',
  SAVE_CUSTOMER_INVOICE_LINE: '/api/Invoice/SaveLine',
  APPROVE_CUSTOMER_INVOICE: '/api/Invoice/Approve',
  CREATE_CREDIT_INVOICE: '/Credit/Create',
  EDIT_CREDIT_NOTES: '/api/Credit/EditNotes',
  GET_CREDIT_REASONS: '/api/CreditReason/CreditReasonSearchJson',
  GET_CREDIT_LINES: '/Credit/GetLines',
  DELETE_CREDIT_LINE: '/Credit/DeleteLine',
  SAVE_CREDIT_INVOICE_LINE: '/Credit/SaveLine',
  APPROVE_CREDIT_INVOICE: '/Credit/Approve',
} as const;
